### PR TITLE
Mesosphere and Kubernetes documentation

### PR DESCRIPTION
**Pull request by juliandunn**
Thanks to @mattray

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @davidwrede to be a potential reviewer

**Comment by juliandunn** [comment]
gonna violate the four-eyes rule and approve my own PR

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit d9f6304 has been approved by `juliandunn`

**Comment by thesentinels** [comment]
:hourglass: Testing commit d9f6304 with merge d027136...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26785130)

**Pull request merged**
