### PR TITLE
Fixing more broken links

### PR DESCRIPTION
**Pull request by davidwrede**
- Fixing broken links from refactoring exercise
- Made internal links relative instead of absolute

Signed-off-by: David Wrede <dwrede@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by tashimi** [comment]
@davidwrede when the merge conflicts are gone, can we remove the do not merge label?

**Comment by davidwrede** [comment]
@tashimi Yup. Sorry, got hung up on some emergency house chores. I'll rebase and then remove the label if everything looks good.

**Comment by davidwrede** [comment]
Ready for review and merge.

**Comment by tashimi** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/282107895).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/282107895).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
