### PR TITLE
[plans] python 3.5.2 (updated)

### PR DESCRIPTION
**Pull request by miketheman**
Released 2016-06-26, includes security patches and much more.
See https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-2

Signed-off-by: Mike Fiedler <miketheman@gmail.com>

### CODE REVIEW

**Comment by smith** [comment]
@thesentinels r+

gif-keyboard-7442889294991808363

**Comment by thesentinels** [comment]
:pushpin: Commit f5ba536 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit f5ba536 with merge acdc903...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/141366889)

**Comment by smith** [comment]
[core/python/3.5.2/20160630162650](https://app.habitat.sh/#/pkgs/core/python/3.5.2/20160630162650) has been built and uploaded to the depot. 💖

**Pull request merged**
