### PR TITLE
Release 0.27.0

### PR DESCRIPTION
**Pull request by christophermaier**
tenor-201603205

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
tenor-243470374

**Comment by fnichol** [comment]
tenor-94227755

**Comment by fnichol** [comment]
"We've improved our soup!"

**Comment by tashimi** [comment]
bestcat

**Comment by raskchanky** [comment]
tenor-219914179

**Comment by chefsalim** [comment]
tenor-94459862

**Comment by adamhjk** [comment]
tenor-135760872

**Comment by tashimi** [comment]
failcat

**Comment by apriofrost** [comment]
https://media.giphy.com/media/l6Td5sKDNmDGU/giphy.gif

**Pull request merged**
