### PR TITLE
Added API docs to be served on sup :9631/

### PR DESCRIPTION
**Pull request by eeyun**
WAIT TO MERGE
Until we get the raml2html habitat package made. Once that is completed (hopefully in a few minutes) this should compile our RAML docs to HTML and serve them up as part of the binary when you attempt to hit the :9631/

This should keep users from having to hit habitat.sh/docs when they forget the REST endpoints for the supervisor.

Signed-off-by: eeyun <ihenry@chef.io>

### CODE REVIEW

**Comment by reset** [comment]
tenor-175313062

Yesssssss

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/230170924).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/230170924).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
