### PR TITLE
Add strReplace helper to templating language

### PR DESCRIPTION
**Pull request by rarenerd**
Signed-off-by: Kristian Vlaardingerbroek <kvlaardingerbroek@schubergphilis.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
This is going to be nice and useful!

gif-keyboard-1446416197013307187

**Comment by reset** [comment]
gif-keyboard-4915911098938646611

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/195120797).

**Pull request merged**
