### PR TITLE
Fixes documentation for template data

### LINKED ISSUE #2459: svc_default_user and svc_default_group not accessible in templates
- Mac OS 10.12
- Habitat 0.24.0/20170519202549

The [Plan interpolation](https://www.habitat.sh/docs/reference/plan-syntax/#pkg) section describes the following variables:

- svc_user_default
- svc_group_default

These values do not seem to be interpolated in templates:

```
{{pkg.svc_user_default}} #=> ""
```

However, `pkg.svg_user` works fine, as long as one is specified in the plan. I'd like to use the behavior of `svg_user_default` as described in the docs, but it always renders as the empty string.

### PR DESCRIPTION
**Pull request by rsertelon**
> Should fix #2459

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by tashimi** [comment]
@thesentinels approve 

tenor-263228946

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/313575911).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/313575911).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
