### PR TITLE
Adding a script to deploy unstable mac builds

### PR DESCRIPTION
**Pull request by raskchanky**
The purpose of this PR is to automatically generate unstable mac builds every time a PR is merged into master and publish those unstable builds to the unstable repo on bintray.

The `publish-hab.sh` script required a few changes and here's why.  We needed to install the jfrog-cli on the mac to publish to bintray.  The Linux builds used the hab `core/jfrog-cli` plan, which was at version 1.3 before this PR (I've built and uploaded 1.7 to the depot already).  The mac version that homebrew builds is 1.7, which is current.  In 1.7, the `--offer-config` global option no longer exists and is instead passed via an environment variable.

The second thing to note is that we now check if there is an unstable repo before trying to create it.  In version 1.3 of the jfrog-cli, a 0 exit code was returned regardless of whether the call to create a repo succeeded or failed.  In 1.7, the exit codes of the jfrog-cli seem to line up more closely with the HTTP status codes.  Trying to create an already existing repo returns a 409 Conflict, which means jfrog-cli exits non-zero and the entire script aborts.  Explicitly checking avoids this problem.

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
gif-keyboard-17273703884077353014

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/206810817).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/206810817).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
