### PR TITLE
Add Habitat Community Summit text to global message

### PR DESCRIPTION
**Pull request by magwalk**
Response to Kayleigh's request to add the banner ad to habitat.sh (https://chefio.atlassian.net/browse/CIA-1076)

screen shot 2016-09-14 at 10 16 04 am

### CODE REVIEW

**Comment by thesentinels** [comment]
@magwalk, thanks for your PR! By analyzing the annotation information on this pull request, we identified @cwebberOps, @ryankeairns and @davidwrede to be potential reviewers

**Comment by metadave** [comment]
:+1:, would you like me to merge or would you prefer someone from the web team to review?

**Comment by ryankeairns** [comment]
@magwalk thanks for tackling this one! Looks great :)

**Comment by reset** [comment]
@magwalk @ryankeairns this is now live!

**Comment by ryankeairns** [comment]
Thanks for pushing it out!

**Pull request merged**
