### PR TITLE
Added support for installing habitat from a semi-qualified version number

### PR DESCRIPTION
**Pull request by eeyun**
This is probably a dirty hack. Obviously temporary. Should run on busybox.

This is to respond to some of the issues presented in https://github.com/habitat-sh/habitat/issues/1896

Signed-off-by: Ian Henry <ihenry@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by eeyun** [comment]
Wanted to update this with more context for reviewers.

More or less we take the version provided and check whether it's formed in an expected way. If it is then we pass that along to the standard process. If it's not, then we take the version number provided and make a call to a different BT API and compare the available versions to the version provided. If we find one that matches the semi-qualified version then we pull the fully qualified version and pass that along to the standard process.

What I don't like about it: It's a _lot_ of string manipulation in bash, which feels bad. A tool like json_pp or jq would be ideal in the case of manipulating the returned json but I hesitated to bundle a full json library or perl script into what should eventually become a curlbash.

**Comment by fnichol** [comment]
We're getting pretty darn close on this--we think we have a mildly evil `sed` that'll operate on the minified JSON data to get us what we need and with the input cases (short version with one match, short version with multiple matches, version that isn't present, invalid string)

**Comment by eeyun** [comment]
Ok I've plugged in the changes that fletcher and I were pairing on this afternoon.  We now have a sed command to strip out our version numbers rather than awk, and this switch cleared up 2x bugs.

First: awk on busybox had slightly different functionality which caused the previous data manipulation to return the wrong things.
Second: The awk manipulation had a bug where it was possible for an incorrect version to be returned

This should work for as long as the APIs on BinTray continue to return minified json. If they switch that up, we'll need to change the sed script but the rest of the logic should remain sound.

**Comment by fnichol** [comment]
I added some final changes to the commit and I think we're really, really good here now:

* Updated the help message to show you can use a short version (ex: `"0.15.0"`)
* Fixed a bug in our trap cleanup code that didn't properly propagate the exit code (at least the second time I've made this exact mistake)
* Called `get_version` from `main()` to make it clearer when we determine our version
* Removed the `for` loop over 1 variable in `get_version()`--now it's a simple if/else
* Added a couple of `info` lines in `get_version()` to explain why we're making API calls to Bintray and what the value of our resulting Bintray version string
* Moved the location of `get_version()` to be ordered with the other top-level functions called by `main()`
* Wrapped the contents of `get_version()` to 80-chars (our shell code style)
* Sorted the `need_cmd` calls in `get_version()` lexically and added a missing one for `grep`
* Made the path to the version.json file absolute (i.e. it's set to `${workdir}/version.json`) to make future debugging via `DEBUG=1 sh install.sh` calls easier to trace
* Ran through `shellcheck` to ensure it continues to lint well (also added a couple of explicit lint ignores that are known-good in our situation)
* Squashed the commits down to 1 and rebased against master

Trust me, that's not as much as you'd think, mostly small changes for future maintenance ease.

I'm all 👍 on this now, we should be good to merge!!

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by reset** [comment]
gif-keyboard-17792092523274989603

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/209871582).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/209871582).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
