### PR TITLE
[builder-web] Make it so clicking outside the user-nav dropdown makes…

### PR DESCRIPTION
**Pull request by smith**
… it go away

gif-keyboard-4426270991134005478

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @ryankeairns and @metadave to be potential reviewers

**Comment by ryankeairns** [comment]
Works on my machine!
image

@thesentinels r+

**Comment by ryankeairns** [comment]
@thesentinels r+

**Comment by metadave** [comment]
@thesentinels r+

**Comment by metadave** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 83520fd has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 83520fd with merge 89a24b5...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/140825101)

**Pull request merged**
