### PR TITLE
Fix build error check ordering

### LINKED ISSUE #4025: Error reading pre_build.env file
Seeing a couple of errors like this on the live workers (origin name redacted in snippet below):

| 11/08/201710:10:12.000 -0800 | 2017-11-08 18:10:12,Failed studio build for <redacted>/sample-node-app, err=BuildEnvFile("/hab/svc/builder-worker/data/846396458917830656/out/pre_build.env", Error { repr: Os { code: 2, message: "No such file or directory" } })
-- | -- | --

We may need to be less aggressive failing if there is no pre_build.env file (eg, just log but not fail with this code?).

The relevant code is in the runner, the relevant failable functions are last_built and attempted_build

```
        if self.has_docker_integration() && status.success() {
            // TODO fn: This check should be updated in PackageArchive is check for run hooks.
            if self.workspace.last_built()?.is_a_service() {
                debug!("Found runnable package, running docker export");
                log_pipe.pipe_stdout(b"\n--- BEGIN: Docker export ---\n")?;
                status = DockerExporter::new(
                    util::docker_exporter_spec(&self.workspace),
                    &self.workspace,
                    &self.config.bldr_url,
                ).export(&mut log_pipe)?;
                log_pipe.pipe_stdout(b"\n--- END: Docker export ---\n")?;
            } else {
                debug!("Package not runnable, skipping docker export");
            }
        }

        if status.success() {
            self.workspace.last_built()
        } else {
            let ident = self.workspace.attempted_build()?;
            let op_ident = OriginPackageIdent::from(ident);
            self.workspace.job.set_package_ident(op_ident);
            Err(Error::BuildFailure(status.code().unwrap_or(-1)))
        }
```

### PR DESCRIPTION
**Pull request by elliott-davis**
Closes #4025

Signed-off-by: Travis Elliott Davis <edavis@chef.io>
tenor-234725457

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by chefsalim** [comment]
tenor-189255191

**Comment by chefsalim** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/299379576).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/299379576).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
