### PR TITLE
Update travis webhook for new homu

### PR DESCRIPTION
**Pull request by smith**
gif-keyboard-3745260270031174231

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk, @fnichol and @cwebberOps to be potential reviewers

**Comment by smith** [comment]
@thesentinels r+

:self-five:

**Comment by thesentinels** [comment]
:pushpin: Commit 94b8ba1 has been approved by `smith`

**Comment by thesentinels** [comment]
:pushpin: Commit 94b8ba1 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 94b8ba1 with merge b995c1c...

**Comment by thesentinels** [comment]
:hourglass: Testing commit 94b8ba1 with merge 94b8ba1...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/140111346)

**Comment by thesentinels** [comment]
:boom: Test timed out

**Pull request merged**
