### PR TITLE
[docs] Add section describing permanent-peer option

### LINKED ISSUE #1820: Document --permanent-peer behavior
Today I learned that `-I || --permanent-peer` is a thing!

We should document it as we have no mention in the docs pages.

### PR DESCRIPTION
**Pull request by webframp**
Some basic testing and code spelunking with git blame sort of helped me piece this together based on the original implementation in https://github.com/habitat-sh/habitat/commit/bf92fc79dd0c264c4afe3100c2228f7180aa8333 and comments from others in slack.

Hopefully fixes #1820 but review for accuracy/clarity is much appreciated.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by webframp** [comment]
Don't know what to do about netlify failure, but let me know if I need to do something

**Comment by fnichol** [comment]
@webframp sorry about that--I finally got some access to netlify and re-ran things and we're green now. Thank you for spelunking!

Closes #1820

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/257913629).

**Comment by thesentinels** [comment]
:broken_heart: Travis CI reports [this PR failed to pass the test suite](https://travis-ci.org/habitat-sh/habitat/builds/257913629).

The next step is to examine the [job](https://travis-ci.org/habitat-sh/habitat/builds/257913629) and figure out why. If it is transient, you can try re-triggering the Travis CI Job - if it passes, this PR will be automatically merged. If it is not transient, you should fix the issue and update this pull request, and issue `approve` again. If you believe it will never pass, and you are feeling :godmode:, you can issue a `force` to merge this PR anyway.

**Comment by webframp** [comment]
well that's odd for a doc change:
```
failures:
    manager::service::hooks::tests::compile_hook_table
```

but let me know and I'll fixup anything I need to

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/257913629).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/257913629).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by mwrock** [comment]
looks like a transient error. Passed on a retry. yay?

**Pull request merged**
