### PR TITLE
Add API for package stats

### PR DESCRIPTION
**Pull request by chefsalim**
This change add an API to provide basic package statistics from the builder scheduler. Currently, it provides the number of plans and builds that are in the DB. The stats will be used by the updated depot UX. Note: currently the number of plans are non-unique (ie, each version is counted separately - the may change in the future).

Signed-off-by: Salim Alam <salam@chef.io>

giphy 22

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

tenor-59766867

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by reset** [comment]
@chefsalim you should add this to the [api.raml](https://github.com/habitat-sh/habitat/blob/master/components/builder-api/doc/api.raml) doc for builder-api when you get a chance!

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/225740591).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/225740591).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
