### PR TITLE
Add "Container orchestration" to docs sidebar and Mesos cleanups

### PR DESCRIPTION
**Pull request by mattray**
Following up on feedback from Mesosphere.

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @davidwrede, @juliandunn, @leonhartX, @TrevorBramble and @ryankeairns to be potential reviewers

**Comment by juliandunn** [comment]
LGTM

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit d23ce54 has been approved by `juliandunn`

**Comment by thesentinels** [comment]
:hourglass: Testing commit d23ce54 with merge a73fe49...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/138493711)

**Pull request merged**
