### PR TITLE
cf-exporter

### PR DESCRIPTION
**Pull request by bodymindarts**
Signed-off-by: Justin Carter <justin@starkandwayne.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by tashimi** [comment]
tenor-84169204

**Comment by fnichol** [comment]
Looks pretty good, this is going to be fun!

I have a couple of small housekeeping tasks around this PR, so this might not hit master for a couple days (I'll add a do-not-merge tag for the team) and will shepard this in when ready. Thanks!

**Comment by fnichol** [comment]
(but assume this is an accepted pull request :smile: )

**Comment by fnichol** [comment]
Thanks for everyone's patience! #3590 had some of the extra housekeeping items to roll this into the next release and ensure it can be called without the need to prefix `hab pkg exec`.

**Pull request merged**
