### PR TITLE
Integrate projects with the package details page

### PR DESCRIPTION
**Pull request by raskchanky**
This introduces some plumbing and gives two new buttons on the package details page:  `View <origin-name> origin` and `Connect a repo`.

`Connect a repo` creates a project for the given package, to be used by the forthcoming build service.

`View <origin-name> origin` is just a shortcut to clicking `Origins` in the sidebar and then clicking on the `<origin-name>` origin.

This also provides a list of packages on the origin details page and links to connect them to repos or view versions of packages from there.

Giant caveat to merging this:  The backend API doesn't currently return VCS information for a project so this feature was written and tested with that info artificially injected into the server response.  We probably want a full end-to-end test of this before merging.

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
@raskchanky, thanks for your PR! By analyzing the annotation information on this pull request, we identified @smith, @ryankeairns, @metadave and @reset to be potential reviewers

**Comment by reset** [comment]
@raskchanky this looks good! Let's wait on #1080 to merge this in so we can take advantage of hiding the builder stuff with feature flags. I'm thinking that #1080 will be ready today, so it shouldn't be too long ;)

**Comment by reset** [comment]
@raskchanky this looks great, I'm going to merge it in but let's follow up with another PR on the feature flag business before we ship any of this!

**Comment by reset** [comment]
gif-keyboard-5079742325098205095

**Pull request merged**
