### PR TITLE
Propagate HAB_STUDIO_SUP into container

### LINKED ISSUE #2502: Setting `HAB_STUDIO_SUP=false` does not work with Docker studios and this should be documented
We might recommend something like this for output inside the Studio when entering (note the last sentence):
```
--> To prevent a Supervisor from running automatically in your
    Studio, export 'HAB_STUDIO_SUP=false' before running
    'hab studio enter'. If you are using a Docker-based Studio, 
    set this in `.studiorc`.
```

### PR DESCRIPTION
**Pull request by smith**
Fixes #2502. 

tenor-187492972

### CODE REVIEW

**Comment by mwrock** [comment]
looks good to me but needs some formatting love.

**Comment by smith** [comment]
> looks good to me but needs some formatting love.

@mwrock should be fixed in e2544d6.

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/237747878).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/237747878).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/237747878).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/237747878).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
