### PR TITLE
[merged] use correct homu server for travis

### PR DESCRIPTION
**Pull request by smith**
gif-keyboard-9357438981322399352

### CODE REVIEW

**Comment by thesentinels** [comment]
@smith, thanks for your PR! By analyzing the annotation information on this pull request, we identified @fnichol, @adamhjk, @cwebberOps and @reset to be potential reviewers

**Comment by smith** [comment]
@thesentinels r+

**Comment by smith** [comment]
@thesentinels r+

**Comment by smith** [comment]
@thesentinels r+

**Comment by smith** [comment]
@thesentinels retry

**Comment by smith** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 3a10518 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 3a10518 with merge 874a307...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/146473598)
Approved by: smith
Pushing 874a307b13d56e566708f5c1c51ce5e7340f3873 to master...

**Pull request closed without merging**
