### PR TITLE
Add metrics endpoint to supervisor

### PR DESCRIPTION
**Pull request by jamesc**
This add a new endpoint `/metrics` to the supervisor that exports prometheus-style metrics.

Right now it exports HTTP metrics for all the endpoints in the side car and a `habitat_package_info` metrics which shows package metadata.  Sample output is:

```
# HELP habitat_package_info package version information
# TYPE habitat_package_info gauge
habitat_package_info{name="redis",origin="core",release="20161104175435",version="3.2.4"} 1
# HELP http_request_duration_seconds HTTP request latencies in seconds.
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_bucket{handler="config",le="0.005"} 1
http_request_duration_seconds_bucket{handler="config",le="0.01"} 1
http_request_duration_seconds_bucket{handler="config",le="0.025"} 1
http_request_duration_seconds_bucket{handler="config",le="0.05"} 1
http_request_duration_seconds_bucket{handler="config",le="0.1"} 1
http_request_duration_seconds_bucket{handler="config",le="0.25"} 1
http_request_duration_seconds_bucket{handler="config",le="0.5"} 1
http_request_duration_seconds_bucket{handler="config",le="1"} 1
http_request_duration_seconds_bucket{handler="config",le="2.5"} 1
http_request_duration_seconds_bucket{handler="config",le="5"} 1
http_request_duration_seconds_bucket{handler="config",le="10"} 1
http_request_duration_seconds_bucket{handler="config",le="+Inf"} 1
http_request_duration_seconds_sum{handler="config"} 0.000456555
http_request_duration_seconds_count{handler="config"} 1
http_request_duration_seconds_bucket{handler="metrics",le="0.005"} 4
http_request_duration_seconds_bucket{handler="metrics",le="0.01"} 4
http_request_duration_seconds_bucket{handler="metrics",le="0.025"} 4
http_request_duration_seconds_bucket{handler="metrics",le="0.05"} 4
http_request_duration_seconds_bucket{handler="metrics",le="0.1"} 4
http_request_duration_seconds_bucket{handler="metrics",le="0.25"} 4
http_request_duration_seconds_bucket{handler="metrics",le="0.5"} 4
http_request_duration_seconds_bucket{handler="metrics",le="1"} 4
http_request_duration_seconds_bucket{handler="metrics",le="2.5"} 4
http_request_duration_seconds_bucket{handler="metrics",le="5"} 4
http_request_duration_seconds_bucket{handler="metrics",le="10"} 4
http_request_duration_seconds_bucket{handler="metrics",le="+Inf"} 4
http_request_duration_seconds_sum{handler="metrics"} 0.001889247
http_request_duration_seconds_count{handler="metrics"} 4
# HELP http_requests_total Total number of HTTP requests made.
# TYPE http_requests_total counter
http_requests_total{handler="config"} 1
http_requests_total{handler="metrics"} 5
```

Other metrics are easily added.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by metadave** [comment]
nice!

**Comment by adamhjk** [comment]
gif-keyboard-9690358160778767190

**Comment by adamhjk** [comment]
Whats the thinking on service defined metrics? Is this something that we can let people easily extend via hooks?

**Comment by jamesc** [comment]
Yep, I think a hook would be the right way.  If it is there we would call it and concatenate onto the end of the habitat specific metrics.

**Comment by smurawski** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/198883427).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/198883427).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
