### PR TITLE
Use best practices in artifactory-pro run hook

### PR DESCRIPTION
**Pull request by schisamo**
These updates are based on feedback from @jamesc in #989.

Signed-off-by: Seth Chisamore <schisamo@chef.io>

/cc @smith

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by reset** [comment]
@thesentinels r+

Thank you!

**Comment by smith** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit bb3152b has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit bb3152b with merge 53eaf2b...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/140598618)

**Comment by smith** [comment]
Built and uploaded to depot: https://app.habitat.sh/#/pkgs/core/artifactory-pro/4.8.1/20160628172056

**Pull request merged**
