### PR TITLE
Updates file to rustfmt standard

### PR DESCRIPTION
**Pull request by burtlo**
I'm new to the project and new to Rust. I like learning about
tools and how I can use them to ensure the code I write integrates
smoothly and correctly with my peers. Thank you for taking the time
to review this Pull Request.

Signed-off-by: Franklin Webber <franklin@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

**Comment by reset** [comment]
@thesentinels force

**Comment by thesentinels** [comment]
Excellent @reset! It always makes me feel nice when humans approve of one anothers work, no matter the consequences. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
