### PR TITLE
Allow specifying organization and repo in Bintray publish tools

### PR DESCRIPTION
**Pull request by reset**
* Add `-o` flag to publish-hab and publish-studio for specifying
  the Bintray organization to publish to
* Add `-r` flag to publish-hab and publish-studio for specifying
  the Bintray repo to publish to

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
This is required for easily publishing unstable builds so I'm gonna merge this one in myself

gif-keyboard-9912724907607691711

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/177342307).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/177342307).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
