### PR TITLE
Updated Banner to pull latest event

### PR DESCRIPTION
**Pull request by eeyun**
Previous bugs have been resolved. This code shouldn't live long as our functionality for retrieving events needs to be fleshed out and likely rewritten. This banner should be able to display several different types of content.

Otherwise it should actually be good to merge as an interstitial fix.

Signed-off-by: eeyun <ihenry@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
As long as we make an issue to consolidate this and the other community events JS into one piece of functionality that can perform both jobs, this seems fine to me as a temporary fix.  👍 

@cnunciato thoughts?

**Comment by cnunciato** [comment]
Yeah, I agree -- I'll make that issue and think a bit on this as well.

**Comment by cnunciato** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/245107684).

**Comment by cnunciato** [comment]
Also:

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/245107684).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
