### PR TITLE
Bump handlebars to 0.19.0

### PR DESCRIPTION
**Pull request by reset**
Version `0.19.0` contains some rendering fixes introduced by @metadave. See #1083 for details

Signed-off-by: Jamie Winsor <jamie@vialstudios.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
@reset, thanks for your PR! By analyzing the annotation information on this pull request, we identified @adamhjk, @metadave and @fnichol to be potential reviewers

**Comment by metadave** [comment]
we should bump to 0.19.1 to include https://github.com/sunng87/handlebars-rust/issues/93

**Comment by reset** [comment]
@metadave got it!

**Comment by smith** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 41cf3e5 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 41cf3e5 with merge 9e1ab14...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/147564548)

**Pull request merged**
