### PR TITLE
Add AWS CLI plan

### PR DESCRIPTION
**Pull request by smith**
gif-keyboard-979612365119967721

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by reset** [comment]
@thesentinels r+

gif-keyboard-1064791249822163614

**Comment by thesentinels** [comment]
:pushpin: Commit 324eaee has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 324eaee with merge c1dcbe1...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/141703270)

**Pull request merged**
