### PR TITLE
Readme Refactor

### PR DESCRIPTION
**Pull request by eeyun**
Split readme into 3 separate docs: README.md CONTRIBUTING.md and BUILDING.md as it was getting rather long in the tooth. 

Hopefully this is a bit less daunting to look at as the landing page of the repo and should still expose links to all of the information that was present before.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by eeyun** [comment]
Oh yeah absolutely. One moment.

**Comment by eeyun** [comment]
And actually at that point I wonder if we shouldn't just remove that docs directory. Seems silly to have a directory with a single .md file in it.

**Comment by ryankeairns** [comment]
@eeyun makes sense, it was rather long :) Is it possible to add links from the README to these other information docs? so links to CONTRIBUTING, BUILDING and UX_PRINCIPLES ?

**Comment by eeyun** [comment]
Absolutely @ryankeairns let me do that while im condensing down the building_windows.md too

**Comment by jjasghar** [comment]
🤘 awesome.

**Comment by eeyun** [comment]
@thesentinels approve

Alt Text

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/172118879).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/172118879).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
