### PR TITLE
Make launcher exit status indicate if supervisor exited with a fatal error

### PR DESCRIPTION
**Pull request by baumanj**
See https://github.com/habitat-sh/habitat/issues/5169

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
I don't see anything here that would have a negative impact on Windows or even differ there @baumanj

**Comment by christophermaier** [comment]
This looks good. I think we should hold off merging right this second, because the core plans refresh brought in a change to glibc that dropped support for older Linux kernels. Until the core plans team sorts that situation out, we'll need to pin back to older versions to ensure that the Launcher still works on the older kernels we support; otherwise the next Launcher release won't work on those kernels.

**Comment by baumanj** [comment]
What should our strategy be here? I think we've finished the pinning work, but how do we move forward with launcher (or any other pinned `core` package) changes at this point?

**Comment by christophermaier** [comment]
@baumanj There shouldn't be a problem. Let's get this rebased and merged.

**Pull request merged**
