### PR TITLE
Add archive section to the jobsrv configuration file

### PR DESCRIPTION
**Pull request by christophermaier**
Turns out you need this; who knew? ;)

Signed-off-by: Christopher Maier <cmaier@chef.io>

### CODE REVIEW

**Comment by mwrock** [comment]
seems like the db tests are getting stuck. This is probably unrelated to this PR but more likely trlated to a recent new build of core/postgresql

**Comment by chefsalim** [comment]
LGTM

**Comment by christophermaier** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/240971818).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/240971818).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
