### PR TITLE
Fix broken link to ruby-rails-sample

### PR DESCRIPTION
**Pull request by RubyTuesdayDONO**

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
@RubyTuesdayDONO thank you for the link updates--clearly we didn't catch every one when we split the core plans out into their own repo.

The only book-keeping item left is to add a [DCO](https://github.com/habitat-sh/habitat/blob/master/CONTRIBUTING.md#signing-your-commits) to the bottom of your commit message. Assuming that you still have this repo cloned and you have you `user.name` and `user.email` setup in your `.gitconfig`,you should be able to do the following:

```sh
# Check out the PR branch
git checkout patch-1

# Alter the commit message by adding a DCO line at the bottom, based on your Git config
git commit --amend --no-edit --signoff

# Force push the modified commit (note: normally speaking, you don't want to go
# around force-pushing, but in this case it's legit)
git push origin patch-1 --force
```

gif-keyboard-8527198766235414135

**Comment by RubyTuesdayDONO** [comment]
Thank you for the feedback! Sorry about missing the DCO -- I realize that's important. I composed this PR lazily from Github's quick-edit web UI, so I might have to decline and re-issue it from the CLI to get the DCO in there (will see if I can do it this weekend, but might be delayed). 

Cheers to Habitat's growing success in the new year!

**Comment by fnichol** [comment]
@RubyTuesdayDONO would you consent if I added the following line to your commit message? 

```
Signed-off-by: Reuben Garrett <some@email.addr>
```

Agreeing to this would agreeing to the DCO and would be just as good. I'd only need an email for yourself to add to the DCO line which you could give either here, or email me at the email address listed in my GitHub profile. Thanks!

**Comment by fnichol** [comment]
It looks like the docs have updated to a newer example so we should be good to close. Thanks!

**Pull request closed without merging**
