### PR TITLE
Warn when installing a fully qualified package not present in the given channel

### LINKED ISSUE #2722: Change hab pkg install logic
We need to do two things:

1. If you do a `hab pkg install` and you specify a fully qualified package name, e.g. `hab pkg install core/redis/3.2.4/20170514150022` and that fully qualified package is _not_ in the channel you've specified (either explicitly via the `--channel` flag or the implicit `stable` channel) then the `hab` CLI should warn you that we're going to install the package anyway, even though it's not in that channel.

2. For all transitive dependencies, we need to ignore the channel completely and just straight up install them.  Transitive dependencies are always fully qualified so there's never any ambiguity and warning the user in this case is not necessary.

### PR DESCRIPTION
**Pull request by raskchanky**
This adds a warning if you try to `hab pkg install` a fully qualified package identifier, e.g. `core/redis/3.2.4/20170514150022` and that package doesn't exist in the channel that's specified.  If no channel is specified, then `stable` is assumed.

I've also added a few clarifying comments in places that felt relevant as I was reviewing the existing code.

tenor-245383576

Closes #2722 

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
tenor-262122422

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/253699164).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/253699164).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
