### PR TITLE
Added myself to MAINTAINERS.md

### PR DESCRIPTION
**Pull request by mjingle**
Signed-off-by: mjingle mjinglewski@chef.io

tenor-54285946

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@mjingle Thanks, but we'll need a DCO line in your commit to merge this; see https://github.com/habitat-sh/habitat/blob/master/CONTRIBUTING.md#signing-your-commits

(Looks like you may have been using Github's direct editing feature for this PR? If so, I don't think it adds that for you, unfortunately. You'll need to use a Git client from your workstation.)

**Comment by mjingle** [comment]
@christophermaier I tried checking out the branch and it's not there. Are there other things I can do to troubleshoot?

**Comment by christophermaier** [comment]
@mjingle Looks like it's been created in a fork in your account: https://github.com/mjingle/habitat/tree/patch-4. If you clone that, add `user.name` and `user.email` to your local config, and then run `git commit --amend --signoff`, that ought to fix it. Force-pushing that back to your repository ought to do the trick. 

Ping me if you run into any other issues and we'll get you sorted out!

**Comment by mjingle** [comment]
Something is really weird about this PR I created. I'm just going to close this and try a new one. Thank you for your help and patience with me, @christophermaier!

**Pull request closed without merging**
