### PR TITLE
Correcting -taskname to -tasklist

### PR DESCRIPTION
**Pull request by rrxtns**
This is a minor doc correction for building windows Hab -taskname --> -tasklist

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by rrxtns** [comment]
Attesting inline per Slack discussions:

Signed-off-by: Syntax Error <rrxtns@users.noreply.github.com>

**Comment by juliandunn** [comment]
hi @rrxtns - with respect to the DCO, [we'll need your real name](https://github.com/habitat-sh/habitat#signing-your-commits) as part of the actual commit message. You can set these in your `~/.gitconfig` as `user.name` and `user.email` and then `git commit --amend -s`  your last commits to sign them off.

**Comment by smurawski** [comment]
@rrxtns We'll get this fixed up monday (per our chat on slack).

**Comment by smurawski** [comment]
@rrxtns I'm going to close this in favor of #1281 which has your commit as well.  Thanks for the contribution!

**Pull request closed without merging**
