### PR TITLE
Upgrade crates, primarily serde 0.9 and toml 0.3 APIs

### PR DESCRIPTION
**Pull request by fnichol**
This change primarily upgrades the codebase from serde 0.8 to 0.9 and
consequently from toml 0.2 to 0.3. Other dependent crates were also
updated as a full update hasnt taken place in over a month.

Currently the urlencoded crate still takes a dependency on an older
bodyparser which in turn depends on serde 0.8 which is why there are 2
versions of these dependencies in the full graph.

Serde and toml Release Notes
----------------------------

* https://github.com/serde-rs/serde/releases/tag/v0.9.0
* alexcrichton/toml-rs@f66d8bc

Of special note: the toml API updates in most cases introduce a
Result-wrapped return and therefore introduce more explicit cases where
the error may need to be handled. Some functions which use these API
calls don't return a Result themselves and therefore some uses of
`.expect()` were used (usually with a TODO left).

---

There are 2 addition commits, one which adds tests for `core::config::ParseInto` implementations (with consequent refactoring) and another which adds support to `ParseInto` for `PackageIdent`. This latter commit may be revisited in future work and was the initial driving work that led to the serde updates (to get at new toml 0.3 behavior). Pull the thread on your sweater, see what happens!

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
WOW! Change a crate...change the world.

Overall, the refactorings the update gets us looks really nice. I really like `serialize_field` over `serialize_struct_elt`.

Huge props on the tests in core config! That is great.

I wonder if we want to address the `expect`s in the supervisor code sooner (now) than later. This could break our rule of "the supervisor can never crash". I ave not really looked, but not sure how big of a refactor that would be.

**Comment by mwrock** [comment]
I'm also guessing this PR may impact @smurawski 's current work.

**Comment by fnichol** [comment]
@mwrock I wanted to take note of increasing our `.expect()` count in the Supervisor but we shouldn't be much worse off than before (the previous toml API simply returned `None` and carried on silently in some cases). It should be a topic for the team in the near future. Having some simple guidelines for where `panic!()`, `.unwrap()`, and `expect()` are okay (justifiable) and not okay (leading to thread panics that can't be recovered) would help us all when we see them elsewhere. For example, `.unwrap()` in testing code is **the best!!**

I'm okay to move forward merging this PR if it helps others rebase and carry forward--I'm happy to have called this out at least!

**Comment by mwrock** [comment]
Fair enough @fnichol! I just wanted to raise the topic. Lets push this through.

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/204681757).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/204681757).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/204681757).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by reset** [comment]
gif-keyboard-14696415766178491025

**Pull request merged**
