### PR TITLE
Add Justin Carter as core habitat maintainer

### PR DESCRIPTION
**Pull request by bodymindarts**

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by bodymindarts** [comment]
Gladly @adamhjk :-)

**Comment by raskchanky** [comment]
tumblr_mrnkq6nmy41scwli8o1_400

**Comment by adamhjk** [comment]
gif-keyboard-143885175834025857

**Comment by reset** [comment]
gif-keyboard-15913864449047670170

**Pull request merged**
