### PR TITLE
[pkg-export-docker] Build in runtime ident for Docker package.

### PR DESCRIPTION
**Pull request by fnichol**
This change will build the fully qualified package identifier for the
version of `core/docker` which it was built against into the binary when
building under Habitat. If it is built in development, a package
identifier of `core/docker` will be used and the program will fail if
the package is not installed.

The package-resolving code was originally in `builder-worker`, but this
change extracted `resolve_cmd_in_pkg()` to `core`.

Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by christophermaier** [comment]
@fnichol I think I missed it; how does the value of `PLAN_DOCKER_PKG_IDENT` get changed based on the environment in which it's built?

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/282046986).

**Comment by fnichol** [comment]
@christophermaier It is a bit subtle.

* the component's `build.rs` checks for the presence of an environment variable (https://github.com/habitat-sh/habitat/pull/3437/files#diff-748cecbade5b4699329195de54e10313R11) 
* which we export in our plan (https://github.com/habitat-sh/habitat/pull/3437/files#diff-5742918e97ebc71216ed5f6c8bdb0a31R66)
* otherwise, if compiling locally, the `build.rs` falls back to a fuzzy pkg ident
* the build program writes a file at compile time who's string value get inlined into the rust source with the `include_str!()` macro
* and finally, we resolve that pkg ident (either fully qualified or fuzzy) once in a static and use it for the remainder of the program

**Comment by fnichol** [comment]
It's building on a pattern we've learned over time about reading our common `VERSION` file and inlining it into a Rust constant in the binary. Then overriding that with a build-provided value when building under Habitat.

**Comment by christophermaier** [comment]
@fnichol Ah, I see... I may have misread your initial PR message; for some reason I was thinking it was supposed to be keying off of whether or not the Rust code was compiled with debug flags or not and was wondering what dark Rust magic I was missing.

Now that _that's_ cleared up (sheesh!), this all makes perfect sense. 👍

**Comment by fnichol** [comment]
It's one crazy and amazing way that vanilla Rust compilation and vanilla Habitat package building come together for even more runtime certainty.

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/282046986).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
