### PR TITLE
Restructure 'service.tick' code to correct order of hook execution

### PR DESCRIPTION
**Pull request by bodymindarts**
This fixes 2 issues:
- hooks don't execute while an election is in progress
- the reconfigure hook is consistently called after the run hook (also
  on restarts) as documented

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by bodymindarts** [comment]
@reset Opened a new PR based off of current master.

Unfortunately it is not possible for me to try out my locally built hab-sup in a real scenario. Could be that there are still some tweaks necessary that I would find when trying to run it. I've opened a ticket https://github.com/habitat-sh/habitat/issues/1753 that refers to that issue.

**Comment by bodymindarts** [comment]
I've found a way to run it locally now to verify the behaviour.

There is an issue with copying the run hook but when building current master it looks like the issue is already present before my changes.

Here is the output from running `hab-sup start core/postgresql` the current master version of hab-sup:
```
hab-sup(MN): Starting core/postgresql
hab-sup(MR): Butterfly Member ID 714363f45ce34c15933a8765a811d5af
hab-sup(MR): Starting butterfly on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
postgresql.default(SR): Initializing
hab-sup(SC): Updated pwfile 5b4b01a4a3892ea3751793da57f072ae08eec694ddcda872239fc8239e4bcd1b
hab-sup(SC): Updated pg_ident.conf 0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8
hab-sup(SC): Updated postgresql.conf 520f0b4f92b53312db6c512e577af98e2fe76c09d774eb81bfd62bb7fcc50b41
hab-sup(SC): Updated pg_hba.conf 84fb71bb84f392d069f3dc1c19d282badb7e217adb865f6a62c54a733b27904d
postgresql.default(SR): Error finding run file: No such file or directory (os error 2)
postgresql.default(SV): Starting process as user=hab, group=hab
postgresql.default(SR): Service restart failed: hab-sup(ER)[src/error.rs:361:8]: No such file or directory (os error 2)
```

**Comment by reset** [comment]
I found some issues in my rework and will address them this weekend and then comment back here

**Comment by reset** [comment]
@bodymindarts this [PR](https://github.com/habitat-sh/habitat/pull/1755) should address the problems with the server loop in the master branch. Unfortunately these changes will create a conflict in your refactors again. I hate to do this to you again, but I needed to get it in a working position quickly. If you'd like to refactor around it one more time please feel free, but the offer still stands to see these changes over the finish line for you.

**Comment by bodymindarts** [comment]
No problem I will rebase off your branch.

**Comment by bodymindarts** [comment]
Closed in favour of https://github.com/habitat-sh/habitat/pull/1757

**Pull request closed without merging**
