### PR TITLE
Disallow multiple simultaneous builds of same project

### PR DESCRIPTION
**Pull request by chefsalim**
This change adds a new check to the builder scheduler. Before dispatching a group of builds, the scheduler will now check to see if a group with the same root project is already in progress. If so, the group create request will be failed with an ENTITY_CONFLICT error. 

Signed-off-by: Salim Alam <salam@chef.io>

tenor-235307634

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
tenor-1292007

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/260832560).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/260832560).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
