### PR TITLE
Bump all crate dependencies

### PR DESCRIPTION
**Pull request by reset**
tenor-35407375

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
looks like jobsrv is not happy on windows. Might not be directly related to this. checking now.

**Comment by mwrock** [comment]
hmm. master compiles fine

**Comment by mwrock** [comment]
compiling locally with this PR and can add a fix commit

**Comment by reset** [comment]
@mwrock just got it!

**Comment by mwrock** [comment]
cool

**Comment by reset** [comment]
I'm going to wait on this one - hyper is in an alpha release and there's quite a bit of conflicting requirements between it and Iron

**Pull request closed without merging**
