### PR TITLE
Improve Kubernetes documentation

### PR DESCRIPTION
**Pull request by asymmetric**
This improves the [Kubernetes documentation](https://www.habitat.sh/docs/best-practices/#kubernetes) in several ways:

* Adds details about the Operator
* Adds Helm examples
* Explains how to work without the operator

/cc @LiliC @zeenix @krnowak

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/343874273).

**Comment by christophermaier** [comment]
@asymmetric Looks like good additions here; thanks! At some point, we're probably going to want a more in-depth tutorial, as well as more in-depth documentation, but this helpfully provides links to all the current relevant information.

@tashimi @ryankeairns Thoughts?

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/343874273).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by ryankeairns** [comment]
@christophermaier yep, we recently updated the Kubernetes "Get Started" page to link to the best practices docs that are updated in this PR. See here - https://www.habitat.sh/get-started/kubernetes/

**Comment by christophermaier** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/343891074).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
