### PR TITLE
0.30.2 release

### PR DESCRIPTION
**Pull request by reset**
tenor-95333649

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by chefsalim** [comment]
image

**Comment by chefsalim** [comment]
Oh wait - version is not right

**Comment by reset** [comment]
Got it!

**Comment by fnichol** [comment]
tenor-37683739

**Pull request merged**
