### PR TITLE
fix broken mesos image links

### PR DESCRIPTION
**Pull request by mattray**

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by davidwrede** [comment]
Looks good.

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit d1198c0 has been approved by `davidwrede`

**Comment by thesentinels** [comment]
:hourglass: Testing commit d1198c0 with merge cf5a28d...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139262051)

**Pull request merged**
