### PR TITLE
Make the plans' build use rust-toolchain version

### PR DESCRIPTION
**Pull request by baumanj**
Set the particular version of `core/rust` that the habitat components depend upon to build based on the `rust-toolchain` file that governs plain `cargo`-based builds of these crates.

### CODE REVIEW

**Comment by mwrock** [comment]
Interesting. It also looks likr the 1.35 package was never promoted

**Comment by raskchanky** [comment]
@mwrock I promoted it just now

**Comment by mwrock** [comment]
cool i built and promoted the windows rust and added commit to affect the relevant ps1 plans

**Comment by baumanj** [comment]
This is ready for review now. I think team Scott (@scotthain & @smacfarlane) will likely be the best judges of whether I've done something ill-advised.

**Comment by baumanj** [comment]
> So in the general case, I would be against pinning here because it goes against our overall strategies of drinking our own champagne first.

Can you elaborate?

The idea is that we upgrade to new versions of rust once we've locally verified that everything in `habitat` seems to build and run correctly (and hopefully we fix up new warnings and such), and then we can flip the switch to a new version in exactly one place. Why wouldn't we want a `cargo build -p hab` and `build components/hab` (in a studio) to build using the same rust version?

**Comment by scotthain** [comment]
I'm more referring to "take the latest as it is released" - we will build automation that will do that when new `core/rust` is released so we can verify what needs to be fixed as needed. When I said "pinning here" i meant in the hab project, not in a rust-toolchain file, I'm all for the pinning in 1 place.

**Pull request merged**
