### PR TITLE
#3819 - adding download links

### PR DESCRIPTION
**Pull request by mgamini**
Signed-off-by: Garrett Amini <kadjar@gmail.com>

tenor-188586499

https://github.com/habitat-sh/habitat/issues/3819

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
Probly be good to squash your commits just as a general practice, but otherwise, 🤘 !

**Comment by mgamini** [comment]
@cnunciato squishied!

**Comment by christophermaier** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/298075498).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/298075498).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by ryankeairns** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
Sorry; I had a problem deploying this change to acceptance. The error was:

```ruby
Expected process to exit with [0], but received '128'
---- Begin output of git fetch origin pull/3990/merge ----
STDOUT: 
STDERR: Warning: Permanently added 'github.com,192.30.255.113' (RSA) to the list of known hosts.
fatal: Couldn't find remote ref pull/3990/merge
---- End output of git fetch origin pull/3990/merge ----
Ran git fetch origin pull/3990/merge returned 128
```

Oops

**Comment by christophermaier** [comment]
Once more, with feeling: 

@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
Sorry; I had a problem deploying this change to acceptance. The error was:

```ruby
Expected process to exit with [0], but received '128'
---- Begin output of git fetch origin pull/3990/merge ----
STDOUT: 
STDERR: Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
fatal: Couldn't find remote ref pull/3990/merge
---- End output of git fetch origin pull/3990/merge ----
Ran git fetch origin pull/3990/merge returned 128
```

Oops

**Pull request merged**
