### PR TITLE
Update builder-web readme for production

### PR DESCRIPTION
**Pull request by smith**
gif-keyboard-3135629635906410220

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by reset** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 317448a has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 317448a with merge f1e907c...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/138521582)

**Pull request merged**
