### PR TITLE
Release 0.10.2.

### PR DESCRIPTION
**Pull request by fnichol**
gif-keyboard-6269728485302717692

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
gif-keyboard-14534286600092507396

**Comment by adamhjk** [comment]
gif-keyboard-370084522762789490

**Comment by jtimberman** [comment]
gif-keyboard-3494451331950561715

**Comment by fnichol** [comment]
Quorum achieved!

gif-keyboard-5625514317694803362

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/164177422).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/164177422).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
