### PR TITLE
Fixes bad studio.sh behavior in folders with spaces

### LINKED ISSUE #3881: Cannot build package if current folder path contains a space
This is using `hab pkg build .` in a folder whose name contains a space. This is the error message:

```
   hab-studio: Destroying Studio at /hab/studios/home--rsertelon--sources--con tracts (unknown)
/hab/pkgs/core/hab-studio/0.37.0/20171019054327/bin/hab-studio: 1066: [: /hab/studios/home--rsertelon--sources--con: unexpected operator
BusyBox v1.24.2 (2017-05-13 21:55:09 UTC) multi-call binary.

Usage: readlink [-fnv] FILE

Display the value of a symlink

	-f	Canonicalize by following all symlinks
	-n	Don't add newline
	-v	Verbose
```

We see that the error shows the truncated name at the space location.

### PR DESCRIPTION
**Pull request by rsertelon**
Should close #3881

Signed-off-by: Romain Sertelon <romain@sertelon.fr>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by rsertelon** [comment]
A little note to say that I couldn't test it with on my computer because I couldn't make hab pickup my dev packages (`rsertelon/hab-studio` for instance), it would only try to use `core/hab-studio`.

**Comment by reset** [comment]
tenor-250681738

**Comment by fnichol** [comment]
Yeah, a nice solution!

tenor-224268665

**Pull request merged**
