### PR TITLE
Add newlines to pkg ident strings in job promote interactive mode

### LINKED ISSUE #4330: `hab bldr job promote --interactive` presents packages on one line
Running `EDITOR=nano hab bldr job promote BUILD_ID stable --interactive` using hab 0.50.3 on OSX opens an editor with content similar to:

```
# This is the list of package identifiers that will be processed.
# You may edit this file and remove any packages that you do
# not want to apply to the specified channel.
core/ant/1.9.7/20171213095951core/jdk8/8u151/20171213095056core/maven/3.3.9/20171213095954
```

Note the lack of line break.  If you simply save and exit, the malformed content leads to nothing being promoted:

```
∅ No matching packages found for promotion
```

Manually inserting line breaks in the presented package list works as expected.

### PR DESCRIPTION
**Pull request by smacfarlane**
Fixes #4330 

Signed-off-by: Scott Macfarlane <macfarlane.scott@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@smacfarlane Thanks!

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
Sorry; I had a problem testing this pull request. The error was:

```ruby
Expected process to exit with [0], but received '128'
---- Begin output of git reset --hard ae14c6cf5a2dd1dca82e56e0ef40c158171138af ----
STDOUT: 
STDERR: fatal: Could not parse object 'ae14c6cf5a2dd1dca82e56e0ef40c158171138af'.
---- End output of git reset --hard ae14c6cf5a2dd1dca82e56e0ef40c158171138af ----
Ran git reset --hard ae14c6cf5a2dd1dca82e56e0ef40c158171138af returned 128
```

Oops

**Comment by christophermaier** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/327279512).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/327279512).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
