### PR TITLE
Revert "Make docker studio behave like chroot studio"

### PR DESCRIPTION
**Pull request by elliott-davis**
Reverts habitat-sh/habitat#5430

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by elliott-davis** [comment]
@baumanj yes

**Comment by christophermaier** [comment]
@elliott-davis Get that DCO line in there, man!

**Comment by christophermaier** [comment]
DCO bot is cranky, even though the required sign-off line is present... merging.

**Pull request merged**
