### PR TITLE
Homepage: Add "Watch the Video" CTA button to homepage sub-hero

### PR DESCRIPTION
**Pull request by magwalk**
CTA directs users to the webcast announcement recording located
at /about/announcement.

Signed-off-by: Maggie Walker <magwalk@gmail.com>

screen shot 2016-06-15 at 12 17 07 pm

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @ryankeairns, @davidwrede, @smith, @cwebberOps and @nathenharvey to be potential reviewers

**Comment by ryankeairns** [comment]
This looks good!

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 6274fa1 has been approved by `ryankeairns`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 6274fa1 with merge d702b59...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26900344)

**Pull request merged**
