### PR TITLE
Updates to the Habitat builder cli commands

### PR DESCRIPTION
**Pull request by chefsalim**
This includes bug fixes and changes to make the build commands functioning
with the new net stack, as well as some cleanup and simplification. In
addition, the job commands have been migrated to the bldr sub-command.

Signed-off-by: Salim Alam <salam@chef.io>

tenor-135610402

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
Is there a reason that these subcommands aren't in `hab bldr job`, like `hab bldr job start`? Seeing `hab bldr start` doesn't communicate as clearly on which noun the verb is operating. It also buys us room to have other nouns under the `hab bldr` namespace.

**Comment by raskchanky** [comment]
@chefsalim omg that gif is A+++.

**Comment by chefsalim** [comment]
@fnichol those are good points, I'll look at moving the job commands down one more level.

**Comment by fnichol** [comment]
@chefsalim thanks, that should help my brain!

**Comment by chefsalim** [comment]
ok @fnichol your requested change is done!

**Comment by chefsalim** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/281028322).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/281028322).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
