### PR TITLE
[ci] Properly detect version of rustfmt for install logic.

### PR DESCRIPTION
**Pull request by fnichol**
gif-keyboard-11842040260886519815

Get it?? Right??

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/165404816).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/165404816).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by reset** [comment]
@fnichol this should be a nice improvement!

**Comment by fnichol** [comment]
Damn, I hope so--yet another place where version detection logic changed. I'm testing this against #1329 so we'll know shortly

**Comment by fnichol** [comment]
Worked! That's like 4 mins per run back once we've upgraded a version of rustfmt.

**Pull request merged**
