### PR TITLE
Fixed some typos in the internals docs.

### PR DESCRIPTION
**Pull request by juliandunn**
Also, mentioned that the rumor list is basically a CmRDT, for distsys nerds that care about such things.

Signed-off-by: Julian C. Dunn <jdunn@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by smith** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit d593a95 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit d593a95 with merge e515ce9...

**Comment by juliandunn** [comment]
@thesentinels retry

**Comment by thesentinels** [comment]
:hourglass: Testing commit d593a95 with merge 4c712d3...

**Comment by juliandunn** [comment]
@thesentinels retry

**Comment by thesentinels** [comment]
:hourglass: Testing commit d593a95 with merge bd78f4d...

**Comment by adamhjk** [comment]
@thesentinels retry

**Comment by smith** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- There's another pull request that is currently being tested, blocking this pull request: #869

**Comment by thesentinels** [comment]
:pushpin: Commit d593a95 has been approved by `smith`

**Comment by adamhjk** [comment]
@thesentinels retry

**Comment by thesentinels** [comment]
:hourglass: Testing commit d593a95 with merge a9ba82b...

**Comment by smith** [comment]
Manually merging.

**Pull request merged**
