### PR TITLE
Update Linux instructions to reflect tar package

### LINKED ISSUE #4557: website suggests I unzip a tarball
https://www.habitat.sh/docs/install-habitat/

For Linux the website says:
> Once you have downloaded the CLI, unzip it onto your machine. Unzipping to /usr/local/bin should place the hab command on your PATH.

However this package is a tarball, not a zip. I'd suggest changing that to something like:
> Once you have downloaded the package, extract the `hab binary with `tar` to /usr/local/bin or add it's location to your PATH.

FWIW, this does the job: `tar -xvzf hab.tgz -C /usr/local/bin --strip-components 1`

### PR DESCRIPTION
**Pull request by tashimi**
Closes #4557 

Signed-off-by: Tasha Drew <tasha.drew@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by tashimi** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/339279451).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/339279451).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
