### PR TITLE
Add plan for jruby1.x

### PR DESCRIPTION
**Pull request by elliott-davis**
* Update plan for jruby 9 to correctly depend on jdk8 and server-jre

Signed-off-by: Elliott Davis <edavis@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by smith** [comment]
Works!

@thesentinels r+

gif-keyboard-16984659366986988388

**Comment by smith** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 42c037b has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 42c037b with merge 42c037b...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/140570202)

**Comment by smith** [comment]
Built and uploaded to depot: https://app.habitat.sh/#/pkgs/core/jruby1/1.7.25/20160627155858

**Pull request merged**
