### PR TITLE
Rename `pkg_binary_dirs` to `pkg_bin_dirs` in docs

### PR DESCRIPTION
**Pull request by smith**
gif-keyboard-17855743432231949317

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @cwebberOps, @davidwrede, @kevindickerson and @juliandunn to be potential reviewers

**Comment by metadave** [comment]
gif-keyboard-15568112774244493447


@thesentinels r+

**Comment by metadave** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 0d719b3 has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 0d719b3 with merge 0d719b3...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/141088935)

**Pull request merged**
