### PR TITLE
Running Rails applications with three different database configurations

### PR DESCRIPTION
**Pull request by nellshamrell**
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by nellshamrell** [comment]
This is now ready for review.

**Comment by ShalokShalom** [comment]
This is super awesome! Easy to read and comprehensive in the same breath, well done Nell :+1: 

We might see a follow up post about the migration from one instance to another? :wink:

**Comment by reset** [comment]
tenor-253754340

**Pull request merged**
