### PR TITLE
Rk/new website theme

### PR DESCRIPTION
**Pull request by ryankeairns**
This updates the navigation, background, and footer to the new darker theme and IA on the www side of the house. For now, I've pointed a few footer links at existing pages/content until the new pages are added... and left out the /explore page in the top nav.

screenshot 2017-05-01 16 53 01
screenshot 2017-05-01 16 53 11

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
Hey, @cnunciato - you don't have permission to issue `approve` on this pull request.

Nope

**Comment by tashimi** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
Hey, @tashimi - you don't have permission to issue `approve` on this pull request.

Nope

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/229213244).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/229213244).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
