### PR TITLE
Remove gdb install step from ubuntu_latest script

### PR DESCRIPTION
**Pull request by cnunciato**
Also updates the doc. Verified on Ubuntu 16.04 and 16.10 VMs.

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
Why remove this?

**Comment by cnunciato** [comment]
There was some discussion in #2164 about this (I was running into the same issue that prompted that change), and it looks like at least on 16.04 and 16.10, it doesn't seem to be necessary, so I figured it might be good to consider removing it. (I haven't tested on 17.04, though.) I could totally be missing the point of it, though. :)

**Comment by raskchanky** [comment]
Ah, I wasn't aware of the context there.  Maybe this is the right move?  I don't think I've hit that error before myself.

**Comment by cnunciato** [comment]
I think I probably missed the point, here -- I was assuming the items in this script were *necessary* libraries, so when I noticed this one wasn't necessary, I figured I might as well remove it. I failed to consider that gdb might actually provide something useful to people other than myself. ;) 

So maybe the thing to do is figure out how to install the right version. @rhass @nellshamrell does that sound right?

**Comment by fnichol** [comment]
Nice! Well, that version of gdb wasn't strictly required but is, in fact an awesome way to debug Rust code (you need version 7.12 or higher). At the time I updated those docs, the latest Ubuntu didn't have that exact version so I hacked it in with the intention to drop it as soon as a newer Ubuntu release shipped with that gdb version.

As a project, our suggestion to developers is to use the latest version of Ubuntu anyway if possible (assuming that's your Linux distribution) so this works for me!

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/227656209).

**Comment by cnunciato** [comment]
Nice! Thanks for the closer look, @raskchanky and @fnichol.

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/227656209).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
