### PR TITLE
Update Elixir plan for 1.3.0 release

### PR DESCRIPTION
**Pull request by shanesveller**
Had one segfault on an earlier local build, but all later ones succeeded without any additional code changes. :unamused:

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by metadave** [comment]
looks good, thanks!

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 19db4fd has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 19db4fd with merge 3f7afa5...

**Comment by metadave** [comment]
uploaded to the depot: https://app.habitat.sh/#/pkgs/core/elixir/1.3.0/20160622164141

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139548877)

**Pull request merged**
