### PR TITLE
Auto-scroll when viewing a running build

### LINKED ISSUE #2537: [builder-web] Auto-scroll when viewing a running build
The build-log component should support pinning vertical scroll position to the end of a running log (so users don't have to scroll manually to keep up with it), jumping to top, and jumping to bottom.

### PR DESCRIPTION
**Pull request by cnunciato**
This adds a couple of buttons to the build-log view that let you jump to the beginning and end of a build log, and when a log is running, pin to the end of it.

Closes #2537.

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
Here's what it looks like:

**Comment by raskchanky** [comment]
So good

tenor-11679074

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/240572712).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/240572712).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/240572712).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/240572712).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
