### PR TITLE
rename nginx-builder-api and promote to components

### PR DESCRIPTION
**Pull request by reset**
`nginx-builder-api` renamed to `builder-api-proxy` which is now more accurately named after it's purpose instead of implementation

gif-keyboard-159526509764636891

Signed-off-by: Jamie Winsor <jamie@vialstudios.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @jtimberman and @adamhjk to be potential reviewers

**Comment by reset** [comment]
Coincidentally, both of the bot assigned reviewers and I had already spoken and agreed upon this the other day :smile: /cc @jtimberman @adamhjk 

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 9cd3d1f has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 9cd3d1f with merge e2059d7...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/141709656)

**Pull request merged**
