### PR TITLE
[bintray-publish] Add documentation for publishing to Bintray.

### PR DESCRIPTION
**Pull request by fnichol**
Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by fnichol** [comment]
A couple of days late, but finally some words for @reset 

gif-keyboard-9571552082391466457

**Comment by adamhjk** [comment]
gif-keyboard-1904049185267588807

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 5c44563 has been approved by `adamhjk`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 5c44563 with merge 2524198...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139911899)

**Pull request merged**
