### PR TITLE
Added more clear instructions on setup

### PR DESCRIPTION
**Pull request by mhedgpeth**
I had a hard time knowing how to get habitat working on a mac, so I added that information to this page.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mhedgpeth** [comment]
Well darn. I forgot the DCO part. Is there a way to change that after the fact?

**Comment by mwrock** [comment]
just need DCO and we will push it.

**Comment by smith** [comment]
> Is there a way to change that after the fact?

@mhedgpeth `git commit --amend --signoff && git push --force`

**Pull request closed without merging**
