### PR TITLE
Add builder-datastore plan to components

### PR DESCRIPTION
**Pull request by reset**
We need to slightly modify the postgresql plan to better suit our
needs, so we create a wrapper package. It is still necessary to
obtain the superuser password for the database and configure each
service group with it so they can create their database.

tenor-38911038

### CODE REVIEW

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/230217193).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/230217193).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
