### PR TITLE
Adds post-stop hook

### LINKED ISSUE #2485: 'Unload' hook
## Preamble

Introduce an "unload" hook for performing tasks _each_ time that `hab stop` is called for a service.

## Example use case

- The `core/drupal` plan background loads `core/nginx` in the init hook. 
- When the user runs `hab stop core/drupal` the core/nginx instance is left running.
- An unload hook would allow the plan writer to additionally stop the nginx which is now cruft.

### PR DESCRIPTION
**Pull request by rsertelon**
> This should fix #2485

I chose to name the hook `post-stop` instead of `unload` because it felt better, if not, I can rename it.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@rsertelon I think that `post-run` is a fine name. I'm sure we could debate this and we may, but the implementation would stay the same so we should go ahead and merge this in as is and worry about it later ;)

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/312725917).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/312725917).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
