### PR TITLE
Integrate EventSrv into the supervisor.

### PR DESCRIPTION
**Pull request by raskchanky**
This commit splits EventSrvClient out into its own crate and integrates
it into the supervisor. The supervisor maintains a thread with the
EventSrvClient and sends changes to itself to said client every time the
census changes. The payload for events is a byte array of
CensusEntry protobufs.

There's still a bit of cleanup and refactoring to do here, but I wanted to get the PR up anyway to get eyes on it now.

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
gif-keyboard-36157540246008319

**Comment by mwrock** [comment]
This is great and I think its totally adequate based on the fact that, as far as I know, its the first and only event server client implementation. If/when we add other services to send event messages, it might be worth abstracting some of the code currently in the supervisor that sets up the listening thread and sends the messages.

It would be cool if a consuming service could simply call `event_client.start()` and stash the client in a struct field. Then as it collects census entries, it jusy calls `event_client.send(entry)`. If you abstract the `as_protobuf` into a trait. This `send` method could accept any kind of event protobuf.

Those were just some thoughts I had while reading this over but this looks totally good as a first client.

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/223988694).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/223988694).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
