### PR TITLE
Two missing oxford commas

### PR DESCRIPTION
**Pull request by nathenharvey**
Signed-off-by: Nathen Harvey <nharvey@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @magwalk, @ryankeairns, @davidwrede, @smith and @cwebberOps to be potential reviewers

**Comment by metadave** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit c9cc9dc has been approved by `metadave`

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26817402)

**Pull request merged**
