### PR TITLE
[hab-plan-build] Normalize file checksums before comparison

### LINKED ISSUE #5427: Hab studio download_file checksum comparison should be case-insensitive
- hab-studio version 0.57 on Mac OS X

This is a fairly easy one to demonstrate:

From `plan.sh`:

```
pkg_shasum="7C4C34E567959677C1EF3A450992AFCE43FB4B8C4BD5B98C5E9D48AFD9CA2223"

...

  if [ ! -f $HAB_CACHE_SRC_PATH/$pkg_filename ]; then
    download_file "${pkg_source}" "${HAB_CACHE_SRC_PATH}/${pkg_filename}"
  fi
```

And then, when running `hab studio run build`:

```
   itm: Downloaded '/hab/cache/src/itm6.3.0.tar.gz'
   itm: Verifying itm6.3.0.tar.gz
   itm: WARN Checksum invalid for itm6.3.0.tar.gz:
   itm: WARN    Expected: 7C4C34E567959677C1EF3A450992AFCE43FB4B8C4BD5B98C5E9D48AFD9CA2223
   itm: WARN    Computed: 7c4c34e567959677c1ef3a450992afce43fb4b8c4bd5b98c5e9d48afd9ca2223
   itm: Build time: 1m13s
   itm: Exiting on error
```

Notice that the checksum matches. The only distinction is the case insensitivity. This should be an easy fix; `ucase` or `lcase` both expected and found checksums before comparison.

### PR DESCRIPTION
**Pull request by stevendanna**
This changes our checksum comparison to be case-insensitive, allowing
user to use hexadecimal representations of the checksum that use
uppercase letters.

Fixes #5427

Signed-off-by: Steven Danna <steve@chef.io>

### CODE REVIEW

**Comment by stevendanna** [comment]
Was going through some older tickets and saw this issue.  This isn't a priority for me personally, but it seemed like an easy enough thing to fix.  If we decide we'd rather not, let's also close the related ticket.

**Comment by christophermaier** [comment]
@mwrock The Windows version of `hab-plan-build` needs this too, correct?

**Comment by christophermaier** [comment]
Also, thanks for this @stevendanna !

**Comment by mwrock** [comment]
Nope @christophermaier . Powershell string comparisons are case insensitive.

**Comment by christophermaier** [comment]
@mwrock That's surprising. Good for us, but surprising. :man_shrugging: 

Thanks!

**Pull request merged**
