### PR TITLE
Native Package enhancements to enable package bootstrapping

### PR DESCRIPTION
**Pull request by atrniv**
This PR adds additional features to the native packages capability that are required to bootstrap a set of packages on a new architecture.

- It adds the ability to specify `pkg_deps` and `pkg_build_deps` for native packages.
- It adds a new type of chroot studio `bootstrap`. The `bootstrap` studio type makes use of various `build-tools` native packages from the [bootstrap plans repo](https://github.com/habitat-sh/bootstrap-plans) to create a minimal studio cleanroom environment that can be used to make isolated builds.
- Fixes a bug that caused failed native package builds to make the hab cli command die with a success exit code (0). Any failure in a native package build will now return a non-zero exit code.

### CODE REVIEW

**Comment by mwrock** [comment]
Do we care if a native package has a dep on a standard package or if a standard package has a dep on a native package? I would guess we would care more about the later. If a standard has a dep on a native package then the standard package may not be as portable as one might expect.

**Comment by mwrock** [comment]
I think we should add some end to end tests for native packages.

**Comment by atrniv** [comment]
> Do we care if a native package has a dep on a standard package or if a standard package has a dep on a native package? I would guess we would care more about the later. If a standard has a dep on a native package then the standard package may not be as portable as one might expect.

@mwrock , there are valid use cases for all combinations of dependencies, I've added a comment to the original proposal elaborating on this: https://github.com/habitat-sh/habitat/issues/8501#issuecomment-1286772725

**Comment by atrniv** [comment]
> I think we should add some end to end tests for native packages.

Yes, perhaps a E2E tests that a native package build succeeds in an environment with the necessary tools and fails otherwise might make sens.

**Review by mwrock — APPROVED** [review]

**Pull request merged**
