### PR TITLE
New Node.js web app guide + content refactoring

### PR DESCRIPTION
**Pull request by davidwrede**
Added a Node.js web app guide using the Node.js scaffolding. 

There is a main splash page that allow you to select which guide you want to read, but after that point, the flow and UI is very similar to how [Build a Sample App](https://www.habitat.sh/tutorials/sample-app/) allows you to switch between related tutorials. 

In addition, I refactored out a lot of the common content so that additional web guides can be written and built faster.

Signed-off-by: David Wrede <dwrede@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by davidwrede** [comment]
cc/@nellshamrell

**Comment by nellshamrell** [comment]
A few notes:

At "The basic structure of a plan is shown below:" you show the contents of the habitat directory without specifying that it is the habitat directory in the root directory of the nodejs application.  It would be clearer to say "tee /habitat" rather than just "tee"

"Additionally, only exact versions of Node.js are currently supported, so version constraint expressions such as ">= 0.10.3" will not work." is out of date - expressions including "0.10.3", "=0.10.3", "v0.10.3", ">0.10.3", ">=0.10.3", ">=0.10.3", ">0.10.3" now work :)

"Additionally, only exact versions of Node.js are currently supported, so version constraint expressions or wildcard versions will not work." is also out of date.  See ^

I get a "File Not Found" when clicking the "Next: Add Configuration" button here http://localhost:4567/tutorials/build-your-own/node/define-processes/

I also get a "File Not Found" error when clicking the "Next: Connect to Nginx" button here http://localhost:4567/tutorials/build-your-own/node/connect-database/

Other than what I've noted above, this looks good!  I learned some things I didn't know through reviewing this, great work @davidwrede!

**Comment by nellshamrell** [comment]
One more thing - it's not clear where the user should get the NodeJS app to package with Habitat here http://localhost:4567/tutorials/build-your-own/node/create-plan/ - would be good to have a link to the github repo, show cloning it, etc.

**Comment by davidwrede** [comment]
@nellshamrell Regarding your last comment, this is more of guide for those folks who already have a Node.js app and they want to learn more about the Node.js scaffolding and how to use it when packaging up their app.

**Comment by nellshamrell** [comment]
One more thing - pre-build and post-build steps currently do not work with the node scaffolding (though that is coming soon!) - could that be added to the docs somewhere?

**Comment by davidwrede** [comment]
Feedback has been incorporated. Ready for other reviews or merge.

**Comment by nellshamrell** [comment]
:shipit:

**Comment by nellshamrell** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/285198397).

**Comment by thesentinels** [comment]
:broken_heart: Travis CI reports [this PR failed to pass the test suite](https://travis-ci.org/habitat-sh/habitat/builds/285198397).

The next step is to examine the [job](https://travis-ci.org/habitat-sh/habitat/builds/285198397) and figure out why. If it is transient, you can try re-triggering the Travis CI Job - if it passes, this PR will be automatically merged. If it is not transient, you should fix the issue and update this pull request, and issue `approve` again. If you believe it will never pass, and you are feeling :godmode:, you can issue a `force` to merge this PR anyway.

**Pull request merged**
