### PR TITLE
[hab] Refactor `install.sh` for Habitat 'hab' program.

### PR DESCRIPTION
**Pull request by fnichol**
* Uses a consistent, minimal POSIX shell style which passes a shellcheck
  execution of `shellcheck -e SC2039 components/hab/install.sh`
* Executes with minimal shell implementations such as Busybox's `sh`
  (used in Alpine linux, for example), Ubuntu's `dash`, vanilla `sh`,
  as well as `bash`
* Uses a command set consistent with a base macOS installation for Mac
  systems and a Busybox userland for Linux systems (in addition to an
  SSL-enabled `wget` or `curl`)
* Ensures that each function has explicit required command checks via the
  `need_cmd()` function (an idea borrowed from Rust's rustup shell wrapper)
* Renders minimal structured output via `info()` and `exit_with()`
  functions (currently no color support)
* Randomizes temporary work directory via `mktemp` while still preferring
  a subdirectory of `/var/tmp` for Red Hat systems that have nosuid set
  on `/tmp` file system mounts
* Only strictly supports the targets that Habitat currently supports,
  namely x86_64-linux and x86_64-darwin (unix-based) which reduces
  additional checks and fallbacks that are never exercised but need to be
  reviewed and tested
* Fixes several unset variable issues when `set -u` was being truely
  honored (issues were not present in all shells)
* Increases the internal consistency of UI output with the rest of the
  Habitat ecosystem
* Modularizes work into smaller functions with a `main()` entrypoint
  (hey, that's a bit like a Rust program)
* Inspired from Chef's mixlib-install [function helpers][mixlib], Rust's
  rustup [installer wrapper][rustup], the [Studio codebase][studio], and
  the [launch-era][launch] simplified version
* Removes progress bars for `curl` and `wget` file downloads
* Preserves channel support via `-c` flag
* Preserves specific version support via `-v` flag
* Add help/usage via `-h` flag

Tested against:

* macOS 10.9 and 10.10
* Alpine Linux (via `alpine:3.4` Docker image)
* Ubuntu Linux (via `ubuntu:16.04` Docker image)
* CentOS Linux (via `centos:7` Docker image)

[mixlib]:
https://github.com/chef/mixlib-install/blob/master/support/install_command.sh
[rustup]:
https://github.com/rust-lang-nursery/rustup.rs/blob/master/rustup-init.sh
[studio]:
https://github.com/habitat-sh/habitat/blob/master/components/studio/bin/hab-studio.sh
[launch]:
https://github.com/habitat-sh/habitat/blob/ae943e0cb7ec3c882105065f7b1eaa1994a4350e/components/hab/install.sh

Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
Works wonderfully on macOS at least. Maybe we should add a section to the top of the README with curl bash instructions so people can get started quickly and for reference on how to easily get this on a node with a provisioner?

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/202385531).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/202385531).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
