### PR TITLE
General quality of life improvements to Supervisor

### LINKED ISSUE #2065: Supervisor exits and fails to clean-up running services
Steps to reproduce:

1.  Start the supervisor (`sudo hab sup run`)
1.  Load a service (`sudo hab sup load learn/mongodb`)
1.  Load another service, one that requires a bind, but don't specify the bind (`sudo hab sup load learn/national-parks`)

The supervisor raises an error and exits at this point.

1.  Unload both services (`sudo hab sup unload learn/national-parks ; sudo hab sup unload learn/mongodb`)
1.  Restart the supervisor (`sudo hab sup run`)
1.  Reload MongoDB (`sudo hab sup load mongodb`)

MongoDB fails.  

Cancel the supervisor, check running habitat processes and see that mongod is still running.  

Was it not shutdown cleanly when the supervisor exited?

Killing the mongod process and restarting everything works.

A screen cast of the issue can be found here - https://youtu.be/64Ql6hDWhxY

### PR DESCRIPTION
**Pull request by reset**
This change introduces some general quality of life improvements to the supervisor after our multi-service changes

* Transient services will no longer produce an IO error when stopping
* Moved some debug logging from EventSrvClient to debug logger
* Fix supervisor crash when a single service fails to load (fixes #2065, #2061, #2110)
* On service load failure we will now remove the offending service spec if it represents a transient service

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by bodymindarts** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/225888660).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/225888660).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
