### PR TITLE
[plan-build] Make `pkg_source` optional so local builds are first class.

### PR DESCRIPTION
**Pull request by fnichol**
*Note* This is a non-breaking change, meaning that all existing Plans
should continue to operate as before.

This change drops the requirement of including the `pkg_source` variable
in a Plan and alters the default behavior of the corresponding build
phases (namely `do_download()`, `do_verify()`, and `do_unpack()`) to do
the right thing.

Rationale
---------

The hypothesis here is that the vast majority of Plans will exist
alongside application source code, much like adding a project `Gemfile`
for Ruby dependencies or a `.travis.yml` for CI instructions. In that
sense, from the point of view of the Plan file, I am building **my**
application, not someone else's.

Previous to this change the build system (and by extension the defaults
in Plan files) optimized for building **other** software (not **my**
software) such as third party services like Redis, MySQL, or
intermediate software libraries like OpenSSL, zlib, etc. In these
cases, the `plan.sh` was not co-located with the source code meaning
that some source artifact needed to be downloaded, verified, and
extracted. In the case where the `plan.sh` is hosted with the source
code, there is nothing to download when building--the source tree is
already mounted into the Studio under `/src` and ready to be used.

In a CI or build environment such as Travis, Jenkins, or Builder (the
Habitat distributed build service), an SCM clone will have already
occurred before a package build will be invoked via `hab pkg build`. If a
clean checkout is provided, then there should be no additional work that
needs to happen inside the Studio instance with the help of the build
program. This means we can operate directly on the mounted-in directory
when performing a build which was part of the original Studio design.

Net-New Plan Author Variables
-----------------------------

As a part of implementing this feature, 2 new user-facing variables are
introduced which a Plan author *might* be inclined to use when writing a
Plan. The internals of the build program have been updated to use these
directly in an attempt to make more clear what is happening and where.
The variables are:

* `$SRC_PATH`: This is the directory that contains the source code to
  be built. During each relevant build phase (namely `do_prepare()`,
  `do_build()`, and `do_install()`), the current working directory will
  be `$SRC_PATH`. For local applications this will be the same directory
  which contains either `./plan.sh` or `./habitat/plan.sh`. For external
  source-downloaded software, this will be in the cache path, as
  described next.
* `$CACHE_PATH`: This is a directory which will be freshly created each
  time the build program is executed and lives under the
  `/hab/cache/src` directory. Its value is derived from the
  `$pkg_dirname` variable and is exactly equivalent to
  `$HAB_CACHE_SRC_PATH/$pkg_dirname`. For externally source-downloaded
  software, this is also the `$SRC_ROOT` where all the source code is
  extracted to, just as in previous behavior. For local applications,
  this is a helpful directory which the Plan author can be assured
  will be cleaned out between build runs and can be used to place
  build-intermediaries, artifacts, caches, indexes, etc.

A Happy Upgrade Path For Existing Local Plans
---------------------------------------------

First off, no existing Plans should be affected so there is nothing
imminent to do. However...

If your Plan is hosted with your application, then you can remove the
following items (which were workarounds):

* Remove the faked-out `pkg_source` variable
* Remove the faked-out `do_download()` implementation which calls
  `return 0`
* Remove the faked-out `do_verify()` implementation which calls
  `return 0`
* Remove the faked-out `do_unpack()` implementation which calls
  `return 0`

This should mean that a `plan.sh` which looks like this:

```sh
pkg_origin=myorigin
pkg_name=mytutorialapp
pkg_version=0.2.0
pkg_maintainer="Me <me@example.com>"
pkg_license=()
pkg_upstream_url=https://github.com/habitat-sh/habitat-example-plans
pkg_source=nosuchfile.tar.gz
pkg_deps=(core/node)
pkg_exports=( [port]=listening_port )
pkg_exposes=(port)

do_download() {
  return 0
}

do_verify() {
  return 0
}

do_unpack() {
  return 0
}

do_build() {
  # implementation details...
}

do_install() {
  # implementation details...
}
```

can be reduced to this:

```sh
pkg_origin=myorigin
pkg_name=mytutorialapp
pkg_version=0.2.0
pkg_maintainer="Me <me@example.com>"
pkg_license=()
pkg_upstream_url=https://github.com/habitat-sh/habitat-example-plans
pkg_deps=(core/node)
pkg_exports=( [port]=listening_port )
pkg_exposes=(port)

do_build() {
  # implementation details...
}

do_install() {
  # implementation details...
}
```

Who doesn't enjoy deleting code, right?

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
gif-keyboard-11805761765640575770

**Comment by fnichol** [comment]
There are a number of either related or relevant issues and PRs that involve `$pkg_source`:

Closes #2064 
Closes #1972
References #1495
References #2066

**Comment by smith** [comment]
Can we update the docs (https://github.com/habitat-sh/habitat/blob/master/www/source/docs/reference/plan-syntax.html.md) and init template (https://github.com/habitat-sh/habitat/blob/master/components/hab/static/template_plan.sh) please?

**Comment by reset** [comment]
@thesentinels approve

This is very clearly the right thing to do and it was a super elegant change. Just delete some stuff and reword the docs ;)

We need to make sure we follow up on the tutorials and other docs

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/220724034).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/220724034).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/220724034).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/220724034).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by fnichol** [comment]
@smith Yeah, I was starting to update these, then realized that they would be deployed out. At a minimum I should get a PR that we can merge closer to release time and make sure we've covered everything off. There are tutorial changes we can make too to simplify the `plan.sh` and explanations even more.

**Comment by bdangit** [comment]
❤️ this.  I'm glad this is being worked at this level.  It will make scaffolding plans have simpler logic to point its just the mechanics of building *x* language instead of understanding habitat layout.

**Pull request merged**
