### PR TITLE
k8s exporter: Add bind options & some cleanups

### PR DESCRIPTION
**Pull request by zeenix**
This is on top of my existing PR for docker image export:

https://github.com/habitat-sh/habitat/pull/4041

I think this: https://github.com/habitat-sh/habitat/commit/0ecc51aa5f57379fa5baf0fd99a24bc979931811 should provide a very good demo/justification for https://github.com/habitat-sh/habitat/issues/4052 .

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by zeenix** [comment]
@christophermaier I know you said that it's best no to submit PRs that depend on other PRs but this one was actually created by accident. It was supposed to be only a quick internal review at kinvolk before I submit upstream. :( I'd be more than happy to push the commits from here to https://github.com/habitat-sh/habitat/pull/4041 and close this one, if you prefer that?

**Comment by christophermaier** [comment]
@zeenix yeah, feel free to close this and add the commits to #4041

**Comment by zeenix** [comment]
@christophermaier roger, wilco! :)

**Pull request closed without merging**
