### PR TITLE
Fixes annoying warn during hab-butterfly compilation

### PR DESCRIPTION
**Pull request by rsertelon**

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by rsertelon** [comment]
This is the warn that the compiler informs me about ;)

```
   Compiling hab-butterfly v0.0.0 (file:///home/rsertelon/sources/habitat/components/hab-butterfly)
warning: unused import: `std::str`
  --> src/command/config.rs:16:9
   |
16 |     use std::str;
   |         ^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 16.7 secs
```

**Comment by raskchanky** [comment]
@rsertelon Looks good!  Appveyor failed, but I think the failure was transient.  I'll merge this when it goes green.

**Comment by raskchanky** [comment]
tenor-176111516

**Pull request merged**
