### PR TITLE
Fully specified URL for open graph image

### PR DESCRIPTION
**Pull request by TrevorBramble**
(For some reason I thought a root-relative path would be sufficient.)

Signed-off-by: Trevor Bramble <tbramble@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @cwebberOps, @smith, @ryankeairns and @magwalk to be potential reviewers

**Comment by cwebberOps** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 5ea168b has been approved by `cwebberOps`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 5ea168b with merge a2f5241...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26909858)

**Pull request merged**
