### PR TITLE
Add `origin key list` subcommand to cli

### LINKED ISSUE #2559: [alias] use easy alias to show local keys
Currently, ls /hab/cache/keys is the way to go in order to show the local keys. 
`keys` as alias is doing very fine here. ^-^

### PR DESCRIPTION
**Pull request by asymmetric**
This subcommand provides an easy way for users to list the origin keys
installed on their system.

Closes #2559.

Signed-off-by: Lorenzo Manacorda <lorenzo@kinvolk.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
The surface area of this change is small enough that even if glob was deprecated and we needed to switch to globset, it'd be pretty easy to do.  I don't think it's a big deal.

**Comment by eeyun** [comment]
That was kind of my inclination as well @raskchanky. Related: this is a feature that I've seen a couple folks ask about which is dope!

**Comment by raskchanky** [comment]
@asymmetric Thanks for the contribution.  This looks great!

My first thought when running this locally was the output should only show the key name, instead of the absolute path to each key.  I'm curious if any of the other @habitat-sh/habitat-core-maintainers have thoughts on this.

**Comment by asymmetric** [comment]
@raskchanky thanks, that was one of the questions I had!

The other one is, should I make sure this only lists files, and not directories?

**Comment by raskchanky** [comment]
@asymmetric Yes, definitely only list files and not directories, since only files can be keys.

**Comment by rsertelon** [comment]
What is the status of this PR with regards to issue #1727 ?

**Comment by asymmetric** [comment]
@rsertelon haven't had much time to work on this lately, so feel free to pick it up if you happen to have it :)

**Comment by asymmetric** [comment]
The build fails on AppVeyor because it uses `for_each`, which was [stabilized in 1.21.0](https://blog.rust-lang.org/2017/10/12/Rust-1.21.html).

But looking at the logs, it seems AppVeyor also runs 1.21.0, so I'm not sure what's happening.

**Comment by mwrock** [comment]
The failing appveyor build is the habitat build of habitat which uses the hab rust package and that was 1.20 for windows. I just build 1.21 and pushed that to the depot's stable channel. I also kicked off a new build of this PR to see if that truly fixes this.

**Comment by rsertelon** [comment]
It would be nice to have @christophermaier input on this one I think. To me it seems a bit related to #4001 and he might have insights on this PR too :)

**Comment by christophermaier** [comment]
My only feedback would be that this PR encodes a little bit of information about what it means to be a key in a separate place from where the rest of the code does it (I'm guessing this is why @rsertelon pinged me, since that was some of my feedback on #4001 😄 ). It would be nice to have all the criteria for "what it is to be a key" in one place that we can just pull in anywhere.

**Comment by christophermaier** [comment]
Any movement on this lately?

**Comment by asymmetric** [comment]
@christophermaier not from me, sorry, I've been busy with other tasks :)

**Comment by christophermaier** [comment]
@asymmetric Yup 😄 Just taking a look through some older PRs to check up on them.

**Comment by elliott-davis** [comment]
This change would also pick up user keys, encryption keys, and potentailly symmetric keys. I'm going to close this since there hasn't been a lot of movement on it and the implementation would have to change quite a bit. Please feel free to re-open if you get some more time to hack on it

**Pull request closed without merging**
