### PR TITLE
[depot-client] Fetching packages now write to randomly named tmpfile.

### LINKED ISSUE #1681: Failure when trying to install the same thing multiple times
If many processes are trying to install one package all at once, an error can happen:

```
hab install core/hab-sup && rm -rf /hab/pkgs/core/hab-sup && hab install core/hab-sup & hab install core/hab
-sup & hab install core/hab-sup & hab install core/hab-sup & hab install core/hab-sup & hab install core/hab-sup & hab install core/hab-sup &
...
→ Using core/zlib/1.2.8/20161118033245
✗✗✗
✗✗✗ Couldn't read MetaFile: TARGET, not found
✗✗✗
✓ Installed core/hab-sup/0.16.0/20170119213934
★ Install of core/hab-sup/0.16.0/20170119213934 complete with 1 new packages installed.
✓ Installed core/hab-sup/0.16.0/20170119213934
★ Install of core/hab-sup/0.16.0/20170119213934 complete with 1 new packages installed.
...
```

Ran into this because we have a monolithic app where after install it has a bunch of systemd units that all run `hab start x`. Since systemd starts them all at the same time and hab-sup isn't there, when this error happens some services don't start, even though everything is fine after a restart.

### PR DESCRIPTION
**Pull request by fnichol**
This change resolves one particular concurrent downloading race when
installing packages from a Depot. For example, if multiple Supervisors
are started in a very short period of time or asynchronously such as
with Systemd, the previous implementation would create a hardcoded temp
file which was the destination file name with `.tmp` added onto the end.
So, if multiple `hab start core/redis` supervisors on one host were
started, then all might try and open a write handle to the same
`core-glibc-2.22-20160612063629-x86_64-linux.hart.tmp` file.

This fix writes to a randomly determined temporary file, such as
`core-glibc-2.22-20160612063629-x86_64-linux.hart.tmp-mL9ovfgI`. While
it is true that each Supervisor will download the same artifacts, they
won't open write file handles on the same temporary files. Future
feature work may add multi-service supervision or other multi-process
aware tricks to further reduce concurrent downloads of the same
artifacts but this should fix the immediate issue at hand.

Tested with:

```sh
cd components/hab
cargo build
alias hab='sudo ../../target/debug/hab'

 # Install all TDEP for the Supervisor so we focus on
 # only the core/hab-sup artifact
hab install core/hab-sup

 # Clean up package and artifact cache
sudo rm -rf /hab/pkgs/core/hab-sup /hab/cache/artifacts/core-hab-sup-*.hart

  # Install many `core/hab-sup` at the same time and
  # monitor for failures as seen in #1681
hab install core/hab-sup & \
  hab install core/hab-sup & \
  hab install core/hab-sup & \
  hab install core/hab-sup & \
  hab install core/hab-sup & \
  hab install core/hab-sup & \
  hab install core/hab-sup &
```

Closes #1681

Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
Looks good! We might want to make sure we're cleaning up any temp files we've generated before the program exits/panics, I'm not sure if this code was handling that before hand

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/197121453).

**Comment by fnichol** [comment]
@reset We weren't handling clean up at all and I was thinking the exact same. First time I would've liked a Go style `defer` or Java `finally { … }` but we could fix this up in a future PR.

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/197121453).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
