### PR TITLE
is_alive should check exit status of handle for STILL_ACTIVE

### PR DESCRIPTION
**Pull request by mwrock**
We (or 'I') incorrectly assumed that receiving a process from `OpenProcess` was confirmation that process was alive. The process may in fact be dead. This PR calls `GetExitCodeProcess` on the handle and checks to make sure its status is NOT `STILL_ACTIVE` (259).

This fixes lock file issues where a supervisor cannot restart because a `LOCK` file exists for a dead process.

Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

gif-keyboard-16025352785608118004

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/216485380).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/216485380).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/216485380).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
