### PR TITLE
Refactor accounts and sessions to be on separate shards

### PR DESCRIPTION
**Pull request by raskchanky**
Before this PR, accounts and sessions shared the same shard.  This made it impossible for us to reuse our stored sessions.

This PR changes that so that sessions are sharded independently of accounts.  Accounts want to be sharded on account name and sessions want to be sharded on their auth tokens.  The foreign key constraint was removed from the `account_sessions` table so it can exist independently of the accounts table.  When we retrieve sessions, instead of using a joined query to get the account information, we issue an RPC call.

Because the sharding for accounts wasn't changed, no data needs to be migrated.  Sessions are transient by nature, so no migration is necessary for their data.  The session retrieval query will also cleanup stale sessions (CTEs are amazing - thank you @christophermaier).

The upside of all this is that authenticated API calls are _much_ faster than they used to be, after the initial session creation.

tenor-235891601

Closes https://github.com/habitat-sh/habitat/issues/3216
Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
I definitely think we need to come up with a near term solution that "works". My reservation here is that we are diluting the data model by introducing multiple partitions to a single database. Maybe that's a nit but I want to just mention it here for discussion. Ultimately I think each database should align behind a single partitioning strategy. I think this points to a deeper issue that may be better addressed by altering schema or introducing an additional denormailized view layer either in the db or in a distributed cache. Clearly both are out of scope for our immediate release goals but I wonder what is the better short term fix: this approach or a non sharded approach discussed earlier.

I also feel like we have exhausted online channels of discussion and should talk in real time next week on this topic.

**Comment by reset** [comment]
While this is definitely an improvement on the first pass which we had there's still a bit better approach. Since we control the format of the session token we should embed the user's account-id and their external token in a base64 encoded string. On the gateway we decode this message and route directly to the server where the account lives since we have the account-id. This will save us the additional overhead of traversing shards during account creation/session validation

**Comment by raskchanky** [comment]
@mwrock I don't have enough experience with sharded databases to comment intelligently on whether it's a problem to have models with different sharding keys in the same database.  On the surface, it seems fine to me, especially when the previous approach was broken from the perspective of reusing our stored sessions.  But whether this will lead to problems down the road isn't something I have enough experience to judge.  I suppose we could just jam all accounts and sessions into the same table, but that would introduce new problems because looking up accounts based on a session key feels pretty convoluted and broken.

**Comment by raskchanky** [comment]
@reset Two thoughts on your comment:

1. Accounts are sharded on name, not id, so even if we had the id, that wouldn't help us look the account up.  I saw the `AccountGetId` message in the proto files but I'm not sure how that works.  If it tries to find the account on the shard given by the id, it's not going to find it unless the id and the name happen to hash to the same value.  The admin gateway seems to be the only thing using that message and I tried tinkering with the admin gateway on Friday but it wasn't working for me, so I couldn't evaluate further.

2. The fundamental problem that this PR is trying to solve is that when we go to look up a session, the auth token is the only piece of information we have.  We don't have the account id, or the account name or anything else.  I think I'm missing how your idea would fit into this.

**Comment by reset** [comment]
@raskchanky we route on `account-name` but it's relatively a static value (more on this at the bottom). Since it's _relatively static_ we use randomly deterministic routing to ensure that your account name always routes to the same server as your account-id. It works this way because the account is generated on the shard which `account-name` routes to. So, everytime you ask for an account by name it goes to the same shard that their account lives on.

Modifying our session token to be a base64 encoded item allows us to create an opaque piece of data which we pack additional information in. The format should probably be along the lines of this: `{account-id}:{session-token}`. We may even considering jamming their account name inside, really whatever our front-end client/gateway finds useful.

With this change you would have the account ID _inside_ the session token 😄 

## What we really should have keyed on

While it's true that you can change your account name on GitHub, they warn you that there may be [unintended side effects](https://help.github.com/articles/what-happens-when-i-change-my-username/). This made it good enough for the time but it would be better if we had keyed on `extern-id` since that *never* changes. I chose to key on `account-name` early on because I hadn't built the ability for one back-end server to message another through RouteSrv.

My comments in an issue last week and the conversation we had on Friday about fixing/improving sharding includes this. Basically I need to go through every protocol message and make sure it's routing the way it's supposed to. Earlier choices were made to save time and I wasn't the best at commenting on each struct because I thought I was going to immediately go back and fix it but instead had to work on the Supervisor since January. This is why I volunteered to fix it - nobody should have to figure out what my intentions were from the undocumented prototype.

**Comment by raskchanky** [comment]
@reset I think I'm still missing something regarding the session token.  When a user authenticates with Builder for the first time, the only piece of information that's available to send is the GH auth token.  So by necessity, we must check for a valid session using just that token.  If we changed our session token to be a base64 encoded version of `{account-id}:{GH-auth-token}`, and stored that in our db, then we'd always fail our session lookup, since we don't have the account id when we auth for the first time.  I see the utility of what you're proposing, but I don't see how it avoids breaking session lookups.

**Comment by raskchanky** [comment]
After an offline discussion with @reset, we agreed that this PR in its current state gets us closer to where we need to be than what we currently have.  The optimizations with customizing the session token are good, but preliminary work on them was not going quickly.  In the interest of time, we're going to merge this as is, and circle back to changing the session token at a later date.

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/280075515).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/280075515).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by reset** [comment]
tenor-220659929

**Pull request merged**
