### PR TITLE
Refactor EventSrv protocols from eventsrv crate into eventsrv-protocol

### PR DESCRIPTION
**Pull request by reset**
* Move EventSrv protocols from `components/eventsrv/protocols` to new
  crate at `components/eventsrv-protocols`
* Automatically build protocol documentation and place them at
  `components/eventsrv-protocols/doc` on protocol build

I will need to update our devshell to automatically include the doc gen but for now this will work

tenor-18948187

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
tenor-180686406

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by fnichol** [comment]
Docs look really nice! I'm in

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/254661469).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/254661469).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
