### PR TITLE
Disable 'attach' when running 'hab pkg build <path>'

### LINKED ISSUE #3943: attach shows a not working prompt when hab pkg build is called
This is with `hab 0.38.0/20171026215954`.

When there's a `attach` inside the `plan.sh` and we run the `hab pkg build .` command, the build effectively stops at the `attach` line, but the prompt shown does not work.

If it is not intended to work outside of an interactive studio, it might be good to ignore it, or print a warning during the build.

### PR DESCRIPTION
**Pull request by rsertelon**
Should close #3943

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by elliott-davis** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/313497497).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/313497497).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
