### PR TITLE
[minor] [docs] Changed user.email to user:email to match GitHub UI

### PR DESCRIPTION
**Pull request by jaymitchell**
The GitHub UI uses "user:email" rather than "user.email" when setting up an access token.

github_access_tokens

(There are other instances of `user.email`, but they are in the context of Git settings, so they are correct.)

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @juliandunn, @davidwrede, @cwebberOps and @smith to be potential reviewers

**Comment by smith** [comment]
Thanks!

gif-keyboard-5516947831574775661

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 67e9e30 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 67e9e30 with merge e7e3a50...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139381860)

**Pull request merged**
