### PR TITLE
Feature/memcached plan

### PR DESCRIPTION
**Pull request by bixu**
Signed-off-by: Blake Irvin <blake.irvin@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by reset** [comment]
@thesentinels r+

gif-keyboard-11244692991960356982

**Comment by thesentinels** [comment]
:pushpin: Commit d644098 has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit d644098 with merge be8d1b2...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/141706710)

**Comment by smith** [comment]
[core/memcached/1.4.25/20160701191752](https://app.habitat.sh/#/pkgs/core/memcached/1.4.25/20160701191752) has been built and uploaded to the depot. 💖

**Pull request merged**
