### PR TITLE
run service as current user if set to default hab user and hab does not exist

### PR DESCRIPTION
**Pull request by mwrock**
This addresses a regression from #4692. Historically windows packages would run as `hab` if that user exists (usually not) and fall back to the current user. The `SVC_USER` metafile was completely ignored. Now we honor the `SVC_USER` file but they default to a `hab` user if the plan does not specify a `$pkg_svc_user`. This means that all windows packages will attempt to run as hab and fail if that user does not exist and it almost always will not. We should continue to run under the current user if the `hab` user does not exist. Otherwise most windows packages will break.

Signed-off-by: mwrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/347603026).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/347603026).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
