### PR TITLE
Clean up and persist builder job server's worker state handling

### PR DESCRIPTION
**Pull request by chefsalim**
This change cleans up some of the job server's handling of the workers by consolidating common functionality into a new Worker struct. It now only needs to keep a single list of Workers rather than two lists of busy and ready workers. It also adds persistence of the busy worker state, so that if the workers restart during build jobs, and the job server restarts as well (eg, supervisor updates), the interrupted build jobs can be resumed smoothly. 

Signed-off-by: Salim Alam <salam@chef.io>

tenor-106422771

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

tenor-229515237

Also had no idea we already had a crate that implemented an expiring hash map in our codebase! Totally needed that :)

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/286383447).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/286383447).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
