### PR TITLE
Set no_intra_emphasis and with_toc_data options in redcarpet.

### LINKED ISSUE #2917: Docs formatting issue on https://www.habitat.sh/docs/reference/plan-syntax
This affects the [variables](https://www.habitat.sh/docs/reference/plan-syntax/#variables) and [hooks](https://www.habitat.sh/docs/reference/plan-syntax/#hooks) sections, and possibly a few others. Basically, successive underscores on the same line are being rendered as emphasis, so when you have something like `$pkg_varname: This is set to $pkg_foo/bar` it gets rendered as $pkg _varname: This is set to $pkg_ foo/bar (only without the spaces I added to make it look that way in the github issue).

I'm guessing the fix is to enclose all `$pkg_foo` and `do_bar()` entries in backticks (`) so they show as code. It's also possible there is an option in the markdown parser to require emphasis to only apply on word boundaries.

### LINKED ISSUE #2918: Anchor links in habitat documentation are broken
Example: <https://www.habitat.sh/docs/reference/plan-syntax/#hooks> - this should go to the hooks section, but it goes to the top of the page. Clicking on 'hooks' in the table of contents doesn't work either. This is in the latest stable chrome. The source for the page only shows `<h2>Hooks</h2>` and not `<h2 id="hooks">Hooks</h2>` or similar markup (e.g. `<a name="hooks">`) that allows intra-page links to work. The fix for this is probably an option in the markdown parser if one exists.

### PR DESCRIPTION
**Pull request by mivok**
Fixes #2917
Fixes #2918

Signed-off-by: Mark Harrison <mark@mivok.net>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/263687946).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/263687946).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
