### PR TITLE
Add logos to be used on get started and guide pages

### PR DESCRIPTION
**Pull request by ryankeairns**
This is some prep work for forthcoming Get Started and Guide pages that will soon be added to the website.

The reason for creating them proactively is that we anticipate a variety of contributing authors and this result in one less roadblock to getting content out the door. With the logos in place, authors should be able to simply generate content and create pages.

Signed-off-by: Ryan Keairns <rkeairns@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/320379833).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/320379833).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
