### PR TITLE
Consistent hook behaviour

### PR DESCRIPTION
**Pull request by bodymindarts**
This PR addresses issues raised in https://github.com/habitat-sh/habitat/issues/1742.

It addresses the following issues / bugs:
- init hook is only run when election is completed
- reconfigure hook is run after run hook (also on restart)

And includes some refactoring to make this possible (documented in commit messages).

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by bodymindarts** [comment]
Okay will have to overwork this again now that the 'tick' refactoring has been merged. Didn't see that coming.

**Comment by reset** [comment]
@bodymindarts thanks so much for doing this work! As you saw, I was in the middle of a large refactor to this subsystem when your PR had come in. We really appreciate the time and effort you put into this, though. We can move forward with this PR in one of two ways.

1. I can carry this PR for you and integrate it into the current master branch. I'll be sure to leave your signed-off by line so you get credit!
1. If you fancy getting involved in the newly refactored subsystem, you can reimplement this yourself ;)

Let me know which you'd like to do. I want to make sure we get these changes in

**Comment by bodymindarts** [comment]
@reset while working on the code I thought some refactoring would be in order but decided to focus on the task at hand. So its cool you were working on that, unfortunate I didn't see it got merged.

After taking a look at the current structure I'm happy to reimplement it myself. I think most of what I did can be adapted in a straight forward manner. Thanks for the offer ;-).

**Comment by bodymindarts** [comment]
Closed in favour of https://github.com/habitat-sh/habitat/pull/1757

**Pull request closed without merging**
