### PR TITLE
Kubernetes & docker exporter fixes

### PR DESCRIPTION
**Pull request by zeenix**
This PR features a bunch of fixes to Kubernetes and docker exporters.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@zeenix It looks like the AppVeyor failure may be fixed on master; if you could rebase, I think that should get the tests green, and then we can get it merged.

**Comment by zeenix** [comment]
@christophermaier sure, done. Let's see how the CI goes now..

**Comment by christophermaier** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/333815813).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/333815813).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by tduffield** [comment]
So, this broke our CI pipeline. I understand why it was done, but it would be great if breaking API changes like this were highlighted in the release notes or changelog. cc/ @tashimi

**Comment by tashimi** [comment]
@tduffield the removal of the CLI command was not correct or intentional. We are reverting that change.

**Comment by raskchanky** [comment]
@tashimi @tduffield The revert has been merged https://github.com/habitat-sh/habitat/pull/4617

**Pull request merged**
