### PR TITLE
Unify (and copy-edit) copy between the origin "keys" and "members" tabs.

### PR DESCRIPTION
**Pull request by juliandunn**

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @ryankeairns, @smith and @metadave to be potential reviewers

**Comment by metadave** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit a84887e has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit a84887e with merge d9e9c51...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26820525)

**Pull request merged**
