### PR TITLE
specify that pkg_description is not optional in www docs

### PR DESCRIPTION
**Pull request by metadave**
resolves https://github.com/habitat-sh/habitat/issues/1147

### CODE REVIEW

**Comment by thesentinels** [comment]
@metadave, thanks for your PR! By analyzing the annotation information on this pull request, we identified @davidwrede, @cwebberOps, @stevendanna, @smith and @bscott to be potential reviewers

**Comment by miketheman** [comment]
@metadave It _is_ optional for the plan syntax, but not optional for the `core` repo, as laid out in that repo's docs: https://github.com/habitat-sh/core-plans/blob/master/CONTRIBUTING.md#package-metadata

**Comment by metadave** [comment]
@miketheman good catch, updated.

**Comment by miketheman** [comment]
👍

**Pull request merged**
