### PR TITLE
Remove chattiness on issuing new census rumors

### PR DESCRIPTION
**Pull request by juliandunn**

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk, @reset, @metadave and @fnichol to be potential reviewers

**Comment by metadave** [comment]
@thesentinals r+

**Comment by metadave** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 5cb8947 has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 5cb8947 with merge a73f7f4...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139063711)

**Comment by adamhjk** [comment]
gif-keyboard-892119419104281097

I went hunting for this pre-launch, didn't find it immediately, and got distracted. YDM.

**Pull request merged**
