### PR TITLE
Fix compiler warnings on macOS platform.

### PR DESCRIPTION
**Pull request by fnichol**
A little quality-of-life involving cleaning up some old imports and
constants which are not used on all targets.

Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
Turns out my commit messages could benefit from a spell checker

tenor-164477695

**Comment by mwrock** [comment]
I think https://github.com/habitat-sh/habitat/blob/315faafc4ab2761f78174f26667ae2a4f6393522/components/hab/src/command/launcher.rs#L38 needs to go :)

**Comment by fnichol** [comment]
Good call, I was lazy and CI had my back there. Will rebase and repush.

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/273033693).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/273033693).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
