### PR TITLE
Fix typo that caused macOS builds to fail

### PR DESCRIPTION
**Pull request by georgemarshall**

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by smith** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
Hey, @smith - you don't have permission to issue `approve` on this pull request.

Nope

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/227393141).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/227393141).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by smith** [comment]
> Hey, @smith - you don't have permission to issue approve on this pull request.

@eeyun could you (or somebody that has the access) please take a look at this. I'm listed under core maintainers here (https://github.com/habitat-sh/habitat/blob/master/MAINTAINERS.md), here (https://github.com/orgs/habitat-sh/teams/habitat-core-maintainers), but not here (https://habitat-sh.slack.com/customize/slackbot), and apparently not in wherever the sentinels is configured. Thanks!

**Comment by raskchanky** [comment]
@smith Sorry man 😞 I don't know how you got removed from the list of approvers that thesentinels bot uses but I've added you back.

**Pull request merged**
