### PR TITLE
[hab] Fix `binlink_all_in_pkg()` which did not work correct with rootfs

### PR DESCRIPTION
**Pull request by fnichol**
This fixes a bug where the "binlink all" behavior would not work correctly if a custom `rootfs` path was provided.

As part of the bugfix, a test for both the single and the all behavior have been added. Yes, that looks like a lot of test code. However, this is a first-step experiment with introducing more test code in the `hab` subcommands where root permissions or other side effects don't get in the way. We now have a slightly better avenue for testing with `UI`-outputing code and even a way to test the contents of both output streams.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
Hah, right--I depended on a previous PR. I'll rebase against master and this should be good.

**Comment by christophermaier** [comment]
The failure looks like the code was expecting to be on top of #3135.

Otherwise, looks good!

tenor-111465911

**Comment by fnichol** [comment]
Awesome!

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/274997162).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/274997162).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
