### PR TITLE
Add "hab pkg channels" to list channels for a given package.

### LINKED ISSUE #2682: Add 'hab pkg channels' command
Currently we have no cli mechanism to find out what channels a package belongs to.
We should consider adding a 'hab pkg channels' command to our repertoire.

### PR DESCRIPTION
**Pull request by raskchanky**
tenor-255532587

Closes #2682 

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
Don't merge this yet - I forgot to add API documentation for the new endpoint.

**Comment by cnunciato** [comment]
One thing I'm seeing is that if I call this with a properly formatted but non-existent identifier (`hab pkg channels core/linux-headers/4.3/idontexist`), I get no response, and the exit code is 0. Might be nice to exit nonzero with a not-found-ish message, unless that'd be inconsistent with current behavior.

**Comment by cnunciato** [comment]
Otherwise:

**Comment by chefsalim** [comment]
Looks great!
Not sure if what is up w/ the AppVeyor failure, it doesn't seem related.

**Comment by chefsalim** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/252162402).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/252162402).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
