### PR TITLE
Add `exec` to tutorial app run hook.

### PR DESCRIPTION
**Pull request by smith**
Restarting doesn't work properly without it. See #989.

gif-keyboard-11790824695907597446

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @cwebberOps, @davidwrede, @ryankeairns, @mattray and @nathenharvey to be potential reviewers

**Comment by davidwrede** [comment]
Thanks for putting this in, @smith! 

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit cc440de has been approved by `davidwrede`

**Comment by thesentinels** [comment]
:hourglass: Testing commit cc440de with merge cc440de...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/141744406)

**Pull request merged**
