### PR TITLE
Read multiple blocks if available while loading Metafile contents

### PR DESCRIPTION
**Pull request by metadave**
Fixes https://github.com/habitat-sh/habitat/issues/1011

This adds a `components/core/tests/fixtures/unhappyhumans-possums-8.1.4-20160427165340-x86_64-linux.hart` file with 1024 lines in TDEPS to test with.

cc @habitat-sh/habitat-core-maintainers

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @fnichol and @reset to be potential reviewers

**Comment by miketheman** [comment]
I concur - the proposed fix solves the problem.

**Comment by metadave** [comment]
@habitat-sh/habitat-core-maintainers this should be reviewed/merged asap!

**Comment by smith** [comment]
Looks good!

@thesentinels r+

gif-keyboard-5936216153901027413

**Comment by thesentinels** [comment]
:pushpin: Commit 8e5681b has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 8e5681b with merge 13c4b53...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/142866959)

**Comment by fnichol** [comment]
Sweet, I was looking for this PR. Nice to see that it's merged.

**Comment by metadave** [comment]
oops, just noticed the branch name is off. my bad :-(

**Pull request merged**
