### PR TITLE
Example errors if pkg_version isn't set

### PR DESCRIPTION
**Pull request by spuder**
```
ERROR: Failed to build. 'pkg_version' must be set.
```

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @juliandunn to be a potential reviewer

**Comment by juliandunn** [comment]
Yes, sorry, I was trying to illustrate that this was a _snippet_ of a plan not the entire plan. @davidwrede can you have a look and fill in other mandatory fields as well.

**Comment by thesentinels** [comment]
:umbrella: The latest upstream changes (presumably 738dddf) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by smith** [comment]
The required and optional were added to the docs in #910.

Closing this.

**Pull request closed without merging**
