### PR TITLE
Increase visual distinction for private keys

### LINKED ISSUE #4054: Provide more visual distinction between public and private keys
Currently, private and public keys are only visually distinguished by a subtle slash through the "eye" icon. It would be nice to provide more visual distinction (e.g., putting private keys behind a "show private keys" button, put them under a big "🚧 WARNING 🚧" banner, etc.)

-----------

### To-do
- [x] Add 'private' tag/label to private key row
- [x] Align both upload buttons to the ride side of the tables
- [x] Remove the eye icon from the public key rows
- [x] Remove the `<hr>` between the private and public sections
- [x] Set the spacing between the private and public sections 60px

### Mockup
https://chef.invisionapp.com/share/TSEGSW52H#/250295491_origin_Keys_Download

### PR DESCRIPTION
**Pull request by cnunciato**
Fixes #4054.

Signed-off-by: Christian Nunciato <chris@nunciato.org>

tenor-11880507

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/319290283).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/319290283).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
