### PR TITLE
Release 0.64.0

### PR DESCRIPTION
**Pull request by smacfarlane**
tenor-145665255

Signed-off-by: Scott Macfarlane <macfarlane.scott@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
tenor-151621364

**Comment by jeremymv2** [comment]
yippie

**Pull request merged**
