### PR TITLE
Update copy and legalese on sign-in page

### LINKED ISSUE #3354: [builder ui] Update copy and legalese on Sign In page
We need to add a footnote regarding the Habitat Terms of Service and Privacy Policy.
While we're in here, let's trim the verbose copy below the Sign In button as well.

[Sign In Mockup](https://chef.invisionapp.com/share/ANDO0J96C#/251301095_120_-_Sign_In)

Related to #3351

### PR DESCRIPTION
**Pull request by cnunciato**
Signed-off-by: Christian Nunciato <cnunciato@chef.io>

Fixes #3354.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
image

**Comment by raskchanky** [comment]
tenor-259642505

**Comment by reset** [comment]
tenor-255364638

**Pull request merged**
