### PR TITLE
Add banner advertising webinar to habitat.sh nav

### PR DESCRIPTION
**Pull request by magwalk**
screen shot 2016-06-14 at 3 49 14 pm

Signed-off-by: Maggie Walker <magwalk@gmail.com>

https://chefio.atlassian.net/browse/CIA-806

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @ryankeairns, @cwebberOps and @davidwrede to be potential reviewers

**Comment by juliandunn** [comment]
lgtm

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit ce0fde7 has been approved by `juliandunn`

**Comment by thesentinels** [comment]
:hourglass: Testing commit ce0fde7 with merge f70198d...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26839809)

**Pull request merged**
