### PR TITLE
Update Docs With Correct Link to Plans Repo

### PR DESCRIPTION
**Pull request by pwelch**
Update the documentation to point to the core-plans repo. Core plans
were moved from the plans directory to the core-plans repo on PR #1030

### CODE REVIEW

**Comment by miketheman** [comment]
@pwelch Nice! As you can see, the DCO test has failed - can you try to `git commit --amend -s && git puch --force` to update your commit message?

**Comment by miketheman** [comment]
For reference: https://github.com/habitat-sh/habitat#signing-your-commits

**Comment by pwelch** [comment]
@miketheman All set. Thanks for the help! 👍

**Comment by metadave** [comment]
@thesentinels r+

**Pull request merged**
