### PR TITLE
Fix minor formatting errors in setup.

### PR DESCRIPTION
**Pull request by juliandunn**
* Terminate the "maybe another time" sentences.
* Make sure there are not two blank lines before we print the "Analytics" heading.

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @fnichol and @metadave to be potential reviewers

**Comment by smith** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 8c1f427 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 8c1f427 with merge 53c877b...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26915969)

**Pull request merged**
