### PR TITLE
Release 0.8.0.

### PR DESCRIPTION
**Pull request by fnichol**
Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

### CODE REVIEW

**Comment by fnichol** [comment]
gif-keyboard-1119605749187328702

@thesentinels r+

**Comment by fnichol** [comment]
And once again, cause it's a party:

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit f5d3221 has been approved by `fnichol`

**Comment by thesentinels** [comment]
:hourglass: Testing commit f5d3221 with merge f5d3221...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/143615066)

**Comment by adamhjk** [comment]
gif-keyboard-9667835232377166126

**Pull request merged**
