### PR TITLE
Fix pkg_exports syntax errors in tutorial and builder plans

### LINKED ISSUE #1718: Errors in plan.sh of tutorial
When following the [mac tutorial](https://www.habitat.sh/tutorials/getting-started/mac/basic-concepts/)

The first time we are prompted to run `build` inside the hab studio we get the following output:
```
/src/habitat/plan.sh: line 9: syntax error near unexpected token `newline'
/src/habitat/plan.sh: line 9: `pkg_exports('
ERROR: Failed to load Plan
```

I think [this line](https://github.com/habitat-sh/habitat/blob/master/www/source/shared/_create_plan_common.html.md.erb#L92) is missing an `=`

After adding that `=` running `hab pkg export docker myorigin/mytutorialapp` failed with the following message:
```
Sending build context to Docker daemon 194.9 MB
Step 1/8 : FROM scratch
 --->
Step 2/8 : ENV PATH :/hab/pkgs/core/glibc/2.22/20160612063629/bin:/hab/pkgs/core/node/5.6.0/20161214013051/bin:/hab/pkgs/core/hab-sup/0.16.0/20170119213934/bin:/hab/pkgs/core/busybox-static/1.24.2/20161214032531/bin:/hab/pkgs/core/bzip2/1.0.6/20161208225359/bin:/hab/pkgs/core/glibc/2.22/20160612063629/bin:/hab/pkgs/core/openssl/1.0.2j/20161214012334/bin:/hab/pkgs/core/xz/5.2.2/20161208230159/bin:/hab/pkgs/core/busybox-static/1.24.2/20161214032531/bin:/hab/bin
 ---> Running in 0ccd442373f3
 ---> db923ca531be
Removing intermediate container 0ccd442373f3
Step 3/8 : WORKDIR /
 ---> 6297159c7226
Removing intermediate container 5817a15d939a
Step 4/8 : ADD rootfs /
 ---> 732a0035bc35
Removing intermediate container 970abff79022
Step 5/8 : VOLUME /hab/svc/mytutorialapp/data /hab/svc/mytutorialapp/config
 ---> Running in c050dc489071
 ---> 33ce59e0e90b
Removing intermediate container c050dc489071
Step 6/8 : EXPOSE 9631 port
Invalid containerPort: port
```

In the [mytutorialapp_finished/habitat/plan.sh](https://github.com/habitat-sh/habitat-example-plans/blob/master/mytutorialapp_finished/habitat/plan.sh#L9) it says:
```
pkg_expose=(8080)
```
and not
```
pkg_exports(
  [port]=port
)
pkg_exposes=(port)
```
as documented in the tutorial. When making that substitution it worked.

### PR DESCRIPTION
**Pull request by reset**
Fixes #1718

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/199335339).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/199335339).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
