### PR TITLE
[plan-build] Add Scaffolding direct deps as direct build deps for Plans.

### LINKED ISSUE #2097: Investigate adding Scaffolding direct run deps as direct Plan build deps

### PR DESCRIPTION
**Pull request by fnichol**
This change aims to fulfill a design goal of Scaffolding: within reason,
a Plan author should be able to do what a Scaffolding package provides
directly in their `plan.sh`. A secondary design goal is that Scaffolding
package authors should not need to call any internal API functions from
the build program. The latter goal surfaced a design issue in the
previous Scaffolding implementation around direct vs. transitive
dependencies.

There are several helper functions that a Plan author (and therefore
Scaffolding package author) may use that are marked as part of the
public API. For example, the `pkg_path_for()` will return the absolute
path to the pkg_prefix for a given dependency. The implementation for
`pkg_path_for()` (correctly) only looks at **direct** build and run
dependencies--not indirect/transitive dependencies. If a Plan author is
using a Ruby Scaffolding package that pulls in Bundler for build-time
dependency resolution, then there is a good change they would want to
call something like: `pkg_path_for core/bundler`. The problem here, is
that the previous implementation would fail the `pkg_path_for()` call and
report that the `core/bundler` dependency is not a direct run or build
dependency.

This change injects the Scaffolding pacakge into the direct build
dependency array `${pkg_build_deps[@]}` as before, but now also adds
each direct run dependency for the Scaffolding package into the direct
**build** dependency array of the Plan. For example, a Ruby Scaffolding
package that pulls Bundler in as its run dependency, would yield a Plan
`${pkg_build_deps[@]}` array which contained `core/ruby` as well as
`core/bundler/1.13.7/20170104000124`. Note that these Scaffolding
dependencies are full qualified in order for the same exact versions of
Scaffolding dependencies to be captured as Plan build dependencies.

Finally, as the number of dependency resolving functions has grown, the
activity of resolving dependencies is captured in the
`_resolve_dependencies()` internal function to be used in the main
program flow.

---

There are additional refactoring commits which have attached comments for more detail.

Closes #2097

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/223306203).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/223306203).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by reset** [comment]
gif-keyboard-3733563235945033432

**Pull request merged**
