### PR TITLE
fix windows docker studio and point FS_ROOT to the system drive by default

### LINKED ISSUE #1898: Regression in 0.18.0 - Fail to bind mount /hab/cache/keys for Docker-based hab studio on Windows
Hello - thanks for reporting an issue with Habitat.

In order to help us troubleshoot the issue, please be sure to include the following information if applicable:

- [ x ] OS: Windows 10
- [ x ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

```
Chef-PS > $env:RUST_LOG='debug';$env:HAB_ORIGIN='smurawski'; hab studio enter
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:hab::command::studio::inner: Found studio image locally.
DEBUG:hab::command::studio::inner: Local image id: 1c7b3eec566c

DEBUG:hab::command::studio::inner: Propagating environment variable into container: HAB_ORIGIN=smurawski
DEBUG:hab::command::studio::inner: Docker arguments = ["run", "--rm", "--tty", "--interactive", "--privileged", "--env", "HAB_ORIGIN=smurawski", "--volume", "/var/run/docker.sock:/var/run/docker.sock", "--volume", "/hab/cache/keys:/hab/cache/keys", "--volume", "C:\\source\\github\\smurawski\\hab-kitchen:/src", "habitat-docker-registry.bintray.io/studio:latest", "enter"]
DEBUG:habitat_core::os::process::imp: Calling child process: ("C:\\Program Files\\Docker\\Docker\\Resources\\bin\\docker.EXE") ["run", "--rm", "--tty", "--interactive", "--privileged", "--env", "HAB_ORIGIN=smurawski", "--volume", "/var/run/docker.sock:/var/run/docker.sock", "--volume", "/hab/cache/keys:/hab/cache/keys", "--volume", "C:\\source\\github\\smurawski\\hab-kitchen:/src", "habitat-docker-registry.bintray.io/studio:latest", "enter"]
   hab-studio: Creating Studio at /hab/studios/src (default)
   hab-studio: Importing smurawski secret origin key
✗✗✗
✗✗✗ Crypto error: No revisions found for smurawski sig key
✗✗✗
Error exporting smurawski key
```

The problem is in 

```
"--volume", "/hab/cache/keys:/hab/cache/keys",
```

which should be

```
"--volume", "c:/hab/cache/keys:/hab/cache/keys",
```

Entering a studio without a default key works (which means no `cli.toml` or `HAB_ORIGIN` or `-k`)

### PR DESCRIPTION
**Pull request by mwrock**
fixes #1898

Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
Thanks @smurawski I totally forgot about the break!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/208329109).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/208329109).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
