### PR TITLE
Add Splunk blog post

### LINKED ISSUE #5022: Splunk Blog Post
Demonstrate how to send Habitat health-check data to Splunk.

### PR DESCRIPTION
**Pull request by cnunciato**
This post covers how to use Habitat health checks to monitor an application’s health with Splunk.

Fixes #5022.

Signed-off-by: Christian Nunciato <chris@nunciato.org>

### CODE REVIEW

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/375124324).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/375124324).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by cnunciato** [comment]
http://www.acceptance.habitat.sh/blog/2018/05/tracking-application-health-with-splunk/

**Comment by cnunciato** [comment]
Seeing a few typos I missed. Fixing...

**Comment by cnunciato** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/375132953).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/375132953).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by cnunciato** [comment]
Thanks @nellshamrell!

**Pull request merged**
