### PR TITLE
Replace failing acceptance tests with Angular tests

### LINKED ISSUE #1001: [builder-web] Fix Acceptance Tests
Running `npm run test-e2e` fails (there's a note in the README indicating this is so.)

Reason for failure are either (1) Protractor has been super flaky and failed in lots of cases from the get-go (2) Things have changed so the tests are no longer valid.

Make them all green. We don't necessarily need to use Protractor. Maybe [WebdriverIO](http://webdriver.io/) would be something to try.

You should be able to run tests against a running development or acceptance environment.

### PR DESCRIPTION
**Pull request by cnunciato**
This also replaces Chai and Mocha with Jasmine, which is more commonly used with Angular.

Fixes #1001.

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

### CODE REVIEW

**Comment by raskchanky** [comment]
200w_d

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/222219337).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/222219337).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
