### PR TITLE
windows plans can consume scaffolding plans

### LINKED ISSUE #2921: powershell plan scaffolding
We need to add the same scaffolding loading logic to hab-plan-build-ps1 that we added to bash earlie so we can create some .net based scaffolding.

### PR DESCRIPTION
**Pull request by mwrock**
resolves #2921

Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by reset** [comment]
tenor-117491654

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/264501743).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/264501743).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
