### PR TITLE
[plans] Fix typo in `core/hab-backline`.

### PR DESCRIPTION
**Pull request by fnichol**

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @smith to be a potential reviewer

**Comment by juliandunn** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 49374cd has been approved by `juliandunn`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 49374cd with merge 2df61a6...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26841610)

**Pull request merged**
