### PR TITLE
GitHub type fix

### PR DESCRIPTION
**Pull request by cnunciato**
Signed-off-by: Christian Nunciato <cnunciato@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
Sorry; I had a problem testing this pull request. The error was:

```ruby
Expected process to exit with [0], but received '128'
---- Begin output of git fetch origin pull/3470/merge ----
STDOUT: 
STDERR: Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
fatal: Couldn't find remote ref pull/3470/merge
---- End output of git fetch origin pull/3470/merge ----
Ran git fetch origin pull/3470/merge returned 128
```

Oops

**Pull request merged**
