### PR TITLE
Changes CHANGELOG date format

### LINKED ISSUE #4913: Date format in CHANGELOG.md is incorrect
The dates should be presented in an unambiguous format which can be understood by countries other than the US such as `YYYY-MM-DD`.

This might be an opinion, except it's not.

I'll fight for this one.

---

Context: I've been trying to document some backwards compatible fixes in the codebase and am trying to reference certain Habitat releases and their dates. Talk about confusing, oi!

### PR DESCRIPTION
**Pull request by rsertelon**
> Closes #4913

Signed-off-by: Romain Sertelon <romain@sertelon.fr>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@rsertelon This looks great, thanks.

We can actually remove the `.github_changelog_generator` file entirely, as we're using an in-house tool ("Expeditor") to manage our changelog now.

That being said, I'm not sure why Expeditor has been putting in dates in `MM-DD-YYYY` format, since it should be doing `YYYY-MM-DD` by default. 

@tduffield Do you know why this might be? Does Expeditor honor `.github_changelog_generator` if it's found?

**Comment by tduffield** [comment]
@christophermaier it uses YYYY-MM-DD. It appears you've been manually changing it: 

- https://github.com/habitat-sh/habitat/commit/e183737884d93b33bb47d9f4460e04b0365f0eae#diff-4ac32a78649ca5bdd8e0ba38b7006a1e
- https://github.com/habitat-sh/habitat/commit/0721e2d1fc35c7a5d3316ce211b6f5e02df84787#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by christophermaier** [comment]
@tduffield 🤦‍♂️ 

Since we're not using Expeditor to automatically roll the changelog forward yet, we've been manually adding those release headers. I've just been blindly copy-pasting from previous entries, which would have been written out by the Github Changelog Generator, using the old config.

🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 

Sorry for the noise!

**Comment by rsertelon** [comment]
So should I remove the github changelog generator config file?

**Comment by christophermaier** [comment]
@rsertelon Yeah, if you wouldn't mind, that would be great.

**Comment by rsertelon** [comment]
Will do!

**Comment by rsertelon** [comment]
@christophermaier done ;)

**Comment by christophermaier** [comment]
tenor-53188726

**Pull request merged**
