### PR TITLE
Correct pkg_include_dirs for core/libffi

### PR DESCRIPTION
**Pull request by scassiba**
Signed-off-by: Samuel Cassiba <s@cassiba.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @jtimberman, @fnichol and @smith to be potential reviewers

**Comment by smith** [comment]
Thank you!

gif-keyboard-8490283027426086571

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 73dc93c has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 73dc93c with merge 8a31831...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139224943)

**Comment by smith** [comment]
Built and uploaded https://app.habitat.sh/#/pkgs/core/libffi/3.2.1/20160621150608

**Pull request merged**
