### PR TITLE
docs(README.md) improve readability of commands

### PR DESCRIPTION
**Pull request by d2s**
- Improve readability of commands with Markdown syntax.

Improves readability of rendered documentation on GitHub etc.

### CODE REVIEW

**Comment by thesentinels** [comment]
@d2s, thanks for your PR! By analyzing the annotation information on this pull request, we identified @juliandunn, @nathenharvey, @adamhjk, @metadave and @smith to be potential reviewers

**Comment by miketheman** [comment]
👍 Formatting only. Does an obvious fix require a DCO?

**Comment by raskchanky** [comment]
@miketheman AFAIK, all commits require DCO.

@d2s Please add a DCO signature to your commit.  This should be as easy as: `git commit -s --amend --no-edit` and then force push your branch.

**Comment by d2s** [comment]
@raskchanky Added DCO signature. Should be fine now.

**Pull request merged**
