### PR TITLE
[WIP] Hab command line tool and requisite crates build on Windows

### PR DESCRIPTION
**Pull request by smurawski**
🚧 

This is a work in progress, with plenty left ahead.  I'm opening this PR to make the work easily visible and accessible for code review and feedback.

Native Dependencies:

- [X]  OpenSSL [Build script](https://github.com/smurawski/hab-build-script/blob/master/openssl_static.ps1)
- [X]  Libarchive  [Build script](https://github.com/smurawski/hab-build-script/blob/master/openssl_static.ps1)
- [X]  Libsodium [Build script](https://github.com/smurawski/hab-build-script/blob/master/openssl_static.ps1)
- [X]  bzip2 [Build script](https://github.com/smurawski/hab-build-script/blob/master/openssl_static.ps1)
- [X]  xz [Build script](https://github.com/smurawski/hab-build-script/blob/master/openssl_static.ps1)
- [X]  zlib [Build script](https://github.com/smurawski/hab-build-script/blob/master/openssl_static.ps1)

Crates required:

- [ ] common
- [ ] core (IN PROGRESS - platform specific-y things are stubbed out currently)
- [ ] http_client
- [ ] builder-depot-client
- [ ] builder-protocol

🚧

### CODE REVIEW

**Comment by thesentinels** [comment]
@smurawski, thanks for your PR! By analyzing the annotation information on this pull request, we identified @reset, @fnichol, @metadave and @adamhjk to be potential reviewers

**Comment by adamhjk** [comment]
This is awesome. One note - Habitat uses the DCO, so you need to have all your commits include `-s`. You can fix this for your last commit with:

```bash
$ git commit --amend -s
```

Then you can force-push to your PR branch. 

Additionally, if the work doesn't impact the mainline (ie: we can still compile on linux/mac os), I think you should feel free to brake this up into smaller PRs that we merge to master as you go. It'll avoid giant-review syndrome.

Yay!

**Comment by smurawski** [comment]
@adamhjk Thanks Adam!  I'll definitely fix that first thing in the AM (as well as getting it `rustfmt`'d).  I think breaking it up into smaller merge-able pieces is the right way to go, but I wanted to get something on the record as to direction and status. :)

**Comment by smurawski** [comment]
Closing this PR in favor of issue #1192 to track the progress and break the changes into smaller PRs.

**Pull request closed without merging**
