### PR TITLE
release 0.31.0

### PR DESCRIPTION
**Pull request by mwrock**
Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by christophermaier** [comment]
tenor-126886680

**Comment by chefsalim** [comment]
tenor-158672665

**Comment by mwrock** [comment]
@thesentinels force

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by thesentinels** [comment]
Excellent @mwrock! It always makes me feel nice when humans approve of one anothers work, no matter the consequences. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by thesentinels** [comment]
Sorry @mwrock; I had a problem merging this pull request. The error was:

```ruby
PUT https://api.github.com/repos/habitat-sh/habitat/pulls/3110/merge?access_token=e5c90b5fd954402d1c97fe59f4e0c143b5d74fce: 405 - Pull Request is not mergeable
See: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button
```

Oops

**Comment by fnichol** [comment]
tenor-196094468

**Pull request merged**
