### PR TITLE
Remove restrictions on non-core builds

### PR DESCRIPTION
**Pull request by chefsalim**
This change removes hard-coded restrictions on building non-core packages. It adds a single config for the depot API to allow toggling between allowing and disallowing non-core builds, and the API is the only place we check for non-core builds now. It does some other minor cleanups and enhancement to the scheduler API to add a couple more build options.
 
Signed-off-by: Salim Alam <salam@chef.io>

tenor-268146977

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by tashimi** [comment]
tenor-145753671

**Comment by reset** [comment]
@thesentinels approve

tenor-194733169

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/277573576).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/277573576).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
