### PR TITLE
[sup] Support optional package bind validation.

### PR DESCRIPTION
**Pull request by fnichol**
This change fixes a bug in the sense that until now, the optional
package binds would not be properly validated on service loading in the
Supervisor. Additionally, any bind provided that is not a required or
optional package bind will now correctly cause an error.

Example
-------

For this example, we have a Plan with 2 required binds (`alpha` &
`charlie`) and 1 optional bind (`echo`). The `plan.sh` is as follows:

```sh
pkg_origin=core
pkg_name=bindabind
pkg_version=0.1.0

pkg_binds=(
  [alpha]="beta"
  [charlie]="delta"
)

pkg_binds_optional=(
  [echo]="foxtrot"
)

do_build() {
  return 0
}

do_install() {
  return 0
}
```

When we start the Supervisor without any `--bind` options, we see that
it fails reporting the 2 missing required binds `alpha` & `charlie`:

```
> hab-sup start core/bindabind
hab-sup(MR): Supervisor Member-ID 7aaaf7f7a8cb474ca8f135223553f209
hab-sup(MR): Starting core/bindabind
hab-sup(MR): Unable to start core/bindabind, hab-sup(SS)[src/manager/service/spec.rs:183:23]: Missing required bind(s), alpha, charlie
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
```

If we provide 1 of the 2 required binds, it still fails:

```
> hab-sup start core/bindabind --bind alpha:alpha.default
hab-sup(MR): Supervisor Member-ID 7aaaf7f7a8cb474ca8f135223553f209
hab-sup(MR): Starting core/bindabind
hab-sup(MR): Unable to start core/bindabind, hab-sup(SS)[src/manager/service/spec.rs:183:23]: Missing required bind(s), charlie
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
```

Finally, if we satisfy both the required binds, the bind requirements
are satisfied and the service starts waiting for the service groups to
exist and be satisfied:

```
> hab-sup start core/bindabind --bind alpha:alpha.default --bind charlie:charline.default
hab-sup(MR): Supervisor Member-ID 7aaaf7f7a8cb474ca8f135223553f209
hab-sup(MR): Starting core/bindabind
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
bindabind.default(SR): The specified service group 'alpha.default' for binding 'alpha' is not (yet?) present in the census data.
bindabind.default(SR): The specified service group 'charline.default' for binding 'charlie' is not (yet?) present in the census data.
bindabind.default(SR): Waiting for service binds...
```

We can also provide the optional bind `echo` which will be looked for as
well in the ring:

```
> hab-sup start core/bindabind --bind alpha:alpha.default --bind charlie:charline.default --bind echo:echo.default
hab-sup(MR): Supervisor Member-ID e9977e2475df429d97ccdea8009ef857
hab-sup(MR): Starting core/bindabind
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
bindabind.default(SR): The specified service group 'alpha.default' for binding 'alpha' is not (yet?) present in the census data.
bindabind.default(SR): The specified service group 'charline.default' for binding 'charlie' is not (yet?) present in the census data.
bindabind.default(SR): The specified service group 'echo.default' for binding 'echo' is not (yet?) present in the census data.
bindabind.default(SR): Waiting for service binds...
```

If we provide both required binds and provide an additional bind that is
not a required or optional package bind name, we get an error:

```
> hab-sup start core/bindabind --bind alpha:alpha.default --bind charlie:charline.default --bind nope:nope.default
hab-sup(MR): Supervisor Member-ID 54bbc826adaa4dcca6a0ae2f5a7673f4
hab-sup(MR): Starting core/bindabind
hab-sup(MR): Unable to start core/bindabind, hab-sup(SS)[src/manager/service/spec.rs:195:23]: Invalid bind(s), nope
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
```

We can trigger the previous failure even when providing an optional
bind:

```
> hab-sup start core/bindabind --bind alpha:alpha.default --bind charlie:charline.default --bind echo:echo.default --bind nope:nope.default
hab-sup(MR): Supervisor Member-ID 4bd7c5acc54a46228f8e6d5cd84a22d1
hab-sup(MR): Starting core/bindabind
hab-sup(MR): Unable to start core/bindabind, hab-sup(SS)[src/manager/service/spec.rs:195:23]: Invalid bind(s), nope
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
```

References #2284

Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@fnichol the initial implementation from earlier today was the behaviour that I had in mind for required vs optional binds - this changes it slightly. My intention for optional binds was for them to be lazily loaded, that they can come and go, and that you would handle that in the templating.

I see why this cchange's behaviour fits with the use case of the Ruby scaffolding that you've been working on, though. For anyone else reading: what if you don't want to provide a bind for a database and instead want to use an AWS resource or just something that isn't a Habitat service. This change would essentially make optional binds behave identical to required binds but the CLI won't stop you from starting when you haven't specified one. 

I'm wondering if we should add a flag for the behaviour and set the default to either this, or lazily loaded. Do you think we should allow lazily loaded binds? Should they just be available for optional? If so, what should be the default?

After typing this out and reading the changes I'm inclined to think that lazy loaded should be an option for both and the default should be strict loading.

**Comment by mwrock** [comment]
I like the strict approach and how it forces plan authors to be intentional with the binds expected from a plan and plan users to fully know what to expect. In the case of the database vs. AWS scenario, I'm guessing that regardless of what the bind name is ("AWS" or "database", the plan needs certain config settings to be exposed by the provider. If a plan is capable of consuming AWS settings OR database settings, I'd state those as optional binds.

**Comment by reset** [comment]
I'm going to go ahead and merge this because I think this is the appropriate default behaviour. If we do want to have lazy loading we probably want to add that as an option.

@thesentinels approve

@mwrock I think a bind to some AWS resource/settings would be a neat idea in itself :). This change basically states that we'll wait for all binds, optional included, to be present before the init hook is run for a service

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/230622930).

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/230622930).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by bixu** [comment]
I think these subtle details could be better documented in the community docs. Got burned pretty hard by this over the last few days at $job - it just wasn't clear that `optional` binds are also required to be satisfied at runtime.

**Pull request merged**
