### PR TITLE
Add page titles in Builder UI

### LINKED ISSUE #4372: Add page titles to Builder UI
Currently, all pages have the same title, which makes navigating through history pretty tedious. We should have titles for all routed views.

image

### PR DESCRIPTION
**Pull request by cnunciato**
This change adds page titles to all routed components in Builder UI.

Fixes #4372.

Signed-off-by: Christian Nunciato <chris@nunciato.org>

tenor-165338777

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
tenor-59046505

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/319957417).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/319957417).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
