### PR TITLE
release 0.37.0

### PR DESCRIPTION
**Pull request by mwrock**
Signed-off-by: mwrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
tenor-24319996

**Comment by nellshamrell** [comment]
:shipit:

**Comment by chefsalim** [comment]
Hmm, the changelog looks a bit wierd (Supervisor changes to lower-caps all over?)

**Comment by ryankeairns** [comment]
tenor-219272203

**Comment by mwrock** [comment]
yeah @chefsalim that is because they were uppercased manually and not ig GH so the changelog generator switched them back. I think we should just stick with the GH text as is for the changelog.

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/289263014).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/289263014).

**Pull request merged**
