### PR TITLE
Add key generation to Builder UI

### LINKED ISSUE #2899: Key Generation in Web UI
## User Story

As a user of Builder, I want to be able to generate the keys for my origin upon creation of my origin in the Builder UI, so I can begin working with Builder before even attempting to download the Habitat CLI

* [x] Generate keys in the Keys tab
* [x] Generate keys when I'm creating an origin

### PR DESCRIPTION
**Pull request by cnunciato**
This adds the ability to generate a new origin key pair when creating an origin
and at any time later, and allows the signing key to be downloaded by members of
the origin.

It also refactors to remove the keys-list component, which was being used for both
public and private keys. (Given how different they are, it doesn't make sense to
cram both into the same component.)

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

Fixes #2899.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
tenor-266146666

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/281547028).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
