### PR TITLE
Added sig key checking to core crypto

### PR DESCRIPTION
**Pull request by georgemarshall**
This is in response to a public key that I uploaded to the depot that was a bad copy/paste with invalid chars. The goal is to do a basic check to make sure the key will not break things.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
This looks really great! My only comment is that it looks like there is a pattern here where the number in the error signifies a "type" of error. I'm deferring to @reset  or @fnichol to confirm this is indeed the pattern, but if so, perhaps the error string should be `write_sig_key_from_str:4 Malformed sig key string`.

**Comment by georgemarshall** [comment]
From my gathering the number seems more like a "section" reference than an error "type".

**Comment by mwrock** [comment]
Right but with the aim to make it clear what logic branch caused the error so having a separate number here I think it would be faster to deduce the nature of the error.

**Comment by reset** [comment]
@mwrock @georgemarshall this isn't a "NetError" so the formatting of the message body doesn't need to be used here - you can use whatever message is helpful to send back to the user.

The formatting that @mwrock is talking about is in the form `{service}:{operation}:{case}`. Service is the service or module which the error occured in. Operation is what was happening at the time. Case is the branch of code that caused the error. This is a static message (no string concatentation or injection) and is meant to be used at a later date to build up a knowledge base for self help and to assist in localizing clients.

**Comment by reset** [comment]
@thesentinels approve

gif-keyboard-12597638913184257927

Thanks for catching this, very sorry for the problem it caused you!

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/190379457).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/190379457).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
