### PR TITLE
Handle case where plan file is at the root

### PR DESCRIPTION
**Pull request by chefsalim**
This change fixes a couple of cases where the Builder github hook does not kick off builds as expected when there is no explicit .bldr.toml file:

1. If the plan.sh is at the root of the repo, or
2. If the plan.sh is in a habitat subfolder, and the change made is above that folder (eg, in the parent path).

Signed-off-by: Salim Alam <salam@chef.io>

tenor-114047197

### CODE REVIEW

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by reset** [comment]
tenor-160383727

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/312723662).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/312723662).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
