### PR TITLE
Revert "Revert "k8s exporter: Add docker image generation""

### PR DESCRIPTION
**Pull request by christophermaier**
This reverts commit 06778b480831503e0d40761f375cc12c08ee195c.

It was taken out during the unfortunate release problems surrounding
0.50.3; we're replacing it to get the functionality back.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
I think we should add the commits of #4200 to this PR to validate that it builds in travis.

**Comment by christophermaier** [comment]
Rebased on top of #4200; if it passes, we're should be good to merge (pending rebases, etc.)

**Comment by christophermaier** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/311644268).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/311644268).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by mwrock** [comment]
Looks like the merge to master failed with the same error we were seeing last week: https://travis-ci.org/habitat-sh/habitat/jobs/311648166

**Pull request merged**
