### PR TITLE
Fix migrations for real

### PR DESCRIPTION
**Pull request by elliott-davis**
Signed-off-by: Travis Elliott Davis <edavis@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by chefsalim** [comment]
tenor-127656605

**Comment by christophermaier** [comment]
tenor-152812823

**Comment by raskchanky** [comment]
tenor-212659942

**Pull request merged**
