### PR TITLE
Add Demo to Tutorials Quick Links

### PR DESCRIPTION
**Pull request by Padgett**
Signed-off-by: Joshua Padgett <jpadgett@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @TrevorBramble, @ryankeairns and @davidwrede to be potential reviewers

**Comment by smith** [comment]
Thanks! @thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit b0c981f has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit b0c981f with merge daad28c...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26818487)

**Pull request merged**
