### PR TITLE
Reverts 65a1f9 and a03510 for hab-plan-build.sh

### PR DESCRIPTION
**Pull request by eeyun**
This change should resolve the build failures in the 0.76.0 release. There are valuable shell linting fixes in here that we will roll back out once we've resolved the illusive bug in theses changes.

Signed-off-by: Ian Henry <ihenry@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
Also note that we expect the verify pipeline to fail so we're going to merge past that for the moment.

**Comment by fnichol** [comment]
We're looking at one more test case to confirm before merging.

**Comment by eeyun** [comment]
We have validated within reason that this change gets us and our users to a functional state. :boom:

**Comment by raskchanky** [comment]
Can one of y'all with the proper context open an issue to follow up with the work to find the illusive bug(s) and put the correct lints back in place?

**Pull request merged**
