### PR TITLE
[WIP] New getting started tutorial based on RoR + PostgreSQL

### PR DESCRIPTION
**Pull request by davidwrede**
This is a new tutorial showing how to use Ruby scaffolding to build rails app and have it connect to PostgreSQL package.

This tutorial shows the following:

- How to use `hab plan init`
- How to use the Ruby scaffolding to create a package
- How to create a health_check hook for app health monitoring
- How to dynamically update packages via `hab config apply`
- How to export packages to Docker containers and then run them via Docker Compose
- How to upload a package and (optionally) promote it

The current tutorial has been left in the repo (only the navigation sidebars have been changed) in case we want to reuse it in some other location.

And, I will be adding in a version of the tutorial that shows how to run this in VMs via a Vagrant + VirtualBox. The `choose-environment` topic will be part of that flow, but these updates will come in a subsequent PR.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/255937987).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/255937987).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by davidwrede** [comment]
The new tutorial work in this PR has been merged into #2861.

**Pull request closed without merging**
