### PR TITLE
[plan-build] Recompute `PATH` when using `pkg_version()` helper.

### LINKED ISSUE #2265: Fix `PATH` setting timing in the build program
From @robbkidd in HabiSlack:

> Working with :habitat: 0.22 and it's shiny new `pkg_version()` hook. :heart_eyes:
Either I'm doing something wrong or there might be something wonky with the environment available in `pkg_version()`. We needed to `hab pkg exec core/ruby ruby` to run Ruby there despite `core/ruby` being a dependency. Seems maybe the PATH constructed of dependencies' bins isn't set there? https://github.com/chef/dcob/blob/master/habitat/plan.sh#L20-L24

References #2237

### PR DESCRIPTION
**Pull request by fnichol**
Closes #2265

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/230532631).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/230532631).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by robbkidd** [comment]
PATH that rocks

Confirmed fixes issues described in #2265.

**Pull request merged**
