### PR TITLE
`hab svc load` respects currently-installed software

### LINKED ISSUE #4019: `hab svc load` fails when acting on local-only package (.hart file)
We've seen behavior where, after installing a local-only package (on a VM or in the Studio), `hab svc load` fails.

- [ ] The OS (including version): macOS
- [ ] Debug/backtrace of the command you are trying to run:
```
[1][default:/src:0]# ls results/smartb-api-0.1.0-20171027160226-x86_64-linux.hart
[1][default:/src:0]# hab pkg install results/smartb-api-0.1.0-20171027160226-x86_64-linux.hart
[38][default:/src:1]# RUST_LOG=debug RUST_BACKTRACE=1 hab svc load smartb/api
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_core::os::process::imp: Calling execvp(): ("/hab/pkgs/core/hab-sup/0.38.0/20171026221910/bin/hab-sup") ["load", "smartb/api"]
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::command::package::install: install key_cache_path: /hab/cache/keys
DEBUG:habitat_http_client::ssl: Setting CA file for SSL context to: /hab/pkgs/core/cacerts/2017.09.20/20171014212239/ssl/cert.pem
DEBUG:habitat_http_client::api_client: User-Agent: hab-sup/0.38.0/20171026221910 (x86_64-linux; 4.9.49-moby)
» Installing smartb/api from channel 'stable'
DEBUG:habitat_http_client::api_client: GET https://bldr.habitat.sh/v1/depot/channels/smartb/stable/pkgs/api/latest with ApiClient { endpoint: "https://bldr.habitat.sh/v1", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 60, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab-sup/0.38.0/20171026221910 (x86_64-linux; 4.9.49-moby)") }
DEBUG:hyper::net: http scheme
DEBUG:hyper::net: https scheme
DEBUG:hyper::http::h1: request line: Get "/v1/depot/channels/smartb/stable/pkgs/api/latest" Http11
DEBUG:hyper::http::h1: headers=Headers { Host: bldr.habitat.sh
, User-Agent: hab-sup/0.38.0/20171026221910 (x86_64-linux; 4.9.49-moby)
, }
DEBUG:hyper::client::response: version=Http11, status=NotFound
DEBUG:hyper::client::response: headers=Headers { Access-Control-Allow-Headers: authorization, range
, Access-Control-Allow-Methods: PUT, DELETE, PATCH
, Access-Control-Allow-Origin: *
, Access-Control-Expose-Headers: content-disposition
, Content-Type: application/json
, Server: nginx/1.11.10
, Via: 1.1 varnish
Via: 1.1 varnish
, Fastly-Debug-Digest: 82aac8545d5c2565e07740c36f039d7b654fcd0d3f3bd0c0e7160af3fc2ae233
, Content-Length: 57
, Accept-Ranges: bytes
, Date: Tue, 07 Nov 2017 15:33:52 GMT
, Age: 0
, Connection: keep-alive
, X-Served-By: cache-sea1035-SEA, cache-hhn1549-HHN
, X-Cache: MISS, MISS
, X-Cache-Hits: 0, 0
, Vary: Accept-Encoding
, Strict-Transport-Security: max-age= 7776000; includeSubDomains
, X-Frame-Options: SAMEORIGIN
, }
DEBUG:habitat_http_client::api_client: GET https://bldr.habitat.sh/v1/depot/channels/smartb with ApiClient { endpoint: "https://bldr.habitat.sh/v1", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 60, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab-sup/0.38.0/20171026221910 (x86_64-linux; 4.9.49-moby)") }
DEBUG:hyper::http::h1: request line: Get "/v1/depot/channels/smartb" Http11
DEBUG:hyper::http::h1: headers=Headers { Host: bldr.habitat.sh
, User-Agent: hab-sup/0.38.0/20171026221910 (x86_64-linux; 4.9.49-moby)
, }
DEBUG:hyper::client::response: version=Http11, status=Ok
DEBUG:hyper::client::response: headers=Headers { Access-Control-Allow-Headers: authorization, range
, Access-Control-Allow-Methods: PUT, DELETE, PATCH
, Access-Control-Allow-Origin: *
, Access-Control-Expose-Headers: content-disposition
, Alternate-Protocol: 443:npn-spdy/3
, Cache-Control: private, no-cache, no-store
, Content-Type: text/plain
, Server: nginx/1.11.10
, X-Content-Type-Options: nosniff
, X-UA-Compatible: IE=Edge
, X-XSS-Protection: 1; mode=block
, Accept-Ranges: bytes
Accept-Ranges: bytes
, Via: 1.1 varnish
Via: 1.1 varnish
, Age: 0
, Fastly-Debug-Digest: d1f05c878a01de9476006268c901f30a2d0c3332147f3f7a26c226c1b21913d6
, Content-Length: 39
, Date: Tue, 07 Nov 2017 15:33:53 GMT
, Connection: keep-alive
, X-Served-By: cache-sea1051-SEA, cache-hhn1549-HHN
, X-Cache: MISS, MISS
, X-Cache-Hits: 0, 0
, Vary: Accept-Encoding
, Strict-Transport-Security: max-age= 7776000; includeSubDomains
, X-Frame-Options: SAMEORIGIN
, }
DEBUG:habitat_http_client::api_client: GET https://bldr.habitat.sh/v1/depot/channels/smartb/stable/pkgs/api/latest with ApiClient { endpoint: "https://bldr.habitat.sh/v1", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 60, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab-sup/0.38.0/20171026221910 (x86_64-linux; 4.9.49-moby)") }
DEBUG:hyper::http::h1: request line: Get "/v1/depot/channels/smartb/stable/pkgs/api/latest" Http11
DEBUG:hyper::http::h1: headers=Headers { Host: bldr.habitat.sh
, User-Agent: hab-sup/0.38.0/20171026221910 (x86_64-linux; 4.9.49-moby)
, }
DEBUG:hyper::client::response: version=Http11, status=NotFound
DEBUG:hyper::client::response: headers=Headers { Access-Control-Allow-Headers: authorization, range
, Access-Control-Allow-Methods: PUT, DELETE, PATCH
, Access-Control-Allow-Origin: *
, Access-Control-Expose-Headers: content-disposition
, Content-Type: application/json
, Server: nginx/1.11.10
, Accept-Ranges: bytes
Accept-Ranges: bytes
, Via: 1.1 varnish
Via: 1.1 varnish
, Age: 0
, Fastly-Debug-Digest: 82aac8545d5c2565e07740c36f039d7b654fcd0d3f3bd0c0e7160af3fc2ae233
, Content-Length: 57
, Date: Tue, 07 Nov 2017 15:33:53 GMT
, Connection: keep-alive
, X-Served-By: cache-sea1027-SEA, cache-hhn1549-HHN
, X-Cache: MISS, MISS
, X-Cache-Hits: 0, 0
, Vary: Accept-Encoding
, Strict-Transport-Security: max-age= 7776000; includeSubDomains
, X-Frame-Options: SAMEORIGIN
, }
DEBUG:habitat_http_client::api_client: GET https://bldr.habitat.sh/v1/depot/channels/smartb/unstable/pkgs/api/latest with ApiClient { endpoint: "https://bldr.habitat.sh/v1", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 60, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab-sup/0.38.0/20171026221910 (x86_64-linux; 4.9.49-moby)") }
DEBUG:hyper::http::h1: request line: Get "/v1/depot/channels/smartb/unstable/pkgs/api/latest" Http11
DEBUG:hyper::http::h1: headers=Headers { Host: bldr.habitat.sh
, User-Agent: hab-sup/0.38.0/20171026221910 (x86_64-linux; 4.9.49-moby)
, }
DEBUG:hyper::client::response: version=Http11, status=NotFound
DEBUG:hyper::client::response: headers=Headers { Access-Control-Allow-Headers: authorization, range
, Access-Control-Allow-Methods: PUT, DELETE, PATCH
, Access-Control-Allow-Origin: *
, Access-Control-Expose-Headers: content-disposition
, Content-Type: application/json
, Server: nginx/1.11.10
, Via: 1.1 varnish
Via: 1.1 varnish
, Fastly-Debug-Digest: 6d45cc9fec09725dd0358c5dc3a5767c396a618aff423fe53d1318e6b0eef67d
, Content-Length: 57
, Accept-Ranges: bytes
, Date: Tue, 07 Nov 2017 15:33:53 GMT
, Age: 0
, Connection: keep-alive
, X-Served-By: cache-sea1044-SEA, cache-hhn1549-HHN
, X-Cache: MISS, MISS
, X-Cache-Hits: 0, 0
, Vary: Accept-Encoding
, Strict-Transport-Security: max-age= 7776000; includeSubDomains
, X-Frame-Options: SAMEORIGIN
, }
hab-sup(ER)[src/error.rs:454:8]: Package not found
```
		
- [ ] Current Habitat environment variables where the `hab` command or supervisor is running:
  - [ ] a. before starting the studio:
```
$ env | grep HAB | grep -v HAB_AUTH_TOKEN

```
  - [ ] b. inside the studio:
```
[39][default:/src:1]# env | grep HAB | grep -v HAB_AUTH_TOKEN
HAB_ORIGIN=smartb
HAB_BINLINK_DIR=/hab/bin
```

### LINKED ISSUE #4065: hab sup load not respecting installed package
Setup:
I have installed a package from a local .hart file

`hab svc load my/package` -> habitat checks the stable channel for package
`hab svc start my/package` -> habitat starts the package

```
root@precise64:/vagrant# uname -a
Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

```
hab-sup(MN): Unloading "/hab/sup/default/specs/sparc-request.spec"
root@precise64:/vagrant# RUST_LOG=debug RUST_BACKTRACE=1 hab svc load chrisortman/sparc-request
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_core::os::process::imp: Calling execvp(): ("/hab/pkgs/core/hab-sup/0.38.0/20171026221910/bin/hab-sup") ["load", "chrisortman/sparc-request"]
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::command::package::install: install key_cache_path: /hab/cache/keys
DEBUG:habitat_http_client::ssl: Setting CA file for SSL context to: /hab/pkgs/core/cacerts/2017.09.20/20171014212239/ssl/cert.pem
DEBUG:habitat_http_client::api_client: User-Agent: hab-sup/0.38.0/20171026221910 (x86_64-linux; 3.2.0-23-generic)
» Installing chrisortman/sparc-request from channel 'stable'
DEBUG:habitat_http_client::api_client: GET https://bldr.habitat.sh/v1/depot/channels/chrisortman/stable/pkgs/sparc-request/latest with ApiClient { endpoint: "https://bldr.habitat.sh/v1", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 60, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab-sup/0.38.0/20171026221910 (x86_64-linux; 3.2.0-23-generic)") }
DEBUG:hyper::net: http scheme
DEBUG:hyper::net: https scheme
DEBUG:hyper::http::h1: request line: Get "/v1/depot/channels/chrisortman/stable/pkgs/sparc-request/latest" Http11
DEBUG:hyper::http::h1: headers=Headers { Host: bldr.habitat.sh
, User-Agent: hab-sup/0.38.0/20171026221910 (x86_64-linux; 3.2.0-23-generic)
, }
^C
```

**No env vars**

### LINKED ISSUE #4602: Supervisor update check when loading service blocks service release to live
It appears that there is a behavior change when services are loaded - an update is attempted during the service load.  If this happens while we are terraforming one of the key live services, the update attempt fails, and the rest of the terraform sequence fails as well - so we are left with no way to bootstrap live services currently.

To reproduce:
Make sure service artifact is installed (similar to the bootstrap):
```
    HAB_BLDR_URL=http://not-a-real-depot.habitat.sh \
                 ${hab_bootstrap_bin} pkg install ${tmpdir}/artifacts/habitat-${pkg_name}-*.hart
```

Then do a `hab svc load`.

### PR DESCRIPTION
**Pull request by christophermaier**
Read commits for details

Fixes #4019
Fixes #4065
Fixes #4602

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/340675115).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/340675115).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by fnichol** [comment]
Wow, that's a good catch!

**Pull request merged**
