### PR TITLE
Update and remove a few additional orphans from the plans exodus

### PR DESCRIPTION
**Pull request by reset**
Just a few things I missed, oops!

Signed-off-by: Jamie Winsor <jamie@vialstudios.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @jtimberman, @fnichol, @juliandunn, @thommay, @metadave and @adamhjk to be potential reviewers

**Comment by juliandunn** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit b3363cf has been approved by `juliandunn`

**Comment by thesentinels** [comment]
:hourglass: Testing commit b3363cf with merge b3363cf...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/141722573)

**Pull request merged**
