### PR TITLE
Enable zlib support for core/python2

### PR DESCRIPTION
**Pull request by scassiba**
Signed-off-by: Samuel Cassiba <s@cassiba.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @jtimberman and @fnichol to be potential reviewers

**Comment by smith** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- There's another pull request that is currently being tested, blocking this pull request: #869

**Comment by thesentinels** [comment]
:pushpin: Commit 2687f6d has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 2687f6d with merge c91e39c...

**Comment by smith** [comment]
Manually merging.

**Pull request merged**
