### PR TITLE
Update development build instructions and upgrade devshell software versions.

### PR DESCRIPTION
**Pull request by fnichol**
This changeset updates the `BUILDING.md` entries for the Mac and Linux platforms to current working instructions. Among the changes are:

* Update the Mac instructions to current standards, using Docker for Mac
* Update devshell to latest Ubuntu release (16.10/Yakkety)
* Add gdb 7.12 to devshell for superior `rust-gdb` support
* Add `hab-butterfly` component into Makefile
* Split shell code out of Dockerfile and into reusable scripts that can be used by developers on Ubuntu workstations and VMs directly.
* Turn code blocks in `BUILDING.md` into reusable scripts for older Ubuntu and CentOS users

For more details, see the individual commit messages.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/185567256).

**Comment by reset** [comment]
gif-keyboard-14697632902306077229

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/185567256).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
