### PR TITLE
Census refactoring

### PR DESCRIPTION
**Pull request by bodymindarts**
Part of my ongoing 'Spring Cleaning' effort https://github.com/habitat-sh/habitat/issues/2094
This refactoring addresses issues around the `census` module.

1) Performance
the previous implementation was rebuilding the entire `CensusList` object graph every tick. Now objects are being reused.

2) Interface
the public interface of the structs in the `census` module is much smaller and more concise.

3) Naming
The names `CensusRing`, `CensusGroup` and `CensusMember` are intended to reference other concepts we are using as they are for the most part mirrors.

4) Decoupling layers
This is a very important issue that will still require many steps to get right but here at least some progress has been made in that the `Service.tick` method doesn't receive a mutable reference to `CensusUpdate` anymore.

The gist of this refactoring was previously discussed with @reset and the execution saves us 160LOC and probably some performance... look forward to feedback.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@bodymindarts this looks perfect, I'll go ahead and add a license header to the top of the new module you added

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/224481599).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/224481599).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by mwrock** [comment]
So great that you are focusing on this @bodymindarts !

**Pull request merged**
