### PR TITLE
Prep for release 0.26.0

### PR DESCRIPTION
**Pull request by chefsalim**
Signed-off-by: Salim Alam <salam@chef.io>

tenor-197965441

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by nellshamrell** [comment]
👍

**Comment by raskchanky** [comment]
tenor-115432363

**Comment by reset** [comment]
tenor-242095238

**Pull request merged**
