### PR TITLE
Add APIs for builder integrations

### PR DESCRIPTION
**Pull request by chefsalim**
This change adds APIs and infrastructure for external integration capability to builder. Specifically, it allows for application-specific settings to be persisted to the origin store. For example, for Docker integration, we may want settings to include credentials for publishing a package to Docker Hub, or a url for a private registry. 

The added integration APIs allow for GET, PUT and DELETE of integration settings per origin/integration/name.  There can be multiple sets of settings associated with a particular integration, and those are identified by the 'name'.  (Currently, the GET only allows for retrieval of the names).

The payload is required to be valid JSON. We don't ordain what is in the JSON - the fields will be different for and specific to each integration. The payload is encrypted and persisted to the origin store, and can later be retrieved as needed by a build or post-processing job.

Signed-off-by: Salim Alam <salam@chef.io>

tenor-92032648

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by chefsalim** [comment]
Will be making some tweaks based on discussion w/ @cnunciato

**Comment by chefsalim** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/269678263).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/269678263).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
