### PR TITLE
Update builder-scheduler job handling

### PR DESCRIPTION
**Pull request by chefsalim**
This change fleshes out the job handling capability of the scheduler. It adds more robust dispatching at the scheduler front end, and the back end implements a state machine to track the progress of the group dispatching and jobs. It also adds an endpoint to the depot API to get status of a scheduled group of jobs. The data store continues to be in-memory for now.

Signed-off-by: Salim Alam <salam@chef.io>

giphy 12

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/211194935).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/211194935).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
