### PR TITLE
Fix grammar.

### PR DESCRIPTION
**Pull request by phiggins**

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
This looks great @phiggins!  In order to merge this, we need a DCO line attached to your commit.  If you use command line git, this is as simple as running `git commit -s --amend --no-edit` and force pushing your branch.

**Comment by raskchanky** [comment]
@phiggins can you rebase this against master?  I'm guessing that will fix the travis failure.

**Comment by phiggins** [comment]
@raskchanky I did the original edit from the github UI (because I am lazy) so it should be up to date. I force-pushed after amending so hopefully it will pass this time?

**Comment by raskchanky** [comment]
@phiggins Gotcha.  Looks like travis is still failing, but I'm confident it's not because of your edit 😉 @eeyun thoughts on this?

**Comment by eeyun** [comment]
Hmm it's definitely because of the acceptance changes today. I wonder if its to do with the PR coming from a fork. One moment I want to check the travis UI

**Comment by smith** [comment]
> Hmm it's definitely because of the acceptance changes today. I wonder if its to do with the PR coming from a fork. One moment I want to check the travis UI

I think you're right. Encrypted environment variables won't be present on forks. I saw a mention of this on an issue, maybe it can help for our use case: https://docs.travis-ci.com/user/jwt

**Comment by eeyun** [comment]
Ah there is in fact a way to do this without extra plugins etc. I'll need to circle back in the a.m. to get it sorted though as it will take me a bit to track down the keys we've used etc.

**Comment by eeyun** [comment]
Ok I've got PRs in for the travis side of this _and_ the sentinels side of this. I'd like to keep these open until the sentinels PRs are merged so that we can use these to test whether the sentinels does what we expect it to for the acceptance environment.

**Comment by eeyun** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by eeyun** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/211021878).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/211021878).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/211021878).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by eeyun** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/211087106).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/211087106).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
