### PR TITLE
Fix markdown format for middleman

### PR DESCRIPTION
**Pull request by tashimi**
Signed-off-by: Tasha Drew <tasha.drew@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by tashimi** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
Hey, @tashimi - you don't have permission to issue `deploy` on this pull request.

Nope

**Comment by eeyun** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/248059998).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/248059998).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by tashimi** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/248066358).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/248066358).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by cnunciato** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
Sorry; I had a problem deploying this change to acceptance. The error was:

```ruby
Expected process to exit with [0], but received '128'
---- Begin output of git fetch origin pull/2667/merge ----
STDOUT: 
STDERR: Warning: Permanently added 'github.com,192.30.255.113' (RSA) to the list of known hosts.
fatal: Couldn't find remote ref pull/2667/merge
---- End output of git fetch origin pull/2667/merge ----
Ran git fetch origin pull/2667/merge returned 128
```

Oops

**Pull request merged**
