### PR TITLE
Use sup-run instead of hab sup run in demo

### LINKED ISSUE #5538: Process supervisor tutorial gives command examples that don't work
On step 10, I'm asked to run the following two commands:
```
[1][default:/src:0]# hab sup run
[2][default:/src:0]# hab svc load yourorigin/sample-node-app --strategy at-once
```
Unfortunately, the terminal just hangs after `hap sup run` so you can't really ever execute the second command.

### PR DESCRIPTION
**Pull request by rsertelon**
> Closes #5538

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by rsertelon** [comment]
Should I go with @cnunciato comment then and remove mentions of starting the supervisor? (instead say it's already started in the studio?)

**Comment by mwrock** [comment]
I'm going to merge this since the tutorial explicitly has the user enter a studio and there is no mention of using `HAB_STUDIO_SUP`. We could definitely go into some detail about starting a supervisor in different environments but this PR as feels like an easy win.

**Comment by mwrock** [comment]
Doh! we are in a merge freeze. Will merge as soon as that is lifted.

**Pull request merged**
