### PR TITLE
Migrate from rustc-serialize to serde in preparation for Rust 1.15

### PR DESCRIPTION
**Pull request by reset**
Serde is the preferred crate for serialization in Rust but we were
unable to change our serialization implementation because it requires
unstable/nightly Rust.

This commit removes our requirement on rustc-serialize and replaces
any calls to it with the serde equivalent. We're able to switch to serde
ahead of the release of Rust 1.15 by leveraging the serde_codegen crate
and some tricks in our rustc build process.

After Rust 1.15 is released, we can rollback the tricks by moving all
of the struct definitions from the `serde_types.in.rs` files placed in
the `src` root of many of our crates and disabling the codegen process
in our `build.rs` files.

gif-keyboard-8781831007990019443

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/194439650).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/194439650).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
