### PR TITLE
add instructions for building a windows launcher

### PR DESCRIPTION
**Pull request by mwrock**
Signed-off-by: mwrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
Here is the doc on the API we use for encryption: https://docs.microsoft.com/en-us/windows/desktop/api/dpapi/nf-dpapi-cryptprotectdata. The entropy parameter is what we use to ensure that only hab can decrypt the value.

**Comment by mwrock** [comment]
done @christophermaier

**Comment by christophermaier** [comment]
@mwrock Great, thank you! We'll get this merged once the release is out.

**Pull request merged**
