### PR TITLE
Link Builder to /pkgs, Fix link name in www nav

### PR DESCRIPTION
**Pull request by cnunciato**
Signed-off-by: Christian Nunciato <cnunciato@chef.io>

cc: @ryankeairns

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by ryankeairns** [comment]
So linking to packages fixes the redirect back to the www site, since /pkgs doesn't require you to be signed in, right?

**Comment by cnunciato** [comment]
@ryankeairns Yep, that's right.

**Comment by reset** [comment]
tenor-197458914

**Pull request merged**
