### PR TITLE
eachAlive does not support `as |member|` style syntax

### PR DESCRIPTION
**Pull request by smurawski**
`hab-sup` 0.18.0

This works,

```
{{#eachAlive binding.default.members}}
IP: {{sys.ip}}
{{/eachAlive}}
```

This doesn't

```
{{#eachAlive binding.default.members as |member|}}
IP: {{member.sys.ip}}
{{/eachAlive}}
```

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by smurawski** [comment]
@smith I reverted some of your changes here in favor of a new test/test template.  This way, we've got broader test coverage over both use cases, with and with `as |something|`.

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/208347748).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/208347748).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/208347748).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/208347748).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/208347748).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
