### PR TITLE
Drop Cargo nightly requirement as of Rust 1.12.0 release.

### PR DESCRIPTION
**Pull request by fnichol**
This change was possible due to the release of Rust 1.12.0 which
features a version of Cargo which supports the workspace feature in use
in this project.

In an effort to minimize and simplify internal setup and external
requirements, we can switch back to the Rust stable version of Cargo.

**Note** that currently the TravsCI infrastructure was left unchanged
until there is good evidence that Rust 1.12.0 is being installed across
their fleet.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
Beat me to it!

gif-keyboard-1991244969179219822

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/163839971).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/163839971).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by fnichol** [comment]
Confirmed that a brand new devshell leads to compiling our project. Same for building `core/hab-sup` without the `core/cargo-nightly` build dep. Woot!

**Pull request merged**
