### PR TITLE
Rename in tutorial output

### PR DESCRIPTION
**Pull request by davidwrede**
- Rename of tutorial source code and output to match package name.

Signed-off-by: David Wrede <dwrede@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @cwebberOps, @ryankeairns, @mattray and @nathenharvey to be potential reviewers

**Comment by juliandunn** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit b04eb21 has been approved by `juliandunn`

**Comment by thesentinels** [comment]
:hourglass: Testing commit b04eb21 with merge 8513634...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26784390)

**Pull request merged**
