### PR TITLE
Add docutils plan

### PR DESCRIPTION
**Pull request by kevindickerson**
Adds `docutils` v0.12

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by smith** [comment]
Thanks!

gif-keyboard-1832083954490940211

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 5aa0dbf has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 5aa0dbf with merge 5a6ab4e...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26899021)

**Pull request merged**
