### PR TITLE
Fix bug in graph pre-check

### LINKED ISSUE #2633: Errors uploading packages with dependencies
On a fresh VM (Ubuntu 16.04 here), after bootstrapping and starting with `make bldr-run`, I'm unable to submit packages with dependencies to the local depot. The errors I'm seeing (for example, on attempting to upload `core/hab-backline`, which depends on `core/attr`) are:

First:

```
scheduler.1 | DEBUG:habitat_net::dispatcher: OnMessage, message_id: "PackagePreCreate" body: "\n\037core/attr/2.4.47/20170513213059\022\036core/glibc/2.22/20170513201042" route_info {protocol: Scheduler hash: 270155433464124382}
scheduler.1 | DEBUG:habitat_builder_scheduler::server: Message received: PackagePreCreate
scheduler.1 | DEBUG:habitat_builder_scheduler::server::handlers: package_precreate message: ident: "core/attr/2.4.47/20170513213059" deps: "core/glibc/2.22/20170513201042"
scheduler.1 | thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:329
```

... followed by four of these, as `hab` retries the failed upload: 

```
scheduler.1 | DEBUG:habitat_net::dispatcher: OnMessage, message_id: "PackagePreCreate" body: "\n\037core/attr/2.4.47/20170513213059\022\036core/glibc/2.22/20170513201042" route_info {protocol: Scheduler hash: 270155433464124382}
scheduler.1 | DEBUG:habitat_builder_scheduler::server: Message received: PackagePreCreate
scheduler.1 | DEBUG:habitat_builder_scheduler::server::handlers: package_precreate message: ident: "core/attr/2.4.47/20170513213059" deps: "core/glibc/2.22/20170513201042"
scheduler.1 | thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /checkout/src/libcore/result.rs:859
```

### PR DESCRIPTION
**Pull request by chefsalim**
This fixes a missed case where extending the package graph with a dependency that is not already present later caused a panic when the dependency was later added.

Fixes #2633 

Signed-off-by: Salim Alam <salam@chef.io>

giphy 41

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

tenor-59918858

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/245220325).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/245220325).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
