### PR TITLE
deploy scripts should upload to stable

### PR DESCRIPTION
**Pull request by mwrock**
Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by nellshamrell** [comment]
👍

**Comment by reset** [comment]
@mwrock I think we want to deploy to stable only if this is an actual stable build. With this change I think we'll consider things from our `-dev` builds as stable

**Comment by mwrock** [comment]
@reset currently `-dev` merges go to acceptance and prod releases go to prod. So both need to go to stable in their respective depots. I think that now that we have channels, moving from acceptance to prod/unstable might be better but I think that is a separate change.

**Comment by reset** [comment]
@mwrock Ah I see, ya we should make a separate change for it but that's the right move IMO

**Comment by reset** [comment]
tenor-174201456

**Pull request merged**
