### PR TITLE
Run terraform fmt on :allthethings:

### PR DESCRIPTION
**Pull request by jtimberman**
Signed-off-by: jtimberman <joshua@chef.io>

### CODE REVIEW

**Comment by reset** [comment]
@jtimberman nevermind, I see it here now ;)

gif-keyboard-9308361575855261163

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit bc6a9fc has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit bc6a9fc with merge bc6a9fc...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/140631166)

**Pull request merged**
