### PR TITLE
Upgrade builder-web to Angular 4, TypeScript 2

### PR DESCRIPTION
**Pull request by cnunciato**
* Upgrade Angular, TypeScript and related JS dependencies
* Remove references to format-js (since tsfmt is no longer there)
* Re-shrinkwrap

This looks like a lot, but it's mainly just getting packages updated and lined up correctly, pulling component declarations out of components and into the main app module, and changing the way inputs are declared. With the TypeScript update, we're also able to remove Typings (definitions are now retrieved from NPM).

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
This looks great to me, once travis passes.

**Comment by reset** [comment]
gif-keyboard-12925990477429605347

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by cnunciato** [comment]
Fixes #2072

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/220671276).

**Comment by thesentinels** [comment]
:broken_heart: Travis CI reports [this PR failed to pass the test suite](https://travis-ci.org/habitat-sh/habitat/builds/220671276).

The next step is to examine the [job](https://travis-ci.org/habitat-sh/habitat/builds/220671276) and figure out why. If it is transient, you can try re-triggering the Travis CI Job - if it passes, this PR will be automatically merged. If it is not transient, you should fix the issue and update this pull request, and issue `approve` again. If you believe it will never pass, and you are feeling :godmode:, you can issue a `force` to merge this PR anyway.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/220671276).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/220671276).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
