### PR TITLE
Make builder-api tests more resilient

### PR DESCRIPTION
**Pull request by adamhjk**
This commit makes the builder-api tests watch for a message from each
service announcing it is ready to receive traffic. Additionally:

* It makes database creation idempotent
* Adds typescript linting
* Adds the 'tags' file to .gitignore

tl;dr, there is less of this:

gif-keyboard-11913720119311690148

and more of this:

gif-keyboard-7960746830611015954

Signed-off-by: Adam Jacob <adam@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by nellshamrell** [comment]
@thesentinels approve

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/221114936).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/221114936).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
