### PR TITLE
www updates - add forums link, diagrams link, docs title links

### LINKED ISSUE #4697: Add forum links to community page
We would like to promote the forum more prominently on the community page in the hero section.

### PR DESCRIPTION
**Pull request by ryankeairns**
Fixes #4697 #4693 #4679 

- Adds forums link as main CTA on community page
- Moves slack to tertiary CTA on community page
- Updates footer to promote forums link
- Fixes community events to be equal height boxes
- Adds callout graphic on Learn page to promote infographics
- Makes parent links clickable in the docs sidebar

screenshot 2018-03-02 12 59 05

screenshot 2018-03-02 13 00 40

screenshot 2018-03-02 12 58 36

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by ryankeairns** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/348370584).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/348370584).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by tashimi** [comment]
tenor-14513661

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/348386402).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/348386402).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
