### PR TITLE
Corrects a handful of typos and bad links

### PR DESCRIPTION
**Pull request by cwebberOps**
Signed-off-by: Christopher Webber <cwebber@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @Padgett, @magwalk, @smith, @TrevorBramble and @ryankeairns to be potential reviewers

**Comment by cwebberOps** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 6f78225 has been approved by `cwebberOps`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 6f78225 with merge cc453ca...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26804309)

**Pull request merged**
