### PR TITLE
Update copyright date to 2019

### PR DESCRIPTION
**Pull request by qubitrenegade**
48 of places where Copyright was specified as 2016.  This updates it to 2019.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by baumanj** [comment]
Thanks for the submission, @qubitrenegade! We're going to check with legal to see if we can omit this boilerplate since it requires regular maintenance and distracts from the doc comments by introducing a lot of noise. We'll check back here when we have that sorted out.

**Comment by qubitrenegade** [comment]
Thanks @baumanj.

@christophermaier had called it out in the other PR so I figured just hit
'em all at once :)

**Comment by christophermaier** [comment]
@qubitrenegade Haven't heard back from legal yet. Regardless of what they say, though, I think we're going to have follow-on work to do. In the interest of keeping the number of PRs in flight down, I'm going to go ahead and close this for now. 

We do appreciate your contribution and attention to detail, though! ❤️

**Comment by qubitrenegade** [comment]
Haha, no worries.  You started it :wink:

**Pull request closed without merging**
