### PR TITLE
Add clippy support and fix all clippy warnings on components/hab

### PR DESCRIPTION
**Pull request by vegai**
- Adds "make lint" that runs clippy on everything via cargo --features clippy
- Adds relevant Cargo.toml changes for all projects
- Fixes all clippy warnings on components/hab

components/hab passes default clippy set after these changes.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by chefsalim** [comment]
Looks great - thanks for the contribution!

Would you mind re-basing for the merge conflict, and also consider squashing the commits into one?

**Comment by vegai** [comment]
Will do.

**Comment by vegai** [comment]
Non-rebase master merges screwed things up enough that I judged it a better idea to start over :)

**Pull request closed without merging**
