### PR TITLE
Various origins UI fixes

### LINKED ISSUE #3315: CSS, JS and layout cleanup in the Origins section
A number of little things need further tidying up here:

* [x] Packages list design should match the mocks
* [x] Keys tab should match the mocks
* [x] Members tab should match the mocks
* [x] Dialog styles (keys, Docker creds) should match the mocks
* [x] Invite-acceptance UI is unbroken
* [x] Add Montserrat font for tab labels
* [x] Spacing in page headings needs tightening
* [x] We don't need to be fetching the list of projects for every package in an origin anymore
* [x] Hide download icon for private keys
* [x] There's no longer a sidebar on most tabs
* [x] Add a config entry for the demo app URL
* [x] Remove the Docker bits from the plan-linkage component
* [x] Remove unused package-info component

### PR DESCRIPTION
**Pull request by cnunciato**
This addresses a number of visual issues in the Origins section:

* Makes packages list, keys tab, member tab, dialog styles and tab labels all now match the mocks
* Fixes the invite-acceptance layout
* Adds Montserrat font for use with tab labels and other headings
* Removes the fetching of projects for every package in an origin
* Hided download icons for private keys
* Removes the sidebar from most tabs
* Adds a config entry for the demo app URL
* Removes the Docker bits from the plan-linkage component
* Removes unused package-info component

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

Fixes #3315 and #3264.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@cnunciato I love the video of the changes. So nice!

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by reset** [comment]
tenor-159420503

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/280088349).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/280088349).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
