### PR TITLE
Initial ARM Platform Targets

### PR DESCRIPTION
**Pull request by predominant**

### CODE REVIEW

**Comment by dmccown** [comment]
Thank you for your submission @predominant! I’d like to learn more about what you’re exploring with the ARM platform.

We should take a deeper look at what our future may be on the ARM platform. Would you be willing to help write up a design proposal for support ARM? Here’s a template that you may follow https://github.com/chef/chef-oss-practices/blob/bc374ecaa5d0236f8dde3e92dfa5964bac43e2e5/contributors/guide/design-proposals.md.

I’d love to get your context as well as give our community a chance to weigh in on what adding ARM as a support platform may look like.

**Comment by predominant** [comment]
I'm very interested in ARM support. My intention here was to include these platform identifiers to allow arm builds and for arm packages to be built. This doesn't immediately require ARM support on public builder, nor does it immediately require an ARM build (or builds) to be published for public download. It would initially just permit builds on those platforms to create packages and run the binary having built it themselves. In particular for:

* armv6-gnuaebi (arm-linux)
* armv7-gnueabi (armv7-linux)
* aarch64 (aarch64-linux)

I've done a build with these modifications myself,  and set `BUILD_PKG_TARGET=arm-linux`,  and have produced a binary that I can use on armv6 (raspberry pi zero).

While this is a good first step, I believe there are other considerations with regards to allowing a package to build and install on the platform. So this PR hopefully prompts the feedback I need to complete that.

I'm hoping for:

* Acceptance to include these architectures
* Guidance on any other changes required to complete arm compatibility.

I'm not necessarily looking for:

* CI for ARM (yet)
* Chef-supported ARM builds
* Builder support for ARM packages

**Comment by dmccown** [comment]
@predominant Sorry for taking so long to get back to you, we are working on getting you the guidance that you asked for. We should have some answers for you next week. Thank you again for your patience!

**Comment by predominant** [comment]
thanks @dmccown looking forward to it.

**Comment by dmccown** [comment]
@predominant Thanks again for your patience on this. We have #6899 in flight to add the ability to make new unsupported platform targets. This should enable experimentation with a clearer support policy. We will also being some work to create a supported platform matrix to set proper expectations with the supported capabilities on each platform.

**Comment by davidMcneil** [comment]
Closing in favor of #6862

**Comment by predominant** [comment]
For anyone that searches this. Due to the toolchain required to build Habitat, ARM is not supported: https://rust-lang.github.io/rustup-components-history/arm-unknown-linux-gnueabi.html

**Pull request closed without merging**
