### PR TITLE
Add comment about SSL ciphers on ELB

### PR DESCRIPTION
**Pull request by smith**
gif-keyboard-12199724015729907066

(See hashicorp/terraform#5637 for the pull request referenced in the comment.)

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @reset to be a potential reviewer

**Comment by adamhjk** [comment]
gif-keyboard-14470833452978696340

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit c583c9b has been approved by `adamhjk`

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139912429)

**Pull request merged**
