### PR TITLE
add blog post for release 0.76

### PR DESCRIPTION
**Pull request by mpeck**
Signed-off-by: Matthew Peck <mpeck@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mpeck** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
Hey, @mpeck - you don't have permission to issue `deploy` on this pull request.

Nope

**Comment by smacfarlane** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/500003984).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/500003984).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
