### PR TITLE
Adds a valid robots.txt file

### PR DESCRIPTION
**Pull request by cwebberOps**
Signed-off-by: Christopher Webber <cwebber@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by fnichol** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit eca2fae has been approved by `fnichol`

**Comment by thesentinels** [comment]
:hourglass: Testing commit eca2fae with merge 772fe8d...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26782190)

**Pull request merged**
