### PR TITLE
Remove hab-director component

### PR DESCRIPTION
**Pull request by reset**
It's a large part of Habitat's vision for it's supervisor to run
multiple services but, at launch, we were unable to deliver this
functionality in time. The best version of the feature was on the
chopping block because it would have required considerable refactoring
to the supervisor's codebase but it was important to the team to
communicate to our new user base that this was an intended use case
for Habitat's runtime.

We decided to create the Director as a stop-gap measure which would be
replaced after we were able to refactor the supervisor to a place where
it could host multiple services. Because of how quickly the Director
was pieced together, like any project, it suffered in quality. We are
nearly ready to begin work on the final pieces of the supervisor to make
it multi-tenant so we're removing the Director from the codebase and
documentation. We feel it's important to do so before the supervisor
support is ready because while the Directory conveys our intentions, it
doesn't meet the minimum requirements to be a useful component in the
Habitat toolchain and causes more confusion and harm than good.

We look forward to delivering multi-tenant support in the supervisor
in the very near future!

gif-keyboard-9851521941844321762

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by smurawski** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/193470382).

**Comment by elliott-davis** [comment]
gif-keyboard-14792745575086463909

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/193470382).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/193470382).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by adamhjk** [comment]
gif-keyboard-17745085576422111518

**Comment by metadave** [comment]
> Because of how quickly the Director was pieced together, like any project, it suffered in quality

bummer

**Comment by themightychris** [comment]
Does the supervisor have this capability yet? I've been watching the change logs since director got removed and haven't been able to find the replacement yet, am I missing it?

**Pull request merged**
