### PR TITLE
More logo cleanup

### PR DESCRIPTION
**Pull request by cnunciato**
This removes the Habitat mark symbol in a number of decorative graphics.

Signed-off-by: Christian Nunciato <chris@nunciato.org>

To view the side-by-sides, click the

image

icon alongside each image in the Files Changed tab.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
Oh, thanks! I completely missed that. Will fix.

**Comment by cnunciato** [comment]
@apriofrost Ok! Should be good now.

**Comment by apriofrost** [comment]
@cnunciato I just noticed there are two logo marks on the cat's pants in `www/source/blog/media/2017-10-09-Habitat-Builder-for-the-People/banner.png`

**Comment by cnunciato** [comment]
@apriofrost Aha, good eye! Fixed.

**Pull request merged**
