### PR TITLE
Hook up the "Request New Build" button

### PR DESCRIPTION
**Pull request by raskchanky**
So this is _sort of_ working.

I've wired up the button and when you click it, it makes the correct API call.  However, there are a few issues with what's here right now:

1. The build doesn't actually succeed because no project has been created for the package in question. It sounds like this is a known issue, see https://github.com/habitat-sh/habitat/issues/2357 and https://github.com/habitat-sh/habitat/issues/2411.

I'm not 100% sure how we should proceed with this for right now, and am open to suggestions.

2.  The styling of this looks beyond horrible right now and is completely unacceptable in its current state.  I made an effort to make it look good, but after working on it for awhile thought maybe @cnunciato would be able to do it in less time.

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
This should be good to go.

**Comment by cnunciato** [comment]
Closes #2412.

**Comment by raskchanky** [comment]
tenor-105629818

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/234192982).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/234192982).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
