### PR TITLE
Use channels in hab-plan-build

### PR DESCRIPTION
**Pull request by chefsalim**
This change adds channel integration functionality to hab-plan-build.

Note: this change depends on the hab cli support for channels - specifically, 'hab pkg install' should support the '--channels' option.

Signed-off-by: Salim Alam <salam@chef.io>

tenor-123170093

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
tenor-213516197

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/248121909).

**Comment by thesentinels** [comment]
:broken_heart: Travis CI reports [this PR failed to pass the test suite](https://travis-ci.org/habitat-sh/habitat/builds/248121909).

The next step is to examine the [job](https://travis-ci.org/habitat-sh/habitat/builds/248121909) and figure out why. If it is transient, you can try re-triggering the Travis CI Job - if it passes, this PR will be automatically merged. If it is not transient, you should fix the issue and update this pull request, and issue `approve` again. If you believe it will never pass, and you are feeling :godmode:, you can issue a `force` to merge this PR anyway.

**Pull request merged**
