### PR TITLE
migrate DEBUG env var to docker studio

### PR DESCRIPTION
**Pull request by mwrock**
Signed-off-by: mwrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
Whoops, forgot that one, agreed

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
Sorry; I had a problem testing this pull request. The error was:

```ruby
Expected process to exit with [0], but received '128'
---- Begin output of git reset --hard 2771b05e27d9f8f261bb0a95793cfc9dd77646f5 ----
STDOUT: 
STDERR: error: unable to create file www/source/tutorials/sample-app/mac/build-package.html.slim: No space left on device
error: unable to create file www/source/tutorials/sample-app/mac/index.html.slim: No space left on device
error: unable to create file www/source/tutorials/sample-app/mac/run-app.html.slim: No space left on device
error: unable to create file www/source/tutorials/sample-app/mac/update-app.html.slim: No space left on device
error: unable to create file www/source/tutorials/sample-app/mac/upload-package.html.slim: No space left on device
error: unable to create file www/source/tutorials/sample-app/next-steps.html.slim: No space left on device
fatal: cannot create directory at 'www/source/tutorials/sample-app/windows': No space left on device
---- End output of git reset --hard 2771b05e27d9f8f261bb0a95793cfc9dd77646f5 ----
Ran git reset --hard 2771b05e27d9f8f261bb0a95793cfc9dd77646f5 returned 128
```

Oops

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
Sorry; I had a problem testing this pull request. The error was:

```ruby
Expected process to exit with [0], but received '128'
---- Begin output of git fetch origin pull/4383/merge ----
STDOUT: 
STDERR: Warning: Permanently added 'github.com,192.30.255.113' (RSA) to the list of known hosts.
error: unable to create temporary file: No space left on device
fatal: failed to write object
fatal: unpack-objects failed
---- End output of git fetch origin pull/4383/merge ----
Ran git fetch origin pull/4383/merge returned 128
```

Oops

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
Sorry; I had a problem testing this pull request. The error was:

```ruby
Expected process to exit with [0], but received '128'
---- Begin output of git checkout master ----
STDOUT: 
STDERR: fatal: Unable to create '/mnt/hab/svc/sentinel/data/habitat/.git/index.lock': No space left on device
---- End output of git checkout master ----
Ran git checkout master returned 128
```

Oops

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/320500169).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/320500169).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
