### PR TITLE
Lint builder-web with Codelyzer

### LINKED ISSUE #886: [builder-web] Lint Angular code with codelyzer
## The Story

As a Habitat engineer, I would like to have my code linted according to the Angular 2 style guide, so I can have easier to understand code.
## Description

Angular 2 has published a style guide (https://angular.io/styleguide), and a tool for linting according to that style guide (https://www.npmjs.com/package/codelyzer.) We should start following these guidelines where appropriate and using codelyzer in the lint process.
## Acceptance Criteria
- `npm run lint` uses a form of the recommended configuration for codelyzer
- The app works

### PR DESCRIPTION
**Pull request by cnunciato**
Adds and implements Codelyzer. (Fixes #886.)

The main things we're doing here are:

* Prefixing remaining element names with `hab-` (many already are)
* Applying some ordering rules for component definitions (private members follow public ones)
* Exposing the methods used by templates publicly

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
Awesome!

**Comment by adamhjk** [comment]
This looks sane to me.

gif-keyboard-3208576146167984073

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/221411414).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/221411414).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
