### PR TITLE
Build 0.29.0

### PR DESCRIPTION
**Pull request by mgamini**
Signed-off-by: Garrett Amini <garrett@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
tenor-119124408

**Comment by mwrock** [comment]
@thesentinels force

**Comment by thesentinels** [comment]
Excellent @mwrock! It always makes me feel nice when humans approve of one anothers work, no matter the consequences. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
