### PR TITLE
Add dependency resolution for windows

### PR DESCRIPTION
**Pull request by mwrock**
Adding logic to resolve package dependencies on windows and `expose a Get-HabPackagePath` function as the direct bash equivalent of `hab_pkg_for`.

This also provides the same conflict detection provided by the bash build and renders a dependency tree with the offending packages:

```
 mwrock/mytutorialapp/0.2.0/20170111170302
    core/dotnet-core/1.0.0-preview3-003930/20170104163602 (*)
    core/powershell/6.0.0-alpha.14/20170111165932
        core/dotnet-core/1.0.0-preview3-003930/20170104174027 (*)
```

Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
This is now successfully catching package conflicts and rendering the graph. So just need to clean this up now.

**Comment by reset** [comment]
@thesentinels approve

gif-keyboard-1358920729867271779

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/191734537).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/191734537).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
