### PR TITLE
Start working on projects front end

### PR DESCRIPTION
**Pull request by smith**
* Add help for name format
* Fetch origins on load
* Create project on server
* Format project data for server upload

### CODE REVIEW

**Comment by smith** [comment]
gif-keyboard-11132761733730594836

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 97506ab has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 97506ab with merge d6edd75...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/147591517)

**Pull request merged**
