### PR TITLE
Add plan for relx

### PR DESCRIPTION
**Pull request by elliott-davis**
* Note - this is blocked by the PR #921

Signed-off-by: Elliott Davis <edavis@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by metadave** [comment]
@thesentinels delegate=elliott-davis

I'm delegating merge access to you, please read [these instructions](https://github.com/habitat-sh/habitat#delegating-pull-request-merge-access) for more info!

**Comment by thesentinels** [comment]
:v: @elliott-davis can now approve this pull request

**Comment by elliott-davis** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit afe0c4f has been approved by `elliott-davis`

**Comment by thesentinels** [comment]
:hourglass: Testing commit afe0c4f with merge 0189b5b...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/141369357)

**Comment by smith** [comment]
Built and uploaded to depot https://app.habitat.sh/#/pkgs/core/relx/3.19.0/20160630161023

**Pull request merged**
