### PR TITLE
Display private key names on the origin page.

### PR DESCRIPTION
**Pull request by raskchanky**
The overall goal here is to be able to show the user the name of a private key, if one exists, when they view the "keys" tab on the origin detail page.  That way, they know whether or not they're going to overwrite an existing key before they upload a new one.

There are two pieces to this change:

First, the protobuf representation of an Origin has been modified to include a private key name.  For reasons that are not clear to me, re-generating the rust code from the protobuf definitions included a lot of noise that appears to be unrelated to my change to the Origin definition.  Additionally, the server has been modified to return the private key name as part of the origin, when an origin is fetched.

Second, the front-end has been modified to be aware of the difference between public and private keys, and to look for the private key name on an origin when one is fetched.  If one is detected, it's displayed to the user, but is not available for download.

gif-keyboard-16776574348754348545

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@raskchanky Looks solid! Great work here ;)

gif-keyboard-891339900840447680

This will only work for newly uploaded private keys. We might need a way to retroactively go through and populate the OriginKeyName index, but I think this is good enough to merge for now!

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/168495176).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/168495176).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
