### PR TITLE
Fix clippy warnings on components/core

### PR DESCRIPTION
**Pull request by vegai**
doc_markdown fixes
Fix needless_returns
Replace potentially confusing if tree with match (also fixes collapsible_if)
Fix unneeded_fields
Fix redundant_closures
Fix needless_borrows
Fix let_unit_values
Fix absurd extreme comparisons
Fix needless_pass_by_values
Fix needless bools
Fix needless_borrows
Fix a needless borrow and needless format!s to to_owned
Fix match_same_arms
Fix single_matches
Fix single_char patterns
Fix or_fun_calls
Fix explicit_iter_loops
Fix len_zero
Fix ptr_args
Remove unneeded clones (fixes clone double ref)
Allow ifs_same_cond in target.rs
Fix single_char_pattern
Fix redundant closures

Signed-off-by: Vesa Kaihlavirta <vk@discord.tech>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
There's quite a number of build failures in the cleanup here but we'd love to pass clippy's warnings for sure. @vegai did you still want to see this one through?

**Comment by reset** [comment]
Closing this one out for now: @vegai please feel free to re-open if you want to carry this across the finish line!

**Comment by vegai** [comment]
Ah, got a bit overwhelmed with things to do. I'll gladly try to bring this home.

**Comment by vegai** [comment]
I did a rebase, and at least the non-clippy build is ok. Clippy itself has some problems currently, though:

```
error[E0463]: can't find crate for `pulldown_cmark`
  --> /home/vegai/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.144/src/lib.rs:55:1
   |
55 | extern crate pulldown_cmark;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

Will have to wait for that to be resolved.

**Comment by vegai** [comment]
I don't seem to have the privileges to re-open this PR.

**Comment by vegai** [comment]
Ran cargo update -p clippy (which fixed a build problem), rebased and refixed.

**Comment by fnichol** [comment]
Hm, I'm seeing the same thing: the "Reopen and comment" button is greyed out with a tooltip saying "The core_clippy_fixes branch was force-pushed or recreated". Would it be possible to try and open a new PR and link back to this one?

**Comment by reset** [comment]
Yeah it looks like we need a new PR opened

**Pull request closed without merging**
