### PR TITLE
[butterfly] Make DatFile write more durable

### PR DESCRIPTION
**Pull request by stevendanna**
This adds two calls to fsync in the DatFile write method:

1) On the temporary file before the rename
2) On the parent directory after the rename

The first fsync is to persist the content of the dat file to disk. I
think this might have prevented of the 0-byte DatFile seen in #5460.

The second fsync is to persist the rename operation to disk. I've
no-oped it on Windows since we found that calling sync_all on a
directory in windows produces an error in
b688d8ae25d9f38b4053fd29372e2733c9254327.

Signed-off-by: Steven Danna <steve@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by stevendanna** [comment]
I haven't been able to confirm that this is the cause of #5460 yet it is a bit tricky to test since (if this is the cause of the failure) it requires us killing/crashing the OS before it has a chance to automatically flush to disk.  Perhaps we could use a FUSE filesystem that injects errors or something.

**Comment by christophermaier** [comment]
@stevendanna Update: the Expeditor failure is a regression around dealing with forks, is currently being worked on, and isn't anything we need to worry about here (as expected).

**Comment by stevendanna** [comment]
Fixed up rust formatting

**Comment by christophermaier** [comment]
@stevendanna Excellent! Thanks again!

**Pull request merged**
