### PR TITLE
Add SQLite support to Python

### PR DESCRIPTION
**Pull request by smith**
Also add a `do_check` (which currently fails because of problems with
SSL) and set some variables correctly.

Add the `pkg_maintainer` and `pkg_description` fields; fix indentation;
put deps on multiple lines and sort them.

gif-keyboard-11227651725138374110

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @fnichol, @jtimberman and @scassiba to be potential reviewers

**Comment by thesentinels** [comment]
:umbrella: The latest upstream changes (presumably #1019) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by reset** [comment]
@thesentinels r+

gif-keyboard-7902167703720575934

**Comment by thesentinels** [comment]
:pushpin: Commit f9e8928 has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit f9e8928 with merge 985b84c...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/141704792)

**Comment by smith** [comment]
[core/python/3.5.2/20160701190748](https://app.habitat.sh/#/pkgs/core/python/3.5.2/20160701190748) has been built and uploaded to the depot. 💖

**Pull request merged**
