### PR TITLE
Fix link to config docs

### PR DESCRIPTION
**Pull request by smith**
gif-keyboard-7068657816007962451

Thanks @walterdolce!

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @cwebberOps and @davidwrede to be potential reviewers

**Comment by davidwrede** [comment]
Thanks for the fix!

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 68b8aba has been approved by `davidwrede`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 68b8aba with merge 903fda7...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139513514)

**Pull request merged**
