### PR TITLE
Adds optimizely snippet to head

### PR DESCRIPTION
**Pull request by ryankeairns**
Going to test some copy changes.

Note: 
A previous attempt at adding Optimizely through Google Tag Manager caused issues since that lodges the script into the body. I've added it directly into the head here (not using GTM) and everything looks 👌 locally.

### CODE REVIEW

**Comment by thesentinels** [comment]
@ryankeairns, thanks for your PR! By analyzing the annotation information on this pull request, we identified @cwebberOps, @TrevorBramble and @magwalk to be potential reviewers

**Comment by reset** [comment]
gif-keyboard-14100617156946726633

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 6f8f19c has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 6f8f19c with merge 35ebdac...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/149588062)

**Pull request merged**
