### PR TITLE
Use protobuf to represent sys information in swim.Service proto

### LINKED ISSUE #2298: sys.ip always reports 127.0.0.1 (when 0.22.* and 0.21.0 supervisors are communicating)
In a template `{{bind.database.first.sys.ip}}` is always reporting `127.0.0.1`. Don't quite know why yet.

### PR DESCRIPTION
**Pull request by reset**
Prior to this change we were serializing a SysInfo struct into
TOML and then passing it across the wire as bytes. This isn't as
resilient to protocol changes as using a protobuf; it's less efficient
and it makes it more difficult to version our protocol in a way to
allow multiple supervisor versions to gossip to each other.

This is a breaking change. A new version of the supervisor will need
to be cut and we must increment the minor version. Previous versions
of the supervisor will not be able to communicate with ones built
after this commit. Fortunately this should stop us from introducing
further breaking changes (with this message at least).

tenor-61960129

Fixes #2298

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

very nice!

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/231030743).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/231030743).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
