### PR TITLE
Add myself as a maintainer

### PR DESCRIPTION
**Pull request by raskchanky**
Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
@raskchanky, thanks for your PR! By analyzing the annotation information on this pull request, we identified @nathenharvey, @fnichol and @bscott to be potential reviewers

**Comment by smith** [comment]
@thesentinels r+

gif-keyboard-4079828513718419627

**Comment by thesentinels** [comment]
:pushpin: Commit 3291024 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 3291024 with merge cbe8c4e...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/148077639)

**Pull request merged**
