### PR TITLE
Add support for deleting project integrations

### LINKED ISSUE #4235: Support deleting project integrations
Currently there is no way to disable a project integration once it's been enabled. We need an API endpoint to correct this and a button in the UI to call it.

### PR DESCRIPTION
**Pull request by cnunciato**
This change allows users to remove existing publish settings Builder UI.

Signed-off-by: Christian Nunciato <chris@nunciato.org>

Fixes #4235.

tenor-16672765

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by chefsalim** [comment]
tenor-263257772

**Comment by chefsalim** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/312751099).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/312751099).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
