### PR TITLE
Remove pkg_expose from census and butterfly rumors

### PR DESCRIPTION
**Pull request by reset**
This is a companion PR for #1712. This removes unused gossiped data and guts what pkg_expose was faking in favor of what pkg_exports is providing 😄 

* Remove `exposes` field from service rumor. Exposed ports are
  now defined and gossiped through a pkg_export
* Remove `ip`, `hostname`, and `port` from service rumor. These
  were left as temporary aliases while finishing up pkg_exports.
  `ip` and `hostname` can be accessed from sys while `port` is
  no longer available by default, and must be exposed as a
  pkg_export and is made available in `cfg` by the alias given
  to the export
* Rename package_ident to pkg on CensusEntry for consistency
* Remove unused `pkg` field from service rumor and rename
  `package_ident` field to `pkg` for consistency
* Bump protobuf dependency and regenerate butterfly protocol files

gif-keyboard-3751860840739127204

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/199062386).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/199062386).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/199062386).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
