### PR TITLE
Show the version in the web app

### PR DESCRIPTION
**Pull request by smith**
So you can see which release of the software you're running.

gif-keyboard-4742568132285133651

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @ryankeairns, @metadave, @reset, @josegonzalez and @adamhjk to be potential reviewers

**Comment by metadave** [comment]
@thesentinels r+

gif-keyboard-17571778669531303580

**Comment by thesentinels** [comment]
:pushpin: Commit d310024 has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit d310024 with merge c90183f...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139858372)

**Pull request merged**
