### PR TITLE
Updated linting rules

### PR DESCRIPTION
**Pull request by elliott-davis**
* Enforces single quotes
* Enforces two spaces
* Adds license header to all ts files

Signed-off-by: Travis Elliott Davis <edavis@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mgamini** [comment]
tenor-152768908

**Comment by raskchanky** [comment]
I'm so glad the quoting bike shed is back!

tenor-268241022

**Comment by fnichol** [comment]
I'm 👎  because this involves a linting decision.

tenor-156910266

tenor-99386839

👍  👍  👍

**Comment by raskchanky** [comment]
I only like double quotes.  Anything else is terrible.

tenor-93863351

**Comment by robbkidd** [comment]
Reduce, Reuse, Recycle. Single quotes consume 50% fewer quotes from our natural quote resources.

**Comment by raskchanky** [comment]
tenor-124415006

**Comment by raskchanky** [comment]
tenor-145397633

**Pull request merged**
