### PR TITLE
Re-add Travis jobs for publishing the website

### PR DESCRIPTION
**Pull request by smacfarlane**
This re-adds the Travis jobs that were responsible for publishing our website and docs as part of a release.  

Signed-off-by: Scott Macfarlane <smacfarlane@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
Is this necessary? @scotthain said we could have a BK pipeline for deploying the web site before the next release, which means we would be adding this just to deploy the web site for the current release, then removing it again before the next release. Why not just manually deploy the web site for the current release?

**Comment by smacfarlane** [comment]
I went this route after a chat with @scotthain that made it sound like moving this to buildkite was going to be more complex and wouldn't be added for a while.   While I'm not opposed to doing it by hand if it's a one-off,  it sounded like it is potentially multiple releases down the road before we'd have this capability back.

**Comment by raskchanky** [comment]
@smacfarlane Makes sense, thanks for clarifying.

**Pull request merged**
