### PR TITLE
[plans] Ruby 2.3.1

### PR DESCRIPTION
**Pull request by smith**
gif-keyboard-11111074038696136836

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @jtimberman and @fnichol to be potential reviewers

**Comment by jtimberman** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit a2c3a75 has been approved by `jtimberman`

**Comment by smith** [comment]
@thesentinels retry

**Comment by thesentinels** [comment]
:hourglass: Testing commit a2c3a75 with merge 78480fd...

**Comment by smith** [comment]
Manually merging.

**Pull request merged**
