### PR TITLE
Add departed state for members

### PR DESCRIPTION
**Pull request by adamhjk**
This PR adds a fourth state for members, 'Departed'. A departed member
is no longer counted as valid for calculating the total population
needed for a quorum.

When a member is marked `Confirmed`, we record the time from the expired
thread. When the expired thread runs, it checks for members whose
departure time has come; and if it has, it sets their health to
`Departed`, removes them from the departure timer, and shares the
rumor.

This commit sets the departure timer at 72 hours, a particularly
conservative number. If an administrator does nothing to bring member
back to life in that timeframe, it will be marked departed
automatically.

TODO:

* Make nodes who are shut-down gracefully try to automatically Depart
  (In Progress)
* Have a command line tool in `hab-butterfly` to manually mark a node as
  Departed
* Automatically depart members if the service group has `Confirmed`
  members, and new members have been added.

Signed-off-by: Adam Jacob <adam@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by adamhjk** [comment]
Ok friends - this is ready for a review and a merge. It is missing documentation, which we should absolutely write before we get the release out the door. But since this is one of the longest-toothed PRs in the universe, it is worth taking.

Note this also stealthily fixes a bug in the launcher, where it wasn't killing services on exit. If we delay merging this too long, that should go as a separate PR against master prior to releasing the launcher to stable.

**Comment by adamhjk** [comment]
tenor-157550614

**Comment by bodymindarts** [comment]
Awesome @adamhjk. Been waiting for this :-). Will try to review ASAP.

**Comment by adamhjk** [comment]
We have a flaky test here for the eventsrv. I worked around it by manually retriggering.

**Comment by reset** [comment]
@adamhjk this is extremely straight forward for the size. It follows the same patterns we already have while adding some new awesome functionality. I'm just gonna go ahead and merge this in. Any comments I have would be around using constants to represent byte counts inside of the dat file module but honestly it doesn't matter ;)

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/254187426).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/254187426).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
