### PR TITLE
Specified required/optional plan settings

### PR DESCRIPTION
**Pull request by davidwrede**
- Added required/optional information for each setting, including when required settings can be optional if certain env vars or callbacks are overridden.

Signed-off-by: David Wrede <dwrede@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @cwebberOps, @smith, @kevindickerson and @juliandunn to be potential reviewers

**Comment by metadave** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit aeea08c has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit aeea08c with merge 7e1639c...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139375707)

**Pull request merged**
