### PR TITLE
[WIP] Update project API on the frontend

### PR DESCRIPTION
**Pull request by raskchanky**
🚧 💀 🔥 🔥 💀 🚧

### CODE REVIEW

**Comment by thesentinels** [comment]
@raskchanky, thanks for your PR! By analyzing the annotation information on this pull request, we identified @smith, @ryankeairns and @metadave to be potential reviewers

**Comment by smith** [comment]
👍 merge when ready!

gif-keyboard-17955638812510858034

**Comment by smith** [comment]
@thesentinels delegate=raskchanky

**Comment by thesentinels** [comment]
:v: @raskchanky can now approve this pull request

**Comment by raskchanky** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 5eaabb9 has been approved by `raskchanky`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 5eaabb9 with merge 08ea351...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/148073484)

**Pull request merged**
