### PR TITLE
[pkg-export-docker] Binlink all binaries in provided packages.

### PR DESCRIPTION
**Pull request by fnichol**
This change will binlink all binaries in all user provided packages when
building the Docker image file system root. This will allow
language-specific Scaffolding-generated process bins to be on `PATH` by
default so that running commands like:

```
docker exec -ti <container_id> myapp-rake db:migrate
```

will work out of the box.

Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
tenor-83066668

**Comment by davidwrede** [comment]
tenor-53033602

**Comment by reset** [comment]
tenor-12691321

**Pull request merged**
