### PR TITLE
pkg-export-k8s: Remove redundant newline filtering code

### PR DESCRIPTION
**Pull request by zeenix**
Instead use the means provided by Handlebars templating language to
achieve the same in the source template itself.

Signed-off-by: Zeeshan Ali <zeeshan@kinvolk.io>

### CODE REVIEW

**Comment by christophermaier** [comment]
Nice!

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/344479236).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/344479236).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
