### PR TITLE
#4718 Cloud Foundry blog post & get started page

### PR DESCRIPTION
**Pull request by mgamini**
tenor-84941999

https://github.com/habitat-sh/habitat/issues/4718

Signed-off-by: Garrett Amini <kadjar@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by tashimi** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/351576740).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/351576740).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by tashimi** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/351581430).

**Comment by tashimi** [comment]
@mgamini could you add the following content, using some of the tiles similar to the /kubernetes page: 

- https://www.starkandwayne.com/blog/habitat-to-cloud-foundry/
- https://www.cbronline.com/enterprise-it/chef-cooks-new-habitat-packaging-apps/
- https://blog.chef.io/2017/10/12/using-habitat-to-build-the-industrial-cloud-at-ge-digital/ 
- https://thenewstack.io/chef-habitat-addresses-issues-moving-containers-production/
- https://www.youtube.com/watch?v=zaKl59hyWys
- https://www.youtube.com/watch?v=F1L3RlNnJqI

**Comment by tashimi** [comment]
tenor-218069722

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/351581430).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by mgamini** [comment]
@tashimi I'll have those done today!

**Pull request merged**
