### PR TITLE
update habitat api.raml

### PR DESCRIPTION
**Pull request by pozsgaic**
Signed-off-by: pozsgaic <pozsgai@progress.com>

### CODE REVIEW

**Comment by mwrock** [comment]
Is there a reason why we are changing `name` to `svc` and `organization` to `org`? I thing `organization` and `name` are more clear. Also I was curious about the `/metrics` end point because I wasn't familiar with it. I just viewed it on a locally running supervisor and it looks like internal metrics only of interest internally. Not a huge deal if we make it public but I'm just wondering if this PR is really necessary.

**Comment by pozsgaic** [comment]
If we don't care about the metrics, then sure, we can close it.

**Comment by mwrock** [comment]
We don't really need or even want the placeholder names to match between code and docs. The code variables might be too succinct. I'd go with whatever is most descriptive.

**Comment by pozsgaic** [comment]
Since the metrics is more internal in nature, we will just close this.

**Pull request closed without merging**
