### PR TITLE
Support package promotion in Builder UI

### LINKED ISSUE #4046: [Builder UI] Add promote button to the UI
As a user, I want to promote my latest build artifact from the web UI
so that I don't have to always use the CLI for this step
especially when it was an automated build or build generated from the UI itself.

--------------

### Mockup
🖼 [Promote to stable from Versions tab](https://chef.invisionapp.com/share/6CEFVIATX#/263696522_package_Detail_Version_Build_Promote)

### PR DESCRIPTION
**Pull request by cnunciato**
This change adds a Promote button that allows origin members to promote a release to the stable channel.

Signed-off-by: Christian Nunciato <chris@nunciato.org>

Fixes #4046.

tenor-77832220

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by chefsalim** [comment]
tenor-29006222

**Comment by chefsalim** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/312194920).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/312194920).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
