### PR TITLE
Quoted $studio_config variable #1338

### LINKED ISSUE #1338: Habitat Studio doesn't work on paths with space inside
**What do I want to do:**
I want to create a studio in my *Awesome Directory*.

**What do I expect:**
A studio gets created and I can start building a plan out of my *Awesome Directory*.

**What do I get:**
I get an error:
```
dos@yoga:~/habitat/Awesome Directory$ sudo hab studio new
/hab/pkgs/core/hab-studio/0.10.2/20160930230930/bin/hab-studio: 353: [: /hab/studios/home--dos--habitat--Awesome: unexpected operator
   hab-studio: Creating Studio at /hab/studios/home--dos--habitat--Awesome Directory (default)
/hab/pkgs/core/hab-studio/0.10.2/20160930230930/bin/hab-studio: 392: [: /hab/studios/home--dos--habitat--Awesome: unexpected operator
/hab/pkgs/core/hab-studio/0.10.2/20160930230930/bin/hab-studio: 396: [: /hab/studios/home--dos--habitat--Awesome: unexpected operator
BusyBox v1.24.2 (2016-09-26 15:29:07 UTC) multi-call binary.

Usage: mount [OPTIONS] [-o OPT] DEVICE NODE

Mount a filesystem. Filesystem autodetection requires /proc.

        -a              Mount all filesystems in fstab
        -f              Dry run
        -v              Verbose
        -r              Read-only mount
        -t FSTYPE[,...] Filesystem type(s)
        -T FILE         Read FILE instead of /etc/fstab
        -O OPT          Mount only filesystems with option OPT (-a only)
-o OPT:
        loop            Ignored (loop devices are autodetected)
        [a]sync         Writes are [a]synchronous
        [no]atime       Disable/enable updates to inode access times
        [no]diratime    Disable/enable atime updates to directories
        [no]relatime    Disable/enable atime updates relative to modification time
        [no]dev         (Dis)allow use of special device files
        [no]exec        (Dis)allow use of executable files
        [no]suid        (Dis)allow set-user-id-root programs
        [r]shared       Convert [recursively] to a shared subtree
        [r]slave        Convert [recursively] to a slave subtree
        [r]private      Convert [recursively] to a private subtree
        [un]bindable    Make mount point [un]able to be bind mounted
        [r]bind         Bind a file or directory [recursively] to another location
        move            Relocate an existing mount point
        remount         Remount a mounted filesystem, changing flags
        ro              Same as -r

There are filesystem-specific -o flags.
dos@yoga:~/habitat/Awesome Directory$
```
So there is no studio and it makes me sad :(

**Potential culpit:**
The variable `$studio_config` in *hab-studio* bash script is used without quotes, so when bash expands it, it treats paths with spaces as multiple arguments.

**Operating system:**
Observed on Arch Linux, Debian GNU/Linux Sid and Ubuntu 16.04

### PR DESCRIPTION
**Pull request by Albibek**
Hi. 
This should fix #1338.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by eeyun** [comment]
@Albibek Thank you so much for your commit its definitely appreciate,
In order for us to consider merging we will need you to amend your commit to sign the DCO. You can read about that [here](https://github.com/habitat-sh/habitat/blob/a37acc7d1ee4db06a086f4e4f03dbb2fe67e88c4/README.md#signing-your-commits)

Essentially we'll need you to  `git commit --amend -s ` and push that up to your branch

**Comment by Albibek** [comment]
Done

**Comment by eeyun** [comment]
Alt Text

**Comment by smurawski** [comment]
Hey @Albibek - thanks for the contribution.  I'd like to merge your commit, but there are a couple of extraneous commits in this PR.  If you could clean it up with 

```
git remote add upstream https://github.com/habitat-sh/habitat.git
git fetch upstream
git reset upstream/master
git add components/studio/bin/hab-studio.sh
git commit -m 'Quoted $studio_config variable #1338' -s
git push origin master --force
```

What this will do is reset your starting point to the current state of the Habitat repository and unstage your change.  Then we'll add it back with `git add`, commit it with the DCO signoff, and push it back to your master branch.  What we should end up with is that this PR has one commit with your change and the signoff message in the commit message.

If that's a bit much, we can take the commit with the change and I can signoff for you (with your permission in a comment).

In either case, your change will be accepted, it'll mostly impact the "look" of this PR (closed vs. merged).

**Comment by Albibek** [comment]
Dat git was harder than fixing the script itself :)

**Comment by smurawski** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/168978465).

**Comment by smurawski** [comment]
@Albibek Git can be "fun". :)  Thanks for taking those steps and for your contribution!

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/168978465).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by Albibek** [comment]
You're welcome.
I still wonder how could I test this fix by myself. I've found I have to build core/hab-studio package, even built it, but didn't manage to gind a way to install it properly without pushing to some core repo.

**Pull request merged**
