### PR TITLE
Add lower latin/roman list styling

### PR DESCRIPTION
**Pull request by TrevorBramble**
Used by Terms & Conditions.

Signed-off-by: Trevor Bramble <tbramble@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @ryankeairns, @cwebberOps and @magwalk to be potential reviewers

**Comment by cwebberOps** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 015e2ca has been approved by `cwebberOps`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 015e2ca with merge a004c17...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26782921)

**Pull request merged**
