### PR TITLE
determine package tdeps before opening depot client

### PR DESCRIPTION
**Pull request by mwrock**
We currently:
1. Open a depot client
2. Upload the public origin key
3. Check TDEPS
4. Upload package via above client

If you have a large package (mine was 465MB), it can take a long time to extract the TDEPS from the hart. I observed that subsequent calls to the depot client were receiving `connection closed` errors. This is likely due to holding open an inactive connection for several seconds.

This PR pulls out the TDEPS early before any connection is made.

Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/196087160).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/196087160).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
