### PR TITLE
`supportbundle` hab subcommand

### PR DESCRIPTION
**Pull request by jeremymv2**
## Description 🔩 
This PR will take care of #3168 by adding a new `hab` subcommand named `supportbundle` that will generate a tarball of the supervisor data from the filesystem.

## Running it/Demo 👟 
The following is a local dev test, running the compiled `hab` binary with the changes when:
 * a 0.55.0 supervisor is running
 * a 0.56.0 supervisor is running with one service loaded

```
# 0.55.0

root@e3a5599f2253:/src/components/hab# hab sup run &
[1] 11092
root@e3a5599f2253:/src/components/hab# ∵ Missing package for core/hab-sup/0.55.0
» Installing core/hab-sup/0.55.0 from channel 'stable'
☛ Verifying core/hab-sup/0.55.0/20180321222338
→ Using core/busybox-static/1.24.2/20170513215502
☛ Verifying core/bzip2/1.0.6/20170513212938
☛ Verifying core/cacerts/2017.09.20/20171014212239
☛ Verifying core/gcc-libs/5.2.0/20170513212920
☛ Verifying core/glibc/2.22/20170513201042
☛ Verifying core/libarchive/3.3.2/20171018164107
☛ Verifying core/libsodium/1.0.13/20170905223149
☛ Verifying core/linux-headers/4.3/20170513200956
☛ Verifying core/openssl/1.0.2l/20171014213633
☛ Verifying core/xz/5.2.2/20170513214327
☛ Verifying core/zeromq/4.2.2/20171018132502
☛ Verifying core/zlib/1.2.8/20170513201911
✓ Installed core/bzip2/1.0.6/20170513212938
✓ Installed core/cacerts/2017.09.20/20171014212239
✓ Installed core/gcc-libs/5.2.0/20170513212920
✓ Installed core/glibc/2.22/20170513201042
✓ Installed core/libarchive/3.3.2/20171018164107
✓ Installed core/libsodium/1.0.13/20170905223149
✓ Installed core/linux-headers/4.3/20170513200956
✓ Installed core/openssl/1.0.2l/20171014213633
✓ Installed core/xz/5.2.2/20170513214327
✓ Installed core/zeromq/4.2.2/20171018132502
✓ Installed core/zlib/1.2.8/20170513201911
✓ Installed core/hab-sup/0.55.0/20180321222338
★ Install of core/hab-sup/0.55.0/20180321222338 complete with 12 new packages installed.
∵ Missing package for core/hab-launcher
» Installing core/hab-launcher from channel 'stable'
☛ Verifying core/hab-launcher/7611/20180521214042
→ Using core/bzip2/1.0.6/20170513212938
→ Using core/cacerts/2017.09.20/20171014212239
→ Using core/gcc-libs/5.2.0/20170513212920
→ Using core/glibc/2.22/20170513201042
→ Using core/libarchive/3.3.2/20171018164107
→ Using core/libsodium/1.0.13/20170905223149
→ Using core/linux-headers/4.3/20170513200956
→ Using core/openssl/1.0.2l/20171014213633
→ Using core/xz/5.2.2/20170513214327
→ Using core/zlib/1.2.8/20170513201911
✓ Installed core/hab-launcher/7611/20180521214042
★ Install of core/hab-launcher/7611/20180521214042 complete with 1 new packages installed.
hab-sup(MR): Supervisor Member-ID 6b70e41c52674326ae5d87322c7fd6df
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631

root@e3a5599f2253:/src/components/hab# cargo run supportbundle
   Compiling hab v0.0.0 (file:///src/components/hab)
    Finished dev [unoptimized + debuginfo] target(s) in 57.7 secs
     Running `/src/target/debug/hab supportbundle`
☛ Generating New Support Bundle at 2018-06-07 20:38:32
☛ Adding files from /hab/sup
✓ Created /src/components/hab/support-bundle-e3a5599f2253-20180607203832.tar.gz
root@e3a5599f2253:/src/components/hab# tar tzvf /src/components/hab/support-bundle-e3a5599f2253-20180607203832.tar.gz
drwxr-xr-x 0/0               0 2018-06-07 20:37 hab/sup/
drwxr-xr-x 0/0               0 2018-06-07 20:37 hab/sup/default
drwxr-xr-x 0/0               0 2018-06-07 20:37 hab/sup/default/composites
-rw-r--r-- 0/0              32 2018-06-07 20:37 hab/sup/default/MEMBER_ID
drwxr-xr-x 0/0               0 2018-06-07 20:37 hab/sup/default/specs
drwxr-xr-x 0/0               0 2018-06-07 20:38 hab/sup/default/data
-rw-r--r-- 0/0             325 2018-06-07 20:37 hab/sup/default/data/butterfly.dat
-rw-r--r-- 0/0               2 2018-06-07 20:37 hab/sup/default/data/services.dat
-rw-r--r-- 0/0             263 2018-06-07 20:37 hab/sup/default/data/census.dat
-rw-r--r-- 0/0              65 2018-06-07 20:38 hab/sup/default/data/6b70e41c52674326ae5d87322c7fd6df.rst
-rw-r--r-- 0/0               5 2018-06-07 20:37 hab/sup/default/LOCK
root@e3a5599f2253:/src/components/hab# fg
hab sup run
^Chab-launch(SV): Hasta la vista, services.
root@e3a5599f2253:/src/components/hab#

# 0.56.0 

root@e3a5599f2253:/src/components/hab# hab sup run &
[1] 11819
root@e3a5599f2253:/src/components/hab# ∵ Missing package for core/hab-sup/0.56.0
» Installing core/hab-sup/0.56.0
☁ Determining latest version of core/hab-sup/0.56.0 in the 'stable' channel
↓ Downloading core/hab-sup/0.56.0/20180530235935
    2.47 MB / 2.47 MB / [========================================================================================================================================] 100.00 % 11.21 MB/s
☛ Verifying core/hab-sup/0.56.0/20180530235935
→ Using core/busybox-static/1.24.2/20170513215502
→ Using core/bzip2/1.0.6/20170513212938
→ Using core/cacerts/2017.09.20/20171014212239
→ Using core/gcc-libs/5.2.0/20170513212920
→ Using core/glibc/2.22/20170513201042
→ Using core/libarchive/3.3.2/20171018164107
→ Using core/libsodium/1.0.13/20170905223149
→ Using core/linux-headers/4.3/20170513200956
→ Using core/openssl/1.0.2l/20171014213633
→ Using core/xz/5.2.2/20170513214327
↓ Downloading core/zeromq/4.2.5/20180407102804
    594.50 KB / 594.50 KB \ [====================================================================================================================================] 100.00 % 27.71 MB/s
☛ Verifying core/zeromq/4.2.5/20180407102804
→ Using core/zlib/1.2.8/20170513201911
✓ Installed core/zeromq/4.2.5/20180407102804
✓ Installed core/hab-sup/0.56.0/20180530235935
★ Install of core/hab-sup/0.56.0/20180530235935 complete with 2 new packages installed.
hab-sup(MR): Supervisor Member-ID 6b70e41c52674326ae5d87322c7fd6df
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting ctl-gateway on 127.0.0.1:9632
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631

root@e3a5599f2253:/src/components/hab# hab pkg install core/redis -f -b
» Installing core/redis
☁ Determining latest version of core/redis in the 'stable' channel
☛ Verifying core/redis/3.2.4/20170514150022
→ Using core/glibc/2.22/20170513201042
→ Using core/linux-headers/4.3/20170513200956
✓ Installed core/redis/3.2.4/20170514150022
★ Install of core/redis/3.2.4/20170514150022 complete with 1 new packages installed.
» Binlinking redis-server from core/redis/3.2.4/20170514150022 into /bin
★ Binlinked redis-server from core/redis/3.2.4/20170514150022 to /bin/redis-server
» Binlinking redis-benchmark from core/redis/3.2.4/20170514150022 into /bin
★ Binlinked redis-benchmark from core/redis/3.2.4/20170514150022 to /bin/redis-benchmark
» Binlinking redis-check-rdb from core/redis/3.2.4/20170514150022 into /bin
★ Binlinked redis-check-rdb from core/redis/3.2.4/20170514150022 to /bin/redis-check-rdb
» Binlinking redis-cli from core/redis/3.2.4/20170514150022 into /bin
★ Binlinked redis-cli from core/redis/3.2.4/20170514150022 to /bin/redis-cli
» Binlinking redis-sentinel from core/redis/3.2.4/20170514150022 into /bin
★ Binlinked redis-sentinel from core/redis/3.2.4/20170514150022 to /bin/redis-sentinel
» Binlinking redis-check-aof from core/redis/3.2.4/20170514150022 into /bin
★ Binlinked redis-check-aof from core/redis/3.2.4/20170514150022 to /bin/redis-check-aof
root@e3a5599f2253:/src/components/hab# hab svc load core/redis
hab-sup(AG): The core/redis service was successfully loaded
The core/redis service was successfully loaded
root@e3a5599f2253:/src/components/hab# hab-sup(MR): Starting core/redis
redis.default(UCW): Watching user.toml
redis.default(HK): Hooks compiled
default(CF): Updated redis.config 6bc2baadd7c401e96b7cd2609771fabf0fc7254b2f1c4d3ffab75f7d8b3536f9
redis.default(SR): Configuration recompiled
redis.default(SR): Initializing
redis.default(SV): Starting service as user=hab, group=hab
redis.default(O):                 _._
redis.default(O):            _.-``__ ''-._
redis.default(O):       _.-``    `.  `_.  ''-._           Redis 3.2.4 (00000000/0) 64 bit
redis.default(O):   .-`` .-```.  ```\/    _.,_ ''-._
redis.default(O):  (    '      ,       .-`  | `,    )     Running in standalone mode
redis.default(O):  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis.default(O):  |    `-._   `._    /     _.-'    |     PID: 12552
redis.default(O):   `-._    `-._  `-./  _.-'    _.-'
redis.default(O):  |`-._`-._    `-.__.-'    _.-'_.-'|
redis.default(O):  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis.default(O):   `-._    `-._`-.__.-'_.-'    _.-'
redis.default(O):  |`-._`-._    `-.__.-'    _.-'_.-'|
redis.default(O):  |    `-._`-._        _.-'_.-'    |
redis.default(O):   `-._    `-._`-.__.-'_.-'    _.-'
redis.default(O):       `-._    `-.__.-'    _.-'
redis.default(O):           `-._        _.-'
redis.default(O):               `-.__.-'
redis.default(O):
redis.default(O): 12552:M 07 Jun 20:49:24.503 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis.default(O): 12552:M 07 Jun 20:49:24.503 # Server started, Redis version 3.2.4
redis.default(O): 12552:M 07 Jun 20:49:24.503 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis.default(O): 12552:M 07 Jun 20:49:24.503 * The server is now ready to accept connections on port 6379

root@e3a5599f2253:/src/components/hab# cargo run supportbundle
   Compiling hab v0.0.0 (file:///src/components/hab)
    Finished dev [unoptimized + debuginfo] target(s) in 52.2 secs
     Running `/src/target/debug/hab supportbundle`
☛ Generating New Support Bundle at 2018-06-07 20:50:22
☛ Adding files from /hab/sup
✓ Created /src/components/hab/support-bundle-e3a5599f2253-20180607205022.tar.gz
root@e3a5599f2253:/src/components/hab# tar tzvf /src/components/hab/support-bundle-e3a5599f2253-20180607205022.tar.gz
drwxr-xr-x 0/0               0 2018-06-07 20:37 hab/sup/
drwxr-xr-x 0/0               0 2018-06-07 20:39 hab/sup/default
drwxr-xr-x 0/0               0 2018-06-07 20:37 hab/sup/default/composites
-rw-r--r-- 0/0              32 2018-06-07 20:37 hab/sup/default/MEMBER_ID
drwxr-xr-x 0/0               0 2018-06-07 20:49 hab/sup/default/specs
-rw-r--r-- 0/0             200 2018-06-07 20:49 hab/sup/default/specs/redis.spec
drwxr-xr-x 0/0               0 2018-06-07 20:50 hab/sup/default/data
-rw-r--r-- 0/0               1 2018-06-07 20:49 hab/sup/default/data/redis.health
-rw-r--r-- 0/0             832 2018-06-07 20:49 hab/sup/default/data/butterfly.dat
-rw-r--r-- 0/0            3266 2018-06-07 20:49 hab/sup/default/data/services.dat
-rw-r--r-- 0/0            1374 2018-06-07 20:49 hab/sup/default/data/census.dat
-rw-r--r-- 0/0             276 2018-06-07 20:50 hab/sup/default/data/6b70e41c52674326ae5d87322c7fd6df.rst
-rw-r--r-- 0/0               5 2018-06-07 20:39 hab/sup/default/LOCK
-rw------- 0/0              88 2018-06-07 20:39 hab/sup/default/CTL_SECRET
root@e3a5599f2253:/src/components/hab#

```
Signed-off-by: Jeremy J. Miller <jm@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by jeremymv2** [comment]
🤔 the travis test seems to have failed somewhat arbitrarily as this same test passed on the 1st commit 

https://travis-ci.org/habitat-sh/habitat/jobs/389443272#L766

```
---- rumor::election::two_members_find_quorum_when_a_third_comes stdout ----
	Failed election check for status Finished: RumorStore {
    list: RwLock {
        data: {
            "witcher.prod": {
                "election": Election(
                    type: Election
                    from_id: "b47179c8d248434c8e637f8eb96d3f50"
                    election {
                      member_id: "b47179c8d248434c8e637f8eb96d3f50"
                      service_group: "witcher.prod"
                      term: 0
                      suitability: 0
                      status: Running
                      votes: "b47179c8d248434c8e637f8eb96d3f50"
                      votes: "8a4b018e11ba45a98ed96793fec9b9f8"
                      votes: "29f4bdf083de4c4b9562cd1886a2854d"
                    }
                
                )
            }
        }
    },
    update_counter: AtomicUsize(
        3
    )
}
thread 'rumor::election::two_members_find_quorum_when_a_third_comes' panicked at 'assertion failed: net.wait_for_election_status(x, "witcher.prod", Election_Status::Finished)', components/butterfly/tests/rumor/election.rs:72:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I don't seem to have a re-run button, can anyone else re-run it?

**Comment by baumanj** [comment]
I restarted the job. I notice this button doesn't seem to render in Firefox:
screen shot 2018-06-07 at 4 38 05 pm

**Comment by jeremymv2** [comment]
Ah thanks @baumanj!
I think it's still not there for me since I do not have write access on the repo.

**Pull request merged**
