### PR TITLE
Update origin privacy settings

### LINKED ISSUE #3261: UI for setting default package uploads visibility
Add the ability to set the default privacy for .harts uploaded to an origin (to public or private).

This occurs in two places:
1. when creating a new origin - [mockup](https://chef.invisionapp.com/share/3ZBKYLQTW#/249657340_create_Origin_Single_Step)
2. on the Settings tab for an existing origin - [](https://chef.invisionapp.com/share/3ZBKYLQTW#/248931182_origin_Settings_Private_Connected)

@elliott-davis has started the UI work, the remaining work is to verify it works/saves to the backend and then finish aligning the UI to the mockup (Invision links above).

### PR DESCRIPTION
**Pull request by cnunciato**
This change applies the `default_package_visibility` setting exposed in the Origin Settings tab.

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

Fixes #3261.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/280717044).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/280717044).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
