### PR TITLE
Replace node based SHA strategy with sed

### PR DESCRIPTION
**Pull request by raskchanky**
For reasons that are not entirely clear to me, https://github.com/habitat-sh/habitat/commit/767e3b9445164c15cd95a7b3a1042764d2005e61 broke the ability to build a builder-api package.  The process runs fine until this line https://github.com/habitat-sh/habitat/blob/master/components/builder-web/bin/dist#L25  The script referenced in that line _will_ run and it _will_ make the changes, but node itself will never exit - it will hang indefinitely.  Because of that, the build process will never finish.

So instead of using node to parse the DOM in `index.html` and adjust the filenames to include their SHAs, we switch to using sed instead.  Now the package builds fine again.

tumblr_mrnkq6nmy41scwli8o1_400

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by fnichol** [comment]
gif-keyboard-18143766738875893839

Awesome turnaround!

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/180201276).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/180201276).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
