### PR TITLE
Skip auto-update on start for rolling update strategy

### PR DESCRIPTION
**Pull request by reset**
Prior to this commit the supervisor would check for an updated version
of the package being loaded as a service if any update strategy was
specified. This behaviour actually only makes sense for the "at-once"
strategy where services can update independent of each other and should
always be at the latest version of the specified package goal on start.

This commit ensures that service groups implementing the rolling
strategy don't have their packages updated on load and relies on the
coordination of the strategy to ensure the supervisor is running the
correct version of the package.

Signed-off-by: Jamie Winsor <jamie@vialstudios.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
Glad we caught this and it's a much easier fix vs. where the fix would have been prior to #1791

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/202976035).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/202976035).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/202976035).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by reset** [comment]
@fnichol a million times easier to see it and fix it after #1791. This place is looking mighty good after the last few months ;)

**Pull request merged**
