### PR TITLE
Remove eventsrv.

### PR DESCRIPTION
**Pull request by raskchanky**
Eventsrv has grown old and crufty and we're not actually using it in any meaningful fashion. We're going to remove it for now and revisit it at a later date.

Resolves https://github.com/habitat-sh/habitat/issues/5962
Resolves https://github.com/habitat-sh/habitat/issues/6012

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by baumanj** [comment]
Does this resolve both of the following issues?
https://github.com/habitat-sh/habitat/issues/5962
https://github.com/habitat-sh/habitat/issues/6012

We should also review the acceptance criteria for those to be sure.

**Comment by raskchanky** [comment]
@baumanj Yeah I think it does.  I'll review those issues and make the appropriate adjustments here.

**Comment by baumanj** [comment]
Additional lines that can be modified/removed:
- [ ] https://github.com/habitat-sh/habitat/blob/jb/remove-eventsrv/Makefile#L216-L217
- [ ] https://github.com/habitat-sh/habitat/blob/jb/remove-eventsrv/CODEOWNERS#L7
- [ ] Update CLI docs (or just wait for our next release, I guess)

**Comment by raskchanky** [comment]
Appveyor has failed twice in a row due to timeouts.  Travis is passing.  I'm going to merge this.

**Pull request merged**
