### PR TITLE
try the old bots once again :|

### PR DESCRIPTION
**Pull request by smith**
gif-keyboard-1279913398353039856

### CODE REVIEW

**Comment by thesentinels** [comment]
@smith, thanks for your PR! By analyzing the annotation information on this pull request, we identified @fnichol, @adamhjk, @cwebberOps and @reset to be potential reviewers

**Comment by smith** [comment]
@thesentinels try

**Comment by thesentinels** [comment]
:hourglass: Trying commit e5ec612 with merge 0904260...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/146758317)

**Comment by smith** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit e5ec612 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit e5ec612 with merge 8f7985c...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/146760923)

**Pull request merged**
