### PR TITLE
Custom serialization logic for u64

### PR DESCRIPTION
**Pull request by christophermaier**
We were running into issues where u64 values were serializing as JSON
strings and not making it back to u64 when they deserialized. Not
quite sure how this isn't being handled automatically by Rust's type
system, but in any event, we can just plug in our own logic with some
attributes.

Signed-off-by: Christopher Maier <cmaier@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
tenor-73398283

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/226992484).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/226992484).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by smurawski** [comment]
@christophermaier This is awesome!  And could probably move to core or common as the supervisor could use this. We hit similar problems deserializing i64s and u16s.  This is much cleaner than what I played with against the earlier serde versions.

**Comment by christophermaier** [comment]
@smurawski Thanks! Yeah, it seems like this could be broadly applicable. I'm totally open to moving into a core crate; I wanted to make sure the initial brokenness got fixed first before casting a bigger net, though 😄

**Pull request merged**
