### PR TITLE
[core] Update git repo to consume habitat-sh/core#22.

### PR DESCRIPTION
**Pull request by fnichol**
Includes:

* habitat-sh/core#19
* habitat-sh/core#20
* habitat-sh/core#21
* habitat-sh/core#22

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
Hold for a minute--I didn't account for `FS_ROOT` calculation when dropping path entries in the `PATH` metadata file which will require a follow on change in `habitat-sh/core`.

**Comment by fnichol** [comment]
We've found the next issue which is that we need to produce the `PATH` metafile in the PowerShell build program again otherwise Habitat tooling can't find the binary programs in packages (with commands like `hab pkg exec`, `hab pkg binlink`, etc. I'll be preparing a PR against this repo with a build program change and then rebase this on top once merged to confirm we've got it.

**Comment by fnichol** [comment]
tenor-2715323

tenor-93416816

**Pull request merged**
