### PR TITLE
Add documentation on `do_setup_environment` callback

### PR DESCRIPTION
**Pull request by christophermaier**
Adds some official documentation around the runtime environment feature, largely recapitulating info covered in the [blog post](https://www.habitat.sh/blog/2017/11/runtime-environment-variables/) that introduced them.

@davidwrede I'd really appreciate your input on tone, formatting, etc.

Signed-off-by: Christopher Maier <cmaier@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by davidwrede** [comment]
@christophermaier I've got a commit coming with some formatting and copy edit changes.

**Comment by christophermaier** [comment]
@davidwrede your changes are _so_ good, thank you!
tenor-17417890

**Comment by christophermaier** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/312672122).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/312672122).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
