### PR TITLE
Update Contributing.md

### PR DESCRIPTION
**Pull request by tashimi**
- add a table of contents
- adds the topics: 
-- Support Channels
-- Feature Requests
-- Bug Reports
-- Report a security vulnerability
-- Pull Requests
-- Writing Documentation and blogs
-- Issue Triage
-- Related Articles
- highlights code of conduct
- adds ways to contact us 
etc.

Signed-off-by: Tasha Drew <tasha.drew@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by tashimi** [comment]
tenor-25419088

**Comment by tashimi** [comment]
Closes #3011

**Comment by reset** [comment]
@tashimi this is *so much better*

tenor-136436032

**Pull request merged**
