### PR TITLE
[WIP] Adds ant plan

### PR DESCRIPTION
**Pull request by spuder**

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by smith** [comment]
@spuder is this a work in progress? Building the plan did not install `ant` for me. It looks like the `do_build` and `do_install` callbacks don't do anything and I end up with an empty package.

**Comment by spuder** [comment]
I should have put WIP in the description. It needs more validation. 

Ant shouldnt require compilation since it is a jar.

**Comment by spuder** [comment]
I've resolved the empty artifact. 

This works, however it is still not getting JAVA_HOME set correctly. I don't understand habitat environment variables enough yet to know how to fix it. 
```
hab studio -k foobar enter
build
hab pkg install /src/results/foo-bar-1.0.0.-xxxxx.hart
hab pkg exec core/ant ant
Error: JAVA_HOME is not defined correctly.
  We cannot execute java
```

**Comment by smith** [comment]
Closing in favor of #919. Thanks for the work on this one!

**Pull request closed without merging**
