### PR TITLE
Fully serialize the `pkg` field of the Service struct

### LINKED ISSUE #2250: Service config not available via API
Testing out Habitat version `0.22.0/20170506041148` on linux.

Steps to reproduce:

1.  Install hab 0.22.0/20170506041148
2. `$ sudo hab sup run`
3. `$ sudo hab sup load learn/mongodb`
4. Open http://YOUR_IP:9631/services/mongodb/default/config in a web browser.

I expect to see the configuration for the running mongodb service.  Instead, I get a 404 page not found error.

Using curl against the local host yields the same result:

```
$ hab sup status learn/mongodb && curl -I http://localhost:9631/services/mongodb/default/config
hab-sup(MN): The learn/mongodb/3.2.10/20170407074757 service entered the running state with PID: 2422 667 seconds ago.
HTTP/1.1 404 Not Found
Content-Length: 0
Date: Sun, 07 May 2017 15:04:50 GMT

```

census, services, and health endpoints all seem to be working correctly.

### PR DESCRIPTION
**Pull request by reset**
This will serialize the entire contents of the `Pkg` struct instead of just the name of the package

Fixes #2250

tenor-136280610

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

Gonna self merge this since it was a mistake that I made!

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/232013952).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/232013952).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
