### PR TITLE
service_config::toml_merge handles toml::Tables

### PR DESCRIPTION
**Pull request by metadave**
fixes https://github.com/habitat-sh/habitat/issues/1184

### CODE REVIEW

**Comment by thesentinels** [comment]
@metadave, thanks for your PR! By analyzing the annotation information on this pull request, we identified @adamhjk, @fnichol, @reset and @smith to be potential reviewers

**Comment by adamhjk** [comment]
Did this merge correctly? I see a "Closed with unmerged commits" here.

**Comment by robbkidd** [comment]
T'isn't merged.

**Comment by robbkidd** [comment]
I've tinkered with this branch in my dev environment. I've confirmed the tests added in this change fail-as-expected when the old form of the `toml_merge` function is used. And the test failures match what I'm seeing when running a package with nested values and I provide a custom config.

I don't quite know how to wire up running my build of `hab-sup` as the supervisor for that package though because they're in separate repos/working directories/containers.

**Comment by metadave** [comment]
@robbkidd inside the dev-shell:

        /src/target/debug/hab-sup start core/somepackage

**Comment by robbkidd** [comment]
OK. Managed to run a service with `hab-sup` from this branch. I believe the merge is currently overriding in the wrong direction: values from `default.toml` are kept, not the overrides from the environment.

**Comment by robbkidd** [comment]
```

**Comment by robbkidd** [comment]
Now that I'm looking at this again, the two uses of `toml_merge` in the code there have the direction opposite each other.

**Comment by robbkidd** [comment]
Building off of @metadave's work here, I rebased this branch and flipped the order of the params in calls to `toml_merge`. Running my thing with `hab-sup` built from [the new branch](https://github.com/habitat-sh/habitat/compare/master...robbkidd:dp_toml_merge_table_fix) runs with environment values taking precedence over defaults. There's some thoughts about refactoring the implementation of the config merge, but it appears that at least with these two commits the "default values in nested tables disappear when some are overridden" and "config precedence flows in the expected order" issues may be fixed.

**Comment by robbkidd** [comment]
Rebased branch + precedence fix offered for review in #1294

**Comment by metadave** [comment]
thanks @robbkidd, you rock!

**Pull request closed without merging**
