### PR TITLE
Updated Mac instructions for building Hab

### PR DESCRIPTION
**Pull request by jjasghar**
This is from the Community summit updating the Mac instructions.

Signed-off-by: JJ Asghar  <jj@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by eeyun** [comment]
:+1:  Awesome.

**Comment by smurawski** [comment]
@thesentinels  approve

**Comment by bdangit** [comment]
@jj does the rust or cargo version we have allow this to be built under virtual box now?

I had to do some hack in the `Dockerfile` to get this to be built under virtual box.

**Comment by jjasghar** [comment]
Thanks a great question @bdangit. I just leveraged the `make` file to build the containers with the main docker app, and it "just worked" TM.

I've haven't used the VirtualBox workflow since I started with this project. :(

**Pull request merged**
