### PR TITLE
bump rumor incarnation when starting a service already in the census

### LINKED ISSUE #2220: Supervisor needs to be restarted for new or update config files to be rendered
New and updated config files are not being rendered when installing a new version of a hab package (local only, no update strategy) via `hab sup unload` and `hab sup load`.  The workaround so far has been to restart the supervisor entirely.

Steps to reproduce:
1. Load a package which has a config template. `sudo hab sup load myorigin/mypackage`
2. Start the supervisor, `hab sup run`
3. Add a new toml config file to hab package, such as `habitat/config/example.toml`.
4. Build the package.
5. Install the resulting hart package.
6. Without stopping the running supervisor, unload and load your package. `sudo hab sup unload myorigin/mypackage && sudo hab sup load myorigin/mypackage`
7. Look in `/hab/svc/myorigin/mypackage/config` to see if the new toml file is present, if this bug is fixed -- it will be there, otherwise the file will be missing until the running supervisor is stopped and restarted.

- [x] The OS (including version) where you are running any of the Habitat commands.
*Ubuntu 16.04.2*
- [ ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

I am not sure if a backtrace is relevant in this use case since there are many command execution steps involved.

- [X] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

`none`

### PR DESCRIPTION
**Pull request by mwrock**
This fixes #2220. If a service is loaded and later unloaded from the supervisor. It remains in the census and I believe that is corect behavior. However, if the same service is later loaded again after it has been updated manually, the supervisor manager simply adds the service with an incarnation of `1`. This means that its config is not regenerated with any possible updates (there is also the chance that it was manually deleted). Also its census record continues to have its initial version and does not reflect the true version/release.

This will bump the update incarnation when adding a service if it is already in the census and will there fore force a reconfigure causing regenerated configuration if it differs from the existing configuration.

Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

tenor-585376

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/228983000).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/228983000).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
