### PR TITLE
Add a links to the habitat source

### PR DESCRIPTION
**Pull request by josegonzalez**
This adds a link to the footer and to the contribution guide.

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @juliandunn, @magwalk, @cwebberOps, @mattray and @davidwrede to be potential reviewers

**Comment by metadave** [comment]
thanks for the PR @josegonzalez, we'll review shortly

**Comment by smith** [comment]
Thanks for the contribution! If you update based based on my suggestion above we'll get it merged.

You also need to sign off on your commits using `git commit --signoff`, since we use DCO. See https://github.com/habitat-sh/habitat#signing-your-commits. You can add a signoff to an existing commit with `git commit --amend --signoff`.

**Comment by smith** [comment]
@josegonzalez forgot to mention we also maintain the footer in 2 places right now: one for the website and one for the web app.

The source for that is here: https://github.com/habitat-sh/habitat/blob/master/components/builder-web/app/footer/FooterComponent.ts#L34-L39

And there's a `config['source_code_url']` available in that footer. Let me know if you need any help with that.

Thanks again!

**Comment by josegonzalez** [comment]
@smith ping

**Comment by smith** [comment]
@josegonzalez beautiful thank you!

gif-keyboard-5382880686380503314

**Comment by smith** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit e075b01 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit e075b01 with merge c2cac85...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26824845)

**Pull request merged**
