### PR TITLE
Adds blog redirect at top-level and links to each post

### PR DESCRIPTION
**Pull request by eeyun**
As requested by marketing, the habitat engineering blog is getting subsumed by the chef marketing team/blog. This change adds links to each blog post that has been migrated and adds a top-level redirect for the "blog" button on the site to chef marketing blog.

Signed-off-by: Ian Henry <ihenry@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@eeyun What's the timeline on when this should merge?

**Comment by eeyun** [comment]
Honestly I have no idea. Just waiting on marketing to tell us when.

**Comment by raskchanky** [comment]
@dmccown gave me the 👍 to merge this

**Pull request merged**
