### PR TITLE
update docs to specify 64-bit as a requirement for windows

### PR DESCRIPTION
**Pull request by ericcalabretta**
update references to windows 2008r2 or windows 7 to specify 64-bit as a requirement. Windows 2008r2, Windows7, and even windows10 have both 32-bit and 64-bit version. The Habitat supervisor requires 64bit.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by ericcalabretta** [comment]
removed the 64bit text for 2008 R2

**Comment by mwrock** [comment]
Awesome! Can tou fix the DCO on your commit?

**Comment by ericcalabretta** [comment]
added DCO to commit message

**Pull request merged**
