### PR TITLE
First pass at the eventsrv

### PR DESCRIPTION
**Pull request by raskchanky**
This is the first pass at the event service.  It sits in the middle of a zeromq pipeline, listening for events on a PULL socket.  Events are sent to it via a PUSH socket.  It takes whatever messages it receives and sends them out on a separate PUSH socket.  Third parties that are interested in receiving the events can listen on a PULL socket.  Using PUSH/PULL sockets gives us fair queueing when running multiple event services.

Events are sent via protobufs, like the rest of our inter-service communication.

The next step in this work is to integrate it with the supervisor, which will be the event publisher.  It's also worth noting that `client.rs` and `subscriber.rs` are only used for testing/debugging purposes and to show what end-to-end communication looks like.  They're not actually part of the service itself.

One question I have on this - what ports should be used?  The ones in this code I just picked randomly for testing and should probably be changed.

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
This is an awesome starting place. The ports I picked for the rest of the system are pretty random, too.  There's a list of known ports on Wikipedia that I consult with to make sure I'm not picking something that is already super well known, but other than that there isn't much science to it. I think we can defer to another PR to choose what default ports we go with :)

gif-keyboard-9135213190366957361

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/216550889).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/216550889).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by mwrock** [comment]
Just curious why we are storing the protobuf messages in this component and not in `builder-protobuf` with the others?

**Comment by reset** [comment]
@mwrock These aren't specific to builder itself since EventSrv isn't part of builder, but it might be a good idea to keep them there since we're trying to reference some common protocols anyway ;). We could also ultimately depend on builder-protocols and pull in that as a dep

**Comment by mwrock** [comment]
Perhaps we eventually rename `builder-protocol` to just `protocol` or `habitat-protocol`. Its nice to have one component t ohave to think about in terms of compiling the protocols.

**Pull request merged**
