### PR TITLE
Support installing hab with a custom cert

### PR DESCRIPTION
**Pull request by bdangit**
This change allows a user to setup environment var SSL_CERT_FILE.

```
env SSL_CERT_FILE=/path/to/pem ./install.sh
```

Signed-off-by: Ben Dang <me@bdang.it>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by bdangit** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
Hey, @bdangit - you don't have permission to issue `deploy` on this pull request.

Nope

**Comment by bdangit** [comment]
is there any way I can rerun the tests again?  The error appears completely unrelated to any of the code I have modified.

**Comment by reset** [comment]
@thesentinels approve

tenor-253615768

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/244741719).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/244741719).

**Comment by thesentinels** [comment]
:broken_heart: Travis CI reports [this PR failed to pass the test suite](https://travis-ci.org/habitat-sh/habitat/builds/244741719).

The next step is to examine the [job](https://travis-ci.org/habitat-sh/habitat/builds/244741719) and figure out why. If it is transient, you can try re-triggering the Travis CI Job - if it passes, this PR will be automatically merged. If it is not transient, you should fix the issue and update this pull request, and issue `approve` again. If you believe it will never pass, and you are feeling :godmode:, you can issue a `force` to merge this PR anyway.

**Pull request merged**
