### PR TITLE
captures standard error of supervisor child process and reads it to the output

### LINKED ISSUE #2395: Supervisor creates pipe for service `stderr` stream but does not consume it.
In our child forking code, on Linux, we setup a pipe for `stderr` (https://github.com/habitat-sh/habitat/blob/301eb15e7f490a449988e04a5b7fc6f67109e4f1/components/sup/src/manager/service/exec.rs#L52) but we don't consume it in `service::supervisor::read_child` (https://github.com/habitat-sh/habitat/blob/301eb15e7f490a449988e04a5b7fc6f67109e4f1/components/sup/src/manager/service/supervisor.rs#L261).

At a minimum we should drop the pipe creation which would send the `stderr` stream to `/dev/null` before we come up with an intermediate solution. Ultimately I'd like to see us handle both `stdout` and `stderr` streams discretely but we should prevent this pipe creation in the meantime. If a hook is printing to `stderr`, eventually the buffer for this pipe is filled (as it is not drained) and any process that attempts to write to it will eventually block and sleep.

### PR DESCRIPTION
**Pull request by mwrock**
This fixes #2395 and outputs a supervisor's child service process standard error to the console.

Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
tenor-210901898

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/237989123).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/237989123).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/237989123).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
