### PR TITLE
Show build log output in the UI

### LINKED ISSUE #2183: [builder-web] Show build output from streaming logs
Streaming log output should be included in the builder-web UI so users can see the status of their builds.

This is a "current job view" that shows streaming log output when you click on an origin/package for more information. It includes information such as: 
- time running
- time completed 
- authored by 
- etc.

### PR DESCRIPTION
**Pull request by cnunciato**
This adds a couple of new views to support showing build output in the UI, and removes some demo/placeholder code that had been written in anticipation of the feature. Currently supports only the core origin.

Closes #2183. Depends on #2241.

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
onuglg0

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/230931949).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/230931949).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
