### PR TITLE
fixes #2701 making hab pkg build -w work on windows

### LINKED ISSUE #2701: HAB_WINDOWS_STUDIO ignored in windows studio v25.0
It looks something broken in version 25:0

```powershell
$env:HAB_WINDOWS_STUDIO=1
cd /path/to/windows/plan
hab pkg build .
```

```powershell
✗✗✗
✗✗✗ `docker' was not found on the filesystem or in PATH
✗✗✗
```

### PR DESCRIPTION
**Pull request by mwrock**
This passes `-w` from `hab pkg build` to the studio call

Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

tenor-112864107

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/251335061).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/251335061).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
