### PR TITLE
Add hab pkg export tar

### LINKED ISSUE #1027: Exporting Habitat build to run in non container environments
Discussion originated in the community forums.

https://forums.habitat.sh/t/exporting-habitat-build-to-run-in-non-container-environments/106

### PR DESCRIPTION
**Pull request by tomrobison**
Fixes #1027

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @fnichol, @reset, @seth, @metadave and @juliandunn to be potential reviewers

**Comment by reset** [comment]
@tomrobison we just moved the plans into their own [repository](https://github.com/habitat-sh/core-plans) so you'll need to move that portion of your PR over to there!

**Comment by smith** [comment]
Looks like everything here is in /components, so I don't think anything needs to be moved.

**Comment by reset** [comment]
@smith oh you're right, my mistake!

**Comment by adamhjk** [comment]
This looks great.

@thesentinels r+

**Comment by adamhjk** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit c291742 has been approved by `adamhjk`

**Comment by thesentinels** [comment]
:hourglass: Testing commit c291742 with merge 46bc425...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/142823564)

**Comment by smith** [comment]
[core/hab-pkg-tarize/0.1.0/20160706163926](https://app.habitat.sh/#/pkgs/core/hab-pkg-tarize/0.1.0/20160706163926) has been built and uploaded to the depot. :sparkling_heart:

**Comment by adamhjk** [comment]
Thanks @tomrobison!

**Comment by thesentinels** [comment]
:umbrella: The latest upstream changes (presumably 8f7985c) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
