### PR TITLE
Builder 0.10.0

### PR DESCRIPTION
**Pull request by reset**
* Fixed all `$/latest` endpoints to return actual latest version
* Package identifiers missing a version or release will now sort
  properly with identifiers that do
* Builder Habitat plans now use VERSION-BLDR to identify their version

Signed-off-by: Jamie Winsor <jamie@vialstudios.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
Looking good here

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
Sorry; I had a problem testing this pull request. The error was:

```ruby
Expected process to exit with [0], but received '128'
---- Begin output of git clone git@github.com:habitat-sh/habitat.git /hab/svc/sentinel/data/habitat ----
STDOUT: 
STDERR: Cloning into '/hab/svc/sentinel/data/habitat'...
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Load key "/hab/svc/sentinel/files/thesentinels-rsa": Permission denied
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
---- End output of git clone git@github.com:habitat-sh/habitat.git /hab/svc/sentinel/data/habitat ----
Ran git clone git@github.com:habitat-sh/habitat.git /hab/svc/sentinel/data/habitat returned 128
```

Oops

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Pull request merged**
