### PR TITLE
Fixing some usability issues

### PR DESCRIPTION
**Pull request by raskchanky**
This fixes a number of usability issues.  See commit messages for specifics.

tenor-118181444

Closes https://github.com/habitat-sh/habitat/issues/2493

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
Overall, looks good! Couple things I'm seeing when I run this locally:

The font size of the latest release should probably be dropped just a bit to match the other items in the sidebar:

image

I'm also still seeing (as described in the issue) that when I go from a state of `No packages found` on the search page and `select-all+delete`, I still see `No packages found`. (The packages list doesn't reload.)

**Comment by raskchanky** [comment]
@cnunciato Thank you for the thorough review.  I've addressed your comments!

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/242870337).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/242870337).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
