### PR TITLE
Version 0.33.1

### PR DESCRIPTION
**Pull request by reset**
tenor-238046809

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
tenor-258630292

**Comment by reset** [comment]
Gonna fast lane this one since it's the weekend and @christophermaier and I worked to doubly verify the fixes!

**Comment by fnichol** [comment]
https://www.tenor.co/vg9e.gif

**Pull request merged**
