### PR TITLE
add /jre/bin

### PR DESCRIPTION
**Pull request by cullenmcdermott**

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @elliott-davis, @smith and @juliandunn to be potential reviewers

**Comment by juliandunn** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit aeff5af has been approved by `juliandunn`

**Comment by thesentinels** [comment]
:hourglass: Testing commit aeff5af with merge 2b6804f...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/138746731)

**Comment by metadave** [comment]
built and uploaded `core/jdk8/8u92/20160620143238` to the depot

**Pull request merged**
