### PR TITLE
Fix comma splice in message displayed when there aren't any origins.

### PR DESCRIPTION
**Pull request by juliandunn**

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @smith and @metadave to be potential reviewers

**Comment by metadave** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 3d52dc6 has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 3d52dc6 with merge 74b1804...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26815764)

**Pull request merged**
