### PR TITLE
Fix formatting problem with slim in download docs

### PR DESCRIPTION
**Pull request by predominant**
Signed-off-by: Graham Weldon <graham@grahamweldon.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by robbkidd** [comment]
Yep, that'll sort out slim munching the first word of the multiline code block.

screen shot 2017-10-13 at 8 51 51 am
screen shot 2017-10-13 at 8 51 57 am

**Comment by robbkidd** [comment]
A-ha! Figured out how to slim to get a multiline text block that slim doesn't munch the first word as a markup directive:

```
      pre
        code
          | brew tap habitat-sh/habitat
            brew install hab
```

screen shot 2017-10-13 at 9 03 41 am

**Comment by predominant** [comment]
Thanks @robbkidd I updated the PR.

**Comment by robbkidd** [comment]
tenor-58976304

**Comment by reset** [comment]
tenor-88774651

**Pull request merged**
