### PR TITLE
Remove implication that hab-depot currently works.

### PR DESCRIPTION
**Pull request by dmp1ce**
Signed-off-by: David Parrish <daveparrish@tutanota.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by dmp1ce** [comment]
Maybe the wording needs a little work, but I think it is important to let users know that they cannot setup a private depot currently.  #1195 has a little more information.

**Comment by mwrock** [comment]
I definitely think its a great idea to more explicitly tell people that running a private depot is not supported. It is "possible" but is not a matter of running `core/ha-depot` and what works today may not work tomorrow until it stabilizes.

**Comment by mwrock** [comment]
Thanks a bunch for inspiring discussion. We are closing this in favor of #2285

**Pull request closed without merging**
