### PR TITLE
Add missing titles for concepts docs

### PR DESCRIPTION
**Pull request by jhedev**
A few concepts docs pages were missing the correct title.

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @juliandunn, @cwebberOps, @ryankeairns and @davidwrede to be potential reviewers

**Comment by davidwrede** [comment]
Thanks for filling these in, @jhedev!

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 5fb3613 has been approved by `davidwrede`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 5fb3613 with merge 0bfe31c...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26885743)

**Pull request merged**
