### PR TITLE
kill launcher when shutting down windows studio

### PR DESCRIPTION
**Pull request by mwrock**
Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

tenor-153889594

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/257116153).

**Comment by fnichol** [comment]
@mwrock ack, I forgot this! In PowerShell, is there a way to get the process ID of a launched process? In #2809 I had to use Bash to get the last process ID via `$!` (https://github.com/habitat-sh/habitat/blob/49b0c943e3b50a2dc118917efd1bdbbaa1c28e69/components/studio/libexec/hab-studio-type-default.sh#L122) but wasn't sure if there was a PowerShell equivalent

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/257116153).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
