### PR TITLE
Unify population of the census with health state reconciliation

### PR DESCRIPTION
**Pull request by christophermaier**
Previously, we would populate our census from `ServiceRumor`s in one
step and update census member health from Butterfly data in another
step. We only processed our `ServiceRumor`s if we got a new one since
last time we reconciled state; similar logic holds for processing of
the Butterfly membership list for health.

However, because both pieces of data are necessary to create a fully
initialized census member (they have an indeterminate health state --
neither alive, suspect, confirmed, nor departed -- until reconciled
with Butterfly data), and because there is no guarantee of the order
in which we'll receive data, we can get into a state where we've got a
stable Butterfly membership list, but are still building out our
census membership. In this case, we'll think that we've already
reconciled all our Butterfly health information (that list isn't
changing!), resulting in census members that have indeterminate
health. Until the Butterfly-layer data changes, this data will remain
out-of-sync, causing problems in the ring. Due to the nature of the
bug, these problems will manifest randomly (sometimes everything comes
up fine, other times one or more services will fail to start because
they are binding to something that's "dead").

To address this, the logic of `update_from_member_list` is pulled into
`update_from_service_store`, with the new function being named
`populate_census` to better reflect what it is doing. Additionally, if
either the service rumors or the Butterfly membership list have
changed since the last time we processed them, we update our census
representation accordingly. `update_from_member_list` was removed as a
stand-alone function.

Signed-off-by: Christopher Maier <cmaier@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by adamhjk** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/277006803).

**Comment by christophermaier** [comment]
For reference, a follow-up issue for the broader refactoring @adamhjk mentioned is #3200

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/277006803).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
