### PR TITLE
Fix name typo

### PR DESCRIPTION
**Pull request by betabit**
The number of e's should not be three.

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk, @juliandunn and @ryankeairns to be potential reviewers

**Comment by juliandunn** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit cda92fd has been approved by `juliandunn`

**Comment by thesentinels** [comment]
:hourglass: Testing commit cda92fd with merge c030529...

**Comment by juliandunn** [comment]
@thesentinels retry

**Comment by thesentinels** [comment]
:hourglass: Testing commit cda92fd with merge 880df1e...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/138432631)

**Pull request merged**
