### PR TITLE
Add Steven as a maintainer

### PR DESCRIPTION
**Pull request by smurawski**

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by adamhjk** [comment]
gif-keyboard-8941594285546027858

**Comment by smurawski** [comment]
Thanks for having me on the team @reset and @adamhjk

**Comment by adamhjk** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by adamhjk** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by adamhjk** [comment]
@thesentinels force

**Comment by thesentinels** [comment]
Excellent @adamhjk! It always makes me feel nice when humans approve of one anothers work, no matter the consequences. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by metadave** [comment]
gif-keyboard-13730617723451968429

**Pull request merged**
