### PR TITLE
[common] Add several additonal ways to create a `UI`.

### PR DESCRIPTION
**Pull request by fnichol**
This change introduces 3 new mechanisms for creating a `UI` struct,
initially for the purposes of helping testing but these may be helpful
in future UX modes like a "slient" mode.

* Adds a `UI::new(shell: Shell)` function that takes a `Shell`.
* Adds a `UI::with_streams(...)` function that takes specific IO
streams. This can be used by testing code to create temporary
stdout/stderr buffers which will not produce output during tests and
allow a tester to check for the output from a command.
* Adds a `UI::with_sinks()` function that produces a `UI` which takes no
stdin and sends both stdout and stderr to a `Sink`.

Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/274983275).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/274983275).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
