### PR TITLE
Remove unnecessary do_install. The build system does this by default.

### PR DESCRIPTION
**Pull request by juliandunn**

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @irvingpop, @fnichol and @smith to be potential reviewers

**Comment by metadave** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 24ab69a has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 24ab69a with merge 1612183...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/140670148)

**Pull request merged**
