### PR TITLE
Update for Terraform 0.7

### PR DESCRIPTION
**Pull request by reset**
These changes are necessary for the Terraform 0.7 release

* Terraform 0.7 [Release notes](https://www.hashicorp.com/blog/terraform-0-7.html)
* Terraform 0.7 [Upgrade guide](https://www.terraform.io/upgrade-guides/0-7.html)

### CODE REVIEW

**Comment by thesentinels** [comment]
@reset, thanks for your PR! By analyzing the annotation information on this pull request, we identified @jtimberman to be a potential reviewer

**Comment by reset** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 5606686 has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 5606686 with merge 02f637c...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/149319519)

**Pull request merged**
