### PR TITLE
Deploy www.habitat.sh when a PR merges to master

### PR DESCRIPTION
**Pull request by raskchanky**
These changes should enable an automatic deploy of `www.habitat.sh` whenever a PR containing changes to the `www` directory lands in master.  I based these changes off of the work that has been done in the past few days to get nightlies building on travis.

Note that I did test these changes to see the web site deploy to the `habitat-www-acceptance` s3 bucket, and it did work, but I had some slightly different settings in some of these files to let it deploy from a PR, instead of from the master branch.

e32ad4b

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
gif-keyboard-7422781314423741776

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/178155473).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/178155473).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
