### PR TITLE
Skip build for missing projects

### PR DESCRIPTION
**Pull request by chefsalim**
This change adds the ability for the scheduler to skips build jobs for packages in the reverse dependency chain that do not have a valid build project. This is a valid scenario as packages can get deprecated where there is no longer a repo/branch to point to for a build. When this scenario is encountered, the project and any subsequent project that depends on the missing project will be skipped from the build schedule.

Signed-off-by: Salim Alam <salam@chef.io>

giphy 35

### CODE REVIEW

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/235889177).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/235889177).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/235889177).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/235889177).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
