### PR TITLE
fix package contents link

### PR DESCRIPTION
**Pull request by cullenmcdermott**

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @cwebberOps, @davidwrede, @juliandunn and @ryankeairns to be potential reviewers

**Comment by reset** [comment]
@thesentinels r+

Thank you!

**Comment by thesentinels** [comment]
:pushpin: Commit 3e934db has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 3e934db with merge dd2dc46...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/138659286)

**Pull request merged**
