### PR TITLE
Pass the account id to segment instead of the account name.

### PR DESCRIPTION
**Pull request by raskchanky**
tenor-126917624

Closes https://github.com/habitat-sh/habitat/issues/3939
Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
tenor-98381242

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
Sorry; I had a problem testing this pull request. The error was:

```ruby
Expected process to exit with [0], but received '128'
---- Begin output of git reset --hard ffee7d8b6cbd2ad18d5b5ffefebdd22265affb0c ----
STDOUT: 
STDERR: fatal: Could not parse object 'ffee7d8b6cbd2ad18d5b5ffefebdd22265affb0c'.
---- End output of git reset --hard ffee7d8b6cbd2ad18d5b5ffefebdd22265affb0c ----
Ran git reset --hard ffee7d8b6cbd2ad18d5b5ffefebdd22265affb0c returned 128
```

Oops

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/293946497).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/293946497).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/293946497).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/293946497).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
