### PR TITLE
[hab/install.sh] Attempt to use both wget & curl before failing.

### PR DESCRIPTION
**Pull request by fnichol**
This change also displays a more helpful warning to the user that their version
of wget or curl may not be SSL-enabled which is a requirement.

Here are some example executions, using the very small Alpine Linux Docker image:

* Using minimal Alpine Linux with SSL-enabled wget:

```
> docker run --rm -ti -v $(pwd):/src alpine:3.4 sh -c 'apk add --no-cache wget ca-certificates; exec sh'
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/2) Installing ca-certificates (20161130-r0)
(2/2) Installing wget (1.18-r0)
Executing busybox-1.24.2-r12.trigger
Executing ca-certificates-20161130-r0.trigger
OK: 6 MiB in 13 packages
/ # sh /src/components/hab/install.sh
--> hab-install: Installing Habitat 'hab' program
--> hab-install: Downlading via wget: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
--> hab-install: Downlading via wget: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz.sha256sum?bt_package=hab-x86_64-linux
--> hab-install: Renaming downloaded archive files
'/var/tmp/tmp.Ffdepi/hab-latest.tar.gz' -> '/var/tmp/tmp.Ffdepi/hab-0.18.0-20170302192035-x86_64-linux.tar.gz'
'/var/tmp/tmp.Ffdepi/hab-latest.tar.gz.sha256sum' -> '/var/tmp/tmp.Ffdepi/hab-0.18.0-20170302192035-x86_64-linux.tar.gz.sha256sum'
--> hab-install: Verifying the shasum digest matches the downloaded archive
hab-0.18.0-20170302192035-x86_64-linux.tar.gz: OK
--> hab-install: Extracting /var/tmp/tmp.Ffdepi/hab-0.18.0-20170302192035-x86_64-linux.tar.gz
--> hab-install: Installing Habitat package using temporarily downloaded hab
» Installing core/hab
↓ Downloading core/hab/0.18.0/20170302192035
    2.41 MB / 2.41 MB \ [===============================================================================] 100.00 % 1.95 MB/s
↓ Downloading core-20160810182414 public origin key
    75 B / 75 B | [=====================================================================================] 100.00 % 3.57 MB/s
☑ Cached core-20160810182414 public origin key
✓ Installed core/hab/0.18.0/20170302192035
★ Install of core/hab/0.18.0/20170302192035 complete with 1 new packages installed.
» Symlinking hab from core/hab into /bin
★ Binary hab from core/hab/0.18.0/20170302192035 symlinked to /bin/hab
--> hab-install: Checking installed hab version
hab 0.18.0/20170302192035
--> hab-install: Installation of Habitat 'hab' program complete.
/ # echo $?
0
```

* Using minimal Alpine Linux with stock non-SSL-enabled wget, but with
SSL-enabled curl installed:

```
> docker run --rm -ti -v $(pwd):/src alpine:3.4 sh -c 'apk add --no-cache curl; exec sh'
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ca-certificates (20161130-r0)
(2/4) Installing libssh2 (1.7.0-r0)
(3/4) Installing libcurl (7.52.1-r1)
(4/4) Installing curl (7.52.1-r1)
Executing busybox-1.24.2-r12.trigger
Executing ca-certificates-20161130-r0.trigger
OK: 6 MiB in 15 packages
/ # sh /src/components/hab/install.sh
--> hab-install: Installing Habitat 'hab' program
--> hab-install: Downlading via wget: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
xxx hab-install: wget failed to download file, perhaps wget doesn't have SSL support and/or no CA certificates are present?
--> hab-install: Downlading via curl: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
--> hab-install: Downlading via wget: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz.sha256sum?bt_package=hab-x86_64-linux
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
xxx hab-install: wget failed to download file, perhaps wget doesn't have SSL support and/or no CA certificates are present?
--> hab-install: Downlading via curl: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz.sha256sum?bt_package=hab-x86_64-linux
--> hab-install: Renaming downloaded archive files
'/var/tmp/tmp.GNkNgD/hab-latest.tar.gz' -> '/var/tmp/tmp.GNkNgD/hab-0.18.0-20170302192035-x86_64-linux.tar.gz'
'/var/tmp/tmp.GNkNgD/hab-latest.tar.gz.sha256sum' -> '/var/tmp/tmp.GNkNgD/hab-0.18.0-20170302192035-x86_64-linux.tar.gz.sha256sum'
--> hab-install: Verifying the shasum digest matches the downloaded archive
hab-0.18.0-20170302192035-x86_64-linux.tar.gz: OK
--> hab-install: Extracting /var/tmp/tmp.GNkNgD/hab-0.18.0-20170302192035-x86_64-linux.tar.gz
--> hab-install: Installing Habitat package using temporarily downloaded hab
» Installing core/hab
↓ Downloading core/hab/0.18.0/20170302192035
    2.41 MB / 2.41 MB | [=============================================================================] 100.00 % 659.27 KB/s
↓ Downloading core-20160810182414 public origin key
    75 B / 75 B | [=====================================================================================] 100.00 % 3.45 MB/s
☑ Cached core-20160810182414 public origin key
✓ Installed core/hab/0.18.0/20170302192035
★ Install of core/hab/0.18.0/20170302192035 complete with 1 new packages installed.
» Symlinking hab from core/hab into /bin
★ Binary hab from core/hab/0.18.0/20170302192035 symlinked to /bin/hab
--> hab-install: Checking installed hab version
hab 0.18.0/20170302192035
--> hab-install: Installation of Habitat 'hab' program complete.
/ # echo $?
0
```

* Using minimal Alpine Linux with stock non-SSL-enabled wget (no curl present
either):

```
> docker run --rm -ti -v $(pwd):/src alpine:3.4 sh
/ # sh /src/components/hab/install.sh
--> hab-install: Installing Habitat 'hab' program
--> hab-install: Downlading via wget: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
xxx hab-install: wget failed to download file, perhaps wget doesn't have SSL support and/or no CA certificates are present?
xxx hab-install: Required: SSL-enabled 'curl' or 'wget' on PATH with
/ # echo $?
6
```

* Using minimal Alpine Linux with a fake-failing `curl` (both wget and curl
will be tried and both will fail):

```
> docker run --rm -ti -v $(pwd):/src alpine:3.4 sh -c 'echo "echo fake-curl: \$*; exit 1" > /bin/curl; chmod 755 /bin/curl; exec sh'
/ # sh /src/components/hab/install.sh
--> hab-install: Installing Habitat 'hab' program
--> hab-install: Downlading via wget: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
xxx hab-install: wget failed to download file, perhaps wget doesn't have SSL support and/or no CA certificates are present?
--> hab-install: Downlading via curl: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
fake-curl: -sSfL https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux -o /var/tmp/tmp.khlolg/hab-latest.tar.gz
xxx hab-install: curl failed to download file, perhaps curl doesn't have SSL support and/or no CA certificates are present?
xxx hab-install: Required: SSL-enabled 'curl' or 'wget' on PATH with
/ # echo $?
6
```

Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

gif-keyboard-13064136924076693161

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/209924314).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/209924314).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
