### PR TITLE
[ci] Disable SSL revocation list when using cargo on Appveyor/Windows.

### PR DESCRIPTION
**Pull request by fnichol**
See: https://users.rust-lang.org/t/appveyor-builds-failing-today/11949/4

tenor-129574121

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
Okay, I think we're getting appveyor back to green! I'm adding back the caching under the assumption that the SSL/CRL fix will work and we can benefit from cached (i.e. faster) builds again. The longest running part of appveyor came in at over 30 mins so I'd like to get that time back down.

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/255869736).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
