### PR TITLE
Add MemberList::get_cloned and refactor create_member_rumor accordingly

### PR DESCRIPTION
**Pull request by baumanj**
h/t to https://rust-lang.github.io/rust-clippy/master/#question_mark

Signed-off-by: Jon Bauman <5906042+baumanj@users.noreply.github.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by baumanj** [comment]
It looks like there are two tests consistently failing TravisCI (though I haven't been able to reproduce locally so far):

1. [`rumor::election::five_members_elect_a_new_leader_when_they_are_quorum_partitioned`](https://github.com/habitat-sh/habitat/blob/master/components/butterfly/tests/rumor/election.rs#L114)
2. [`rumor::departure::two_members_share_departures`](https://github.com/habitat-sh/habitat/blob/master/components/butterfly/tests/rumor/departure.rs#L20)

(1) Is failing on [`assert_wait_for_election_status!(net, [0..5], "witcher.prod", ElectionStatus::Finished);`](https://github.com/habitat-sh/habitat/blob/master/components/butterfly/tests/rumor/election.rs#L137), which implies to me that the election just isn't finishing. It's limited by [`max_gossip_rounds`](https://github.com/habitat-sh/habitat/blob/master/components/butterfly-test/src/lib.rs#L232), which is currently 5, so it might be interesting to see if it persists should I increase the value. Otherwise, I need to dig more deeply into how that test actually works. The output seems to me like all the votes are present such that the election should end:
```
Failed election check for status Finished: RumorStore {
    list: RwLock {
        data: {
            "witcher.prod": {
                "election": Election {
                    member_id: "759ab91b6af14b4aaddd543bfd21731f",
                    service_group: "witcher.prod",
                    term: 0,
                    suitability: 1,
                    status: Running,
                    votes: [
                        "759ab91b6af14b4aaddd543bfd21731f",
                        "255cae636fee419eb1bace8a2015653e",
                        "f0cd467807c2498b9aef45dc9231ae8a",
                        "9a7129e6b5744d18bac62fae7f9fdc08",
                        "2b448520c4374b7a9c67b971fa2d022c"
                    ]
                }
            }
        }
    },
    update_counter: 7
}
```
So maybe there is an actual bug, but I'm at a real loss for how the change in this PR could've caused it.

(2) is much simpler: it's just adding a departure rumor on member 0 and checking that it shows up on member 1. Again, I can't see why that would fail with this change, but I suppose I can try some additional logging.

**Comment by baumanj** [comment]
Whelp, adding `--test-threads=1` made this pass. And didn't seem to make travis actually take any longer, so I'm kinda inclined it just leave it in.

**Comment by raskchanky** [comment]
@baumanj Seems fine to me.  :shipit:

**Pull request merged**
