### PR TITLE
Add _common_prepare to do_prepare callback

### PR DESCRIPTION
**Pull request by tomrobison**
Signed-off-by: Tom Robison <thomas.robison@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @fnichol, @adamhjk, @juliandunn and @smith to be potential reviewers

**Comment by smith** [comment]
Thanks!

gif-keyboard-17754658584900237801

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit b7ed3dc has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit b7ed3dc with merge b7ed3dc...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/141171989)

**Comment by smith** [comment]
Built and uploaded https://app.habitat.sh/#/pkgs/core/openssl/1.0.2h/20160629200645

**Pull request merged**
