### PR TITLE
make clear that the cmd means the public key

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
You can actually upload the private key as well both via the web UI or the command line. Is that not working for you?

**Comment by ShalokShalom** [comment]
I got confused by the text:

" If you do not upload at least the public key for the origin, the depot will reject the upload of your packages under that origin."

and together with that:

"You can upload keys for the origin through the web interface for the depot, or by using the hab origin key upload command."

Since that sounds like this uploads both, the private and the public keys. 
I agree that my change makes less sense since it does not apply to the web UI, while the command to upload private keys look a bit different. 

I just like to make clear, that the common behavior is uploading a public key and how this is working. 
So long as the upload of a private key is something special, it should be marked so. 

I hope this is clear :/

**Comment by ShalokShalom** [comment]
And where can i upload packages on the web interface?

https://bldr.habitat.sh/#/

**Comment by mwrock** [comment]
You must use the hab cli to upload packages

**Comment by ShalokShalom** [comment]
So the current text speaks about that wrong anyway, let me create another issue.

**Pull request closed without merging**
