### PR TITLE
update handlebars to 0.20.1

### PR DESCRIPTION
**Pull request by metadave**
resolves https://github.com/habitat-sh/habitat/issues/1117 via https://github.com/sunng87/handlebars-rust/pull/94

thanks @sunng87 for publishing a release so quickly!

### CODE REVIEW

**Comment by thesentinels** [comment]
@metadave, thanks for your PR! By analyzing the annotation information on this pull request, we identified @reset, @adamhjk and @fnichol to be potential reviewers

**Comment by fnichol** [comment]
Excellent, fast turnaround!

**Comment by reset** [comment]
gif-keyboard-5354687389042837372

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 19b6206 has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 19b6206 with merge 0404107...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/149558011)

**Pull request merged**
