### PR TITLE
Apply default package visibility settings when packages are uploaded

### PR DESCRIPTION
**Pull request by raskchanky**
Note that this _should_ take care of both users uploading packages on their own and builder building packages, since the builder worker uses the same HTTP upload endpoint when it finishes building a package.

There might need to be a change to how this works in the future, after @chefsalim's refactor of the worker to remove HTTP uploading.

tenor-92374911

Closes https://github.com/habitat-sh/habitat/issues/3118

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/274456794).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/274456794).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
