### PR TITLE
Update the package sidebar to pull the latest stable

### LINKED ISSUE #3305: [Builder-Web] `latest stable` in UI is pointing to latest package
The sidebar on the package view is currently showing the _latest package_ instead of the _latest stable package_

screen shot 2017-09-24 at 7 06 32 am

### PR DESCRIPTION
**Pull request by cnunciato**
This updates the package sidebar component to retrieve the latest stable version of the package, rather than just the latest.

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

Fixes #3305.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

tenor-2573883

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/280214071).

**Comment by cnunciato** [comment]
@ryankeairns For packages that have no latest stable, this just hides the LATEST STABLE section of the sidebar, but now I'm wondering whether it'd be clearer to show the heading with something like "None." below it, just for clarity. Thoughts on this?

**Comment by reset** [comment]
@cnunciato @ryankeairns what if we showed *latest stable* and *latest unstable*? You can put "none" or hide the thing if there isn't one in stable

**Comment by cnunciato** [comment]
We could, but I guess we do have the Latest tab, which should always be the latest stable.

**Comment by ryankeairns** [comment]
@cnunciato How about ‘None. View available builds.’ Where that last part links to Bulld Jobs or Versions tab?

I like leaving the LATEST STABLE as it indicates clearly that there isn’t one.

**Comment by cnunciato** [comment]
@ryankeairns Sounds good to me.

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/280214071).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
