### PR TITLE
Prep for 0.30 release

### PR DESCRIPTION
**Pull request by chefsalim**
Signed-off-by: Salim Alam <salam@chef.io>

tenor-57180797

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
tenor-221418552

**Comment by christophermaier** [comment]
tenor-172634061

**Comment by fnichol** [comment]
tenor-60009877

**Pull request merged**
