### PR TITLE
removes root requirement for running hab start, now only warns rather…

### PR DESCRIPTION
**Pull request by nellshamrell**
… than fails

Tested this in a docker container, and with this change a user can run hab start as the hab user, rather than needing to use the root user.

Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
This is great!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/214863728).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/214863728).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by reset** [comment]
Delivered a much asked for improvement in just a few lines, good work @nellshamrell!

gif-keyboard-13601963992606690101

/cc @fnichol @adamhjk do we also want to remove the requirement on installing packages? It would seem that this would be a little less useful if we didn't but I wanted to make sure ;)

**Pull request merged**
