### PR TITLE
[hab] Disable `config apply` & `file upload` on Mac and Windows systems.

### PR DESCRIPTION
**Pull request by fnichol**
As of the 0.14.0 release, the two subcommands `config apply` and `file
upload` are provided by an accompanying Habitat package
`core/hab-butterfly` which is installed on first use similar to the
behavior of the `sup` and `studio` subcommands on Linux. As the Depot
software currently doesn't support multiple target systems we cannot
simply download the required package and proceed. As such, until we can
provide a better experience for this on Mac and Windows, a message will
be displayed to users explaining that these subcommands are not
currently supported.

The following would be displayed:

```
> target/debug/hab config apply
∅ Running `config apply` on this operating system is not currently supported. Try running this command again on a 64-bit Linux operating system.

✗✗✗
✗✗✗ Subcommand `config apply' not supported on this operating system
✗✗✗
```
gif-keyboard-2448706760253377657

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
gif-keyboard-11818690423648201552

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/185938078).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/185938078).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
