### PR TITLE
Add a back-to-build-jobs link

### LINKED ISSUE #3928: [Builder UI] Add 'back to build jobs' link on build output screen
As a user, I want to easily navigate back to the list of build jobs from the build output screen
so that I can quickly access other build job output

The UI mockups for the build output screen include a 'back to build jobs' link that simply takes a user from the build output view back to the list of build jobs. This is of importance since these two screens (build output and build job list) both reside under a single tab (BUILD JOBS) making it not obvious how you navigate back and forth between these screens.

The link can be seen in the following mockup:
[Build output example](https://chef.invisionapp.com/share/DUE6DJN7S#/248751352_package_Detail_V2_-_Output_Collapsed_Published)

### PR DESCRIPTION
**Pull request by cnunciato**
Fixes #3928.

Signed-off-by: Christian Nunciato <chris@nunciato.org>

tenor-210412295

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/319288117).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/319288117).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
