### PR TITLE
cargo audit github action

### PR DESCRIPTION
**Pull request by jasonheath**
There's may be some noise on this branch as I rev different things working to test out this new functionality.  This commit is the first cut of the files and after this I intend to upgrade some things in order to see it working.

### CODE REVIEW

**Comment by jasonheath** [comment]
One point of discussion.  As currently committed `cargo audit` will run for every push.  We can instead run it only when the Cargo.lock, a Cargo.toml and the .cargo/audit.toml files change during a push and I think that's a useful change.  We could also have it run daily via a cron job.  I kind of like that as well.  Both are easy to add.

**Review by mwrock — APPROVED** [review]
Looks good!

**Comment by jasonheath** [comment]
So as is?  No changes as to pushing for those three files or putting it on a schedule?

**Comment by mwrock** [comment]
I think it's fine as is. It's not expensive and will finish way before the verify check and we are more likely to see it in a PR than on a schedule.

**Pull request merged**
