### PR TITLE
Switch over to `hab` Bintray URL now that we are live

### PR DESCRIPTION
**Pull request by schisamo**
Signed-off-by: Seth Chisamore <schisamo@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @fnichol to be a potential reviewer

**Comment by schisamo** [comment]
@fnichol Do we also want to update:
https://github.com/schisamo/habitat/blob/master/terraform/scripts/bootstrap.sh

...to use this `install.sh` OR at least pull from Bintray?

**Comment by fnichol** [comment]
Perfect, you beat me to this!

gif-keyboard-13327838951016575517

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 4f6afae has been approved by `fnichol`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 4f6afae with merge 7a8dafe...

**Comment by fnichol** [comment]
@schisamo We should update the terraform, but would like to double check with @reset first as that impl. had asked for a specific version. I suppose we could get the equivalent direct Bintray URLs though.

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26837390)

**Comment by reset** [comment]
@fnichol we want latest in Terraform, thank you for asking!

**Comment by schisamo** [comment]
@reset This script should do just what you need! Not sure if/where it is being served up on the public web though (e.g. https://willem.habitat.sh/install.sh ??). It would be awesome to serve it up though so others can curl to bash that initial `hab` used to bootstrap the application.

**Pull request merged**
