### PR TITLE
Fix automated deployments to acceptance

### LINKED ISSUE #2510: [www] Fix automated deployment to acceptance
We're supposed to be able to deploy an open PR to acceptance a mention to the bot (`@thesentinels acceptance`), but the last few times I've done that, it hasn't worked. We should investigate and fix.

### PR DESCRIPTION
**Pull request by cnunciato**
This fixes automated deployments by adjusting the way we determine the files affected by a merge commit. Rather than use the TRAVIS_COMMIT_RANGE environment variable, which is unreliable, this change examines only the most recent merge commit on the target branch, which is sufficient given that Travis will always have created one for us.

Also removes some no-longer-needed AWS config. 

Fixes #2510.

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

### CODE REVIEW

**Comment by reset** [comment]
tenor-192927288

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/243081799).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/243081799).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
