### PR TITLE
More Codeowners Changes

### PR DESCRIPTION
**Pull request by eeyun**
Adds a new section for the rootless studio, adds myself as a codeowner for some stuff
Signed-off-by: Ian Henry <ihenry@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@eeyun Gotta get a DCO 😄 

Also, would you mind rebasing this, rather than having a merge from master in this branch?

**Comment by eeyun** [comment]
Strange also it IS DCO'd - let me rebase and correct this

**Pull request merged**
