### PR TITLE
Add PostRun hook to hook table

### PR DESCRIPTION
**Pull request by bodymindarts**
Closes https://github.com/habitat-sh/habitat/issues/1983

Signed-off-by: Justin Carter <justin@starkandwayne.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
Should we change the state of the service or delay its completed initialization until the post run hook has completed?

My concern is that once the run hook has completed, other services can bind to this service and the service may not be "prepared" for binding until the post run hook completes.

**Comment by bodymindarts** [comment]
@mwrock thats a good point but I would like to mention that currently the `initialized`status of a service has no baring whatsoever on the rest of the system. Even though the gossiped messages have a field for that it is never being populated or read out.
That doesn't mean we shouldn't think about this, just that any decision wouldn't come to bare until that information actually gets gossiped.

That being said what do you think is correct:
`hooks/init` gets repeated until it succeeds
-> `hooks/run`
-> `hooks/post-run` until it succeeds.
Or should the entire 
`hooks/init`
`hooks/run`
`hooks/post-run`

sequence get repeated until all have succeeded?

**Comment by mwrock** [comment]
Yeah looking at the flow again I see what you are saying. `initialized` does not even state that or guarantee that the service run hook has completed. I'm fine with this as is but am curious what others think before merging. @reset had some comments on this topic in https://github.com/habitat-sh/habitat/issues/1393 and I am curious what his thoughts are here.

**Comment by bodymindarts** [comment]
Actually I understand the concerns that @reset mentions in that ticket.

I definitely see a need for this hook but it makes sense to discuss what it
means for a service to be initialized and what the expected behavior is.

In the context of 1 service this doesn't have much baring but in systems
with multiple collaborators it is very important to have clear contacts.
Otherwise there is no way to reliably orchestrate longer life cycles
including updates of dependant (potentially clustered services) services.

In BOSH there is the equivalent 'post-start' Skript and it is considered
part of the initialization.
Eg. When updating a cluster and a post-start script falls then the whole
update will terminate (leaving the remaining nodes in the old state). When
an operator continues the update ('bosh deploy) will be re start the
proceces on the ndes that failed (including the post-start script) before
attempting to update the rest of the nodes.

**Comment by reset** [comment]
@mwrock @bodymindarts I think this is a perfectly acceptable implementation and I think it actually prevents what I was worried about in #1393. What I didn't want to happen was for the service to start and then a rumor to be sent which indicated to it's peers that all was good. This will actually block after service start for the hook to complete before that rumor is sent.

gif-keyboard-14807548089388691765

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/223261398).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/223261398).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
