### PR TITLE
Change try! to ?

### PR DESCRIPTION
**Pull request by georgemarshall**
This change updates the code base to use the newer `?` version of `try!`

image

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by afiune** [comment]
IMHO (from a dev perspective) Sometimes it is good to continue using `try!()` since you can easily catch when you are trying to unwrap the value from a `Result<>`(or other type on the left hand side), some other times though, like when you write code chaining expressions, it makes me smile that I can just use `?`.

**Comment by georgemarshall** [comment]
The main driver behind these changes was a discussion in the #rust channel about the inconsistency of mixing both. It was any easy change and thus thought it would be worth submitting a PR of the changes.

Consider it on par with the changes that happen every time `rustfmt` is upgraded.

**Comment by reset** [comment]
@georgemarshall could you resolve conflicts and squash commits? Thanks man!

**Comment by georgemarshall** [comment]
Yea, should be ready in 10 min.

**Comment by reset** [comment]
@thesentinels approve

tenor-211258507

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/253737095).

**Comment by thesentinels** [comment]
:broken_heart: Travis CI reports [this PR failed to pass the test suite](https://travis-ci.org/habitat-sh/habitat/builds/253737095).

The next step is to examine the [job](https://travis-ci.org/habitat-sh/habitat/builds/253737095) and figure out why. If it is transient, you can try re-triggering the Travis CI Job - if it passes, this PR will be automatically merged. If it is not transient, you should fix the issue and update this pull request, and issue `approve` again. If you believe it will never pass, and you are feeling :godmode:, you can issue a `force` to merge this PR anyway.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/253737095).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/253737095).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
