### PR TITLE
Set initial version to 0.1.0 in `hab plan init`

### PR DESCRIPTION
**Pull request by smith**
instead of 0.0.1. Small nitpick thing, but http://semver.org/#faq says:

> How should I deal with revisions in the 0.y.z initial development
> phase?

> The simplest thing to do is start your initial development release at
> 0.1.0 and then increment the minor version for each subsequent release.

So let's do that.

gif-keyboard-15821273349619666947

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/189257838).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/189257838).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
