### PR TITLE
handle migration case of symlinks in svc directory

### LINKED ISSUE #1267: Check filetype of static/run in svc directory before writing to
Recent versions of the supervisor assume that the following files or directories are actual files and not symlinks:

* `/hab/svc/${service}/static`
* `/hab/svc/${service}/run`

Previous versions of the supervisor created both of these as a symlink which causes issues if a newer supervisor attempts to start a service from a service directory created by an older version of the supervisor.

In the case of the static directory we experience a service startup error which can easily be resolved by deleting `/hab/svc/${service}/static` and attempting to start the supervisor again. I believe this can be repaired by simply checking if the directory is a symlink and, if so, removing it.

The case of the run script is a bit worse. Newer versions of the supervisor is allowed to write to the run script in the svc directory. This will cause the run script in the *actual package* to be overwritten forcing the end-user to re-install their package. I believe this can be repaired by checking if `/hab/svc/${service}/run` is a symlink and, if so, removing it just like the static directory.

### PR DESCRIPTION
**Pull request by metadave**
resolves #1267 
HAB-281

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@metadave Looks good and I love the tests!

gif-keyboard-14459780969214574728

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/165382802).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/165382802).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
