### PR TITLE
Honor the `start` parameter for archived log requests

### LINKED ISSUE #2622: Retrieval of completed job log does not respect `start` parameter
When retrieving a job log via the API, we provide a `start` URL parameter to allow retrieval of the log from that line. However, if the log is already completed (and we're retrieving it from the archive rather than from the local disk) we currently [ignore](https://github.com/habitat-sh/habitat/blob/aa150a64e5f29f7cad502964216a139a88abab04/components/builder-jobsrv/src/server/handlers.rs#L118) any `start` parameter and just return the entire log, whether the user wanted the whole thing or not! This is not intentional, and amounts to an oversight.

If a non-zero value for `start` is provided, we should honor it, regardless of whether the job is complete or not.

Thanks to @cnunciato for pointing this out.

### PR DESCRIPTION
**Pull request by cnunciato**
Currently we’re setting the start index to zero (meaning retrieve the full log) on any request for an archived log. This change honors the value passed in with the request, and for out-of-range values, just returns an empty list.

Fixes #2622.

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@cnunciato Nice!

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/245727682).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/245727682).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
