### PR TITLE
Add groff plan

### PR DESCRIPTION
**Pull request by smith**
gif-keyboard-17767210912883262197

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by metadave** [comment]
@thesentinels r+
gif-keyboard-6124353286088562375

**Comment by thesentinels** [comment]
:pushpin: Commit 8564969 has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 8564969 with merge c78013c...

**Comment by metadave** [comment]
`core/groff/1.22.3/20160623182339` uploaded to the depot

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139840723)

**Pull request merged**
