### PR TITLE
Replace deprecated rand usage with mktemp

### PR DESCRIPTION
**Pull request by baumanj**
Very similar to https://github.com/habitat-sh/habitat/pull/5562

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
Odd Travis failures: `use of unstable library feature 'rustc_private'` 🤔 

Other than that, looks good (like the previous work!)

**Comment by mwrock** [comment]
The appveyor failures definitely look relevant to the code change.

**Comment by baumanj** [comment]
Ok, I think I understand the AppVeyor failures. But the travis ones are still mysterious to me.

**Comment by baumanj** [comment]
Abandoned in favor of https://github.com/habitat-sh/habitat/pull/5655

**Pull request closed without merging**
