### PR TITLE
update to rustfmt 0.8.0

### PR DESCRIPTION
**Pull request by mwrock**
Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
@mwrock Unfortunetly, there's one more place that refers to the rustfmt version, in [`support/ci/lint.sh`](https://github.com/habitat-sh/habitat/blob/849fa27188b3c7cc3361d4edfd37c9a71e1d3bef/support/ci/lint.sh#L50). That should cover it though, similar to the [0.7.1 update](https://github.com/habitat-sh/habitat/commit/fdfb3ceea115f9b1ca7670dd2ed81ae1e40cc73e).

**Comment by mwrock** [comment]
thanks I'll add that. I also neglected to run cargo fmt on all the things which I am doing now

**Comment by fnichol** [comment]
For those interested, these are the high-level changes from rustfmt 0.7.1 to 0.8.0 (as compiled by me earlier this week)

* [Process build scripts](https://github.com/rust-lang-nursery/rustfmt/pull/1286)
* [Do not format string lits by default](https://github.com/rust-lang-nursery/rustfmt/commit/e56ef44a3a27d1f609a20aacbdd2919f225175a9)
* [Support field-init-shorthand](https://github.com/rust-lang-nursery/rustfmt/pull/1308)
* [Add error_on_line_overflow option](https://github.com/rust-lang-nursery/rustfmt/pull/1325)
* [Fix width bug for long patterns in match arms](https://github.com/rust-lang-nursery/rustfmt/commit/7ad352239acbc5c2824ab97ab8881ea843496d0e)

**Comment by mwrock** [comment]
ok i added the lint script and also formatted everything @fnichol

**Comment by fnichol** [comment]
Looks good to me, thanks for doing this!

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/212231314).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/212231314).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
