### PR TITLE
Resolve symlinks when searching for keys

### LINKED ISSUE #2939: `No revisions found for chef-ring sym key` when ring key is a symlink
if the ring key is a symlink instead of the actual file, the supervisor is unable to find the key. This matters because kubernetes does not mount actual files but instead creates symlinks.

```
# cd /hab/cache/keys/
/hab/cache/keys # ls -al
total 12
drwxrwxrwx    3 root     root          4096 Aug 15 16:52 .
drwxr-xr-x    1 root     root          4096 Aug 11 21:10 ..
drwxr-xr-x    2 root     root          4096 Aug 15 16:52 ..8988_15_08_16_52_32.234939343
lrwxrwxrwx    1 root     root            31 Aug 15 16:52 ..data -> ..8988_15_08_16_52_32.234939343
lrwxrwxrwx    1 root     root            39 Aug 15 16:52 chef-ring-20170815133633.sym.key -> ..data/chef-ring-20170815133633.sym.key
lrwxrwxrwx    1 root     root            42 Aug 15 16:52 cia-delivery-20170815134636.box.key -> ..data/cia-delivery-20170815134636.box.key
lrwxrwxrwx    1 root     root            38 Aug 15 16:52 cia-delivery-20170815134636.pub -> ..data/cia-delivery-20170815134636.pub
lrwxrwxrwx    1 root     root            54 Aug 15 16:52 customer_portal.prod@cia-20170815134841.box.key -> ..data/customer_portal.prod@cia-20170815134841.box.key
lrwxrwxrwx    1 root     root            50 Aug 15 16:52 customer_portal.prod@cia-20170815134841.pub -> ..data/customer_portal.prod@cia-20170815134841.pub
```

If I unlink the `chef-ring-20170815133633.sym.key` file and then cp `..data/chef-ring-20170815133633.sym.key` into `/hab/cache/keys` the supervisor joins the ring.

### PR DESCRIPTION
**Pull request by christophermaier**
There are a few different ways to get file metadata in Rust, some of
which traverse symlinks and others that do not. Grabbing metadata
directly from a `DirEntry` is one of the latter. This is what we were
using, meaning that any keys that were symlinks were effectively
invisible to Habitat.

If you instead get metadata from the `DirEntry`'s path, you _do_
resolve symlinks, meaning that `is_file()` will return `true`.

Some of the variable names in the `get_key_revisions` function were
changed to better reflect that we are dealing with `DirEntry` structs,
to make it a bit more obvious what is happening.

Fixes #2939

Signed-off-by: Christopher Maier <cmaier@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

tenor-136069853

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/266170789).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/266170789).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
