### PR TITLE
Adds Supervisor demo 

### PR DESCRIPTION
**Pull request by ryankeairns**
👀  I'm pretty certain the steps are technically accurate, but there's alot of config I've done over the past couple of years :)

This demo walks through starting up a stable version of the sample-node-app, then promoting a new stable version and seeing the supervisor handle the auto-update.

This demo also re-uses the setup and installation steps from the other predecessor demos, though it neither necessitates creating a local build nor updating a build artifact... so I don't think there's much required (I'm specifically thinking about `export` items like HAB_ORIGIN and HAB_AUTH_TOKEN.. which I've left out). 

Also, I've noted on a couple of steps (1 and 8) where you can jump ahead if you've already set things up in the predecessor demos.

Anywho, give it a spin and let me know what you think! I've also updated the home page and /learn with links to this new demo.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by ryankeairns** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/324735849).

**Comment by thesentinels** [comment]
:broken_heart: Travis CI reports [this PR failed to deploy](https://travis-ci.org/habitat-sh/habitat/builds/324735849).

The next step is to examine the [job](https://travis-ci.org/habitat-sh/habitat/builds/324735849) and figure out why. If it is transient, you can try re-triggering the Travis CI Job - if it passes, this PR will be automatically merged. If it is not transient, you should fix the issue and update this pull request, and issue `approve` again. If you believe it will never pass, and you are feeling :godmode:, you can issue a `force` to merge this PR anyway.

**Comment by ryankeairns** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/324735849).

**Comment by thesentinels** [comment]
:broken_heart: Travis CI reports [this PR failed to deploy](https://travis-ci.org/habitat-sh/habitat/builds/324735849).

The next step is to examine the [job](https://travis-ci.org/habitat-sh/habitat/builds/324735849) and figure out why. If it is transient, you can try re-triggering the Travis CI Job - if it passes, this PR will be automatically merged. If it is not transient, you should fix the issue and update this pull request, and issue `approve` again. If you believe it will never pass, and you are feeling :godmode:, you can issue a `force` to merge this PR anyway.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/324735849).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/324735849).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by ryankeairns** [comment]
Preview the new content here: https://www.acceptance.habitat.sh/

**Comment by reset** [comment]
tenor-34579493

Looks accurate!

**Pull request merged**
