### PR TITLE
Quick fix for sorting package identifiers returned by the Depot API

### PR DESCRIPTION
**Pull request by reset**
This is a first pass implementation to get a fix out the door. We're
pulling a bulk of strings out of the database and allocating identifiers
for each then performing a sort in memory. This is going to be alright
for now, but in the future we should use weights in Redis' sorted sets
and adjust the rank of all identifiers on insertion of a new package
so we only perform the sorting overhead on write instead of each read

Signed-off-by: Jamie Winsor <jamie@vialstudios.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
@reset, thanks for your PR! By analyzing the annotation information on this pull request, we identified @metadave and @fnichol to be potential reviewers

**Comment by raskchanky** [comment]
I think I understand what's going on here, and from what I can tell, it looks good.

gif-keyboard-11019382013941327395

**Comment by adamhjk** [comment]
This looks good. Yay for traits making the `sort` logic just work on the iterator.

Merge it!

**Comment by adamhjk** [comment]
gif-keyboard-3394374292705165834

**Pull request merged**
