### PR TITLE
Sync job status notifications with builder-scheduler

### PR DESCRIPTION
**Pull request by chefsalim**
This change adds reliable job status notifications to be sent from the job server to the builder scheduler. This allows the system to be more robust under failure conditions. The original mechanism of sending the job status to the scheduler via a pub/sub ZMQ socket is now deprecated. This change also fixes a bug where some notifications caused the scheduler to crash.

Signed-off-by: Salim Alam <salam@chef.io>

giphy 24

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
Excellent refactor and thanks for tending to the log level of the messages in these services!

tenor-103418885

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/227679757).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/227679757).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
