### PR TITLE
Remove vendored sodiumoxide and libsodium-sys from components

### PR DESCRIPTION
**Pull request by reset**
These two vendored components had their necessary improvements merged
into their master branches and pushed to crates.io, so we can drop our
vendored code and switch over.

Additionally, this PR updates our crate dependencies in the roll forward often fashion that we've adopted for crate dep management

gif-keyboard-1596825245039141399

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
Closes #952

**Comment by fnichol** [comment]
@reset Did you intend to update the other project deps in this commit?

**Comment by reset** [comment]
@fnichol yes, but I completely forgot to mention it in the PR. This was intended to be an overall clean up our deps PR!

**Comment by adamhjk** [comment]
gif-keyboard-15498891535237152095

@thesentinels approve

**Comment by fnichol** [comment]
@reset K, wanted to make sure--I grep our git commits for dep-bumping commits occasionally when bisecting down an issue.

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/165281585).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/165281585).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
