### PR TITLE
[sup] Refactor `SpecWatcher` to call notify's sync API.

### PR DESCRIPTION
**Pull request by fnichol**
After putting `SpecWatcher` into use, I found the async APIs in notify
to not be as reliable as I expected (i.e. using `rx.try_recv`, etc. on
the channel), so this changes the strategy a bit. The new implementation
spawns a thread which sets up the channel and then consumes all fs
events with blocking reads. On each event it gets, it sets a shared
`AtomicBool` to true and the main checking function
`SpecWatcher.new_events()` simply checks the value of this shared
boolean, and resets it if it's loaded specs off disk. Much more
reliable!

References #1976

gif-keyboard-18362153266568422464

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
gif-keyboard-17578841332521531907

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/214364812).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/214364812).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
