### PR TITLE
Replace Mesosphere with DC/OS per Mesosphere's request

### PR DESCRIPTION
**Pull request by mattray**
Andy Paroff did the work

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by ryankeairns** [comment]
I'm going to cut the size of this in half since it's quite large (5000px + wide) and push it up to this PR.

**Comment by ryankeairns** [comment]
@mattray can you have Andy reduce the size by 50%? Even on a retina display, this wouldn't need to be larger than that... it's currently over 5000px wide. Thanks!

**Comment by mattray** [comment]
@ryankeairns done

**Comment by ryankeairns** [comment]
great, thanks!

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 13826cc has been approved by `ryankeairns`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 13826cc with merge 854b4f2...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26905778)

**Pull request merged**
