### PR TITLE
`hab studio enter` on Windows via Docker!

### PR DESCRIPTION
**Pull request by smurawski**
- [X] Works on Windows with Docker for Windows
- [X] Works on Mac with Docker for Mac

Signed-off-by: Steven Murawski <steven.murawski@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
I don't know if we're ok to merge things yet or not, but whenever we are, this looks good to me. 👍 

gif-keyboard-9094612746379443699

**Comment by smurawski** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
Hey, @smurawski - you don't have permission to issue `approve` on this pull request.

Nope

**Comment by metadave** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
Hey, @metadave - you don't have permission to issue `approve` on this pull request.

Nope

**Comment by metadave** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/164674721).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/164674721).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by smurawski** [comment]
progress on #1192

**Pull request merged**
