### PR TITLE
Copies /etc/inputrc in studio if available

### LINKED ISSUE #4060: Allow ctrl+<arrow> in studio shell
> hab 0.38.0/20171026215954

This is a nice to have, but frequently, I'm frustrated because I can't use CTRL + :arrow_left: nor CTRL + :arrow_right: in the studio.

Instead the studio shell prints things like `;5D` or `;5C` which I have to delete and use only arrow keys.

### PR DESCRIPTION
**Pull request by rsertelon**
This fixes #4060 by using host configuration for input in the studio.

Signed-off-by: Romain Sertelon <romain@sertelon.fr>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by HT154** [comment]
Does this also apply to the docker studio? Or just the chroot studio?

It would also be neat if it generated a sensible default inputrc if none was present on the host system (in /etc/inputrc or ~/.inputrc)

**Comment by rsertelon** [comment]
@HT154 I think this might be just for the chroot studio. Not sure what is needed to make it work in docker.

**Comment by christophermaier** [comment]
I think it might be good to define a minimal `/etc/inputrc` that we could use. That may make it easier for the Docker experience to be the same as the chroot studio.

**Comment by rsertelon** [comment]
@christophermaier yep, that would be nice indeed. Thing is, I don't really know about `libreadline` and appart from proposing the default Ubuntu 18.04 `/etc/inputrc`... ;)

What should be have in your opinion at a minimum?

Of course, I'm thinking about support for ctrl+left/right arrow, anything else we could think of?

**Comment by rsertelon** [comment]
Ping :)

**Comment by rsertelon** [comment]
@christophermaier I've changed the implementation to create a default file in the studio.

Is there anything to do for the docker studio?

**Comment by christophermaier** [comment]
Sorry for the delay @rsertelon ... This is on my list to get to very soon!

**Comment by christophermaier** [comment]
Hrmm... I'm having trouble verifying that this works. I'm no readline guru, but I wonder if there's some kind of terminal shenanigans afoot. I'll continue investigating.

**Pull request merged**
