### PR TITLE
Remove plans from repository

### PR DESCRIPTION
**Pull request by reset**
Now that we have launched and are no longer developing Habitat in lock-step with our core packages they can safely be moved to their own [repository](https://github.com/habitat-sh/core-plans).

All pull requests up to this point with regards to plans have been merged with the exception of one which was undecided and one which was opened when I began this work. I'll follow up with both of those issues to make sure they are seen through.

gif-keyboard-14392334969307394099

Signed-off-by: Jamie Winsor <jamie@vialstudios.com>

### CODE REVIEW

**Comment by juliandunn** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit c78a767 has been approved by `juliandunn`

**Comment by thesentinels** [comment]
:hourglass: Testing commit c78a767 with merge c78a767...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/141718599)

**Pull request merged**
