### PR TITLE
Fix typo in install script

### PR DESCRIPTION
**Pull request by d2lam**
Fixing typo in the script.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
@d2lam This looks great, but it looks like we're missing a DCO line (it's a one line "sign off" at the end of the commit message). Can we get you to add a [DCO line](https://github.com/habitat-sh/habitat/blob/master/CONTRIBUTING.md#signing-your-commits) to that commit message and repush? Thanks!

**Comment by d2lam** [comment]
@fnichol  Sure. I added the DCO line. Thanks! :)

**Comment by reset** [comment]
tenor-94321465

**Pull request merged**
