### PR TITLE
Make a new Search module, do a bit of cleanup

### PR DESCRIPTION
**Pull request by cnunciato**
This change does a few cleanup-related things, including:

* Pulling the packages page and packages list into a new Search module, since what remains of those views now supports only search

* Removes a bunch of now-dead code from those components

* Fixes a bug with the progress bar by restricting it to origins-loading state (we aren’t yet set up to use it properly elsewhere)

* Restores some recently lost styling

* Routes links from the Explore view to /latest

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/272132621).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
