### PR TITLE
"reasonable" is a better choice than "sane"

### PR DESCRIPTION
**Pull request by nathenharvey**
Some minor wordsmithing

Signed-off-by: Nathen Harvey <nharvey@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk, @fnichol, @metadave, @juliandunn and @reset to be potential reviewers

**Comment by metadave** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 803af15 has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 803af15 with merge b50ae66...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26816374)

**Pull request merged**
