### PR TITLE
Add Brian Scott as a Maintainer

### PR DESCRIPTION
**Pull request by bscott**

### CODE REVIEW

**Comment by adamhjk** [comment]
This is a definite plus. Rebase and approve yourself. 

@thesentinels delegate=@bscott

**Comment by bscott** [comment]
@adamhjk Can you merge, I don't have rights

**Comment by bscott** [comment]
@adamhjk It passed!

**Comment by bscott** [comment]
@thesentinels r+

**Comment by smith** [comment]
@bscott I added you to the list of maintainers on Homu, so you should be able to r+ any PR now. See https://habitat-homu.herokuapp.com/ for instructions.

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit da2c62d has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit da2c62d with merge da2c62d...

**Comment by smith** [comment]
Merging manually (see https://habitat-sh.slack.com/archives/general/p1468417818008298)

**Comment by reset** [comment]
gif-keyboard-1119605749187328702

**Comment by thesentinels** [comment]
:boom: Test timed out

**Pull request merged**
