### PR TITLE
Finalizing content for Explore page

### PR DESCRIPTION
**Pull request by ryankeairns**
Completes v1 of #2181 

I've made some tweaks, but was out of my depth in converting the current JSON fetch from 1 to 3 different lists. Attached is a screenshot of the desired packages in each list... other than that, I think it will be done

screenshot 2017-05-16 17 10 28

Signed-off-by: Ryan Keairns <rkeairns@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
@ryankeairns I can help

**Comment by raskchanky** [comment]
@ryankeairns Should be good to go now

**Comment by ryankeairns** [comment]
@tashimi We'll have to push through another update once the other plans land, but at this point we can merge this and we'll have links to real plans. I've also removed the Getting Started video section for now.

**Comment by reset** [comment]
tenor-38597281

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/233085050).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/233085050).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
