### PR TITLE
Updates the blog post on windows docker export

### PR DESCRIPTION
**Pull request by burtlo**
@mwrock you continue to bring the love to the Windows + Habitat world!

* add titles (may need review/revisions)
* prefacing commands with a prompt char '>'
* combining commands and output
* adding path and json format to the json file

Bill Gates laying on the deck -- you know the picture

## Example of final rendering

image

Signed-off-by: Franklin Webber <franklin@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by tashimi** [comment]
tenor-129327259

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/339077397).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/339077397).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by mwrock** [comment]
Hey this is super cool @burtlo . Thanks!!

**Pull request merged**
