### PR TITLE
Enable SSL and zlib support for core/python

### PR DESCRIPTION
**Pull request by scassiba**
Addresses #904 

Signed-off-by: Samuel Cassiba <s@cassiba.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @jtimberman and @fnichol to be potential reviewers

**Comment by smith** [comment]
Thank you!

gif-keyboard-4248790241981262239

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit a40757f has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit a40757f with merge 3bb6d43...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/138948297)

**Comment by smith** [comment]
This has been built and uploaded to the depot: https://app.habitat.sh/#/pkgs/core/python/3.5.1/20160620170847

**Pull request merged**
