### PR TITLE
Add API endpoints for updating and retrieving your profile

### PR DESCRIPTION
**Pull request by raskchanky**
This adds 2 API endpoints - one for retrieving your profile and one for updating it.  Right now, we only support updating your email address.  Other things might come later.  Here are some examples of it in action:

```shell
curl -v \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer [REDACTED]" \
http://localhost:9636/v1/profile
```

```shell
curl -v \
-X PATCH \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer [REDACTED]" \
-d '{"email": "johndoe@example.com"}' \
http://localhost:9636/v1/profile
```

tenor-75774397

Closes https://github.com/habitat-sh/habitat/issues/3866
Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by chefsalim** [comment]
LGTM.  One comment - we're using session id as an account id - not sure if/whether that changes as we migrate things over more fully to internal session tokens.

**Comment by raskchanky** [comment]
@chefsalim It's a good question. I'm not sure what it means once we migrate things over to our internal session tokens.  I'm sure a fair number of things will need to be changed, and it's entirely possible this is one of them.

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/292284973).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/292284973).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
