### PR TITLE
Add CPPFLAGS and CXXFLAGS to hab-plan-build

### LINKED ISSUE #926: issues building c++ stuff because no CXXFLAGS
To get MariaDB/Percona to build I need to set the following in my install script:

```
export CXXFLAGS="$CFLAGS"
```

habitat should probably do this for me :)

### PR DESCRIPTION
**Pull request by adamhjk**
This fixes #926 and #962. If no CPPFLAGS or CXXFLAGS have been set by
your dependent packages (which, as of now, no package has) then they
will become set to the value of CFLAGS.

When you build a new package, it will now set CPPFLAGS and CXXFLAGS
metadata to the value of pkg_include_dirs, just like CFLAGS. That means
as we rebuild packages, they will get new metadata files, and new
builds will honor the metadata rather than draft of CFLAGS.

The side effect is that current packages will Just Work (tm), while
packages that set explicit CPPFLAGS or CXXFLAGS in their plans will
now have the values embedded into their package, making the linking
work correctly.

gif-keyboard-6275459144357838229

Signed-off-by: Adam Jacob <adam@chef.io>

### CODE REVIEW

**Comment by adamhjk** [comment]
This could use both a review and some real-world testing. Paging @miketheman and @stevendanna, who I think had this issue. You should be able to try this out by checking out the habitat source, doing 'make shell', then 'studio enter' from the src directory. Rather than `hab pkg build`, try doing:

`components/plan-build/bin/hab-plan-build.sh plan/YOURPLAN`

To build your plan.

**Comment by reset** [comment]
@adamhjk looks like an easy, straightforward addition!

gif-keyboard-3494451331950561715

**Comment by adamhjk** [comment]
@thesentinels delegate=miketheman

**Comment by thesentinels** [comment]
:v: @miketheman can now approve this pull request

**Comment by miketheman** [comment]
@adamhjk I can confirm that this now passes flags along:
```
...
   llvm: Setting CFLAGS=-I/hab/pkgs/core/glibc/2.22/20160612063629/include -I/hab/pkgs/core/cmake/3.5.2/20160612153830/include -I/hab/pkgs/core/gcc/5.2.0/20160612064854/include -I/hab/pkgs/core/make/4.1/20160612080650/include -I/hab/pkgs/core/python2/2.7.11/20160620182552/include -I/hab/pkgs/core/python2/2.7.11/20160620182552/Include -I/hab/pkgs/core/zlib/1.2.8/20160612064520/include
   llvm: Setting CXXFLAGS=-I/hab/pkgs/core/glibc/2.22/20160612063629/include -I/hab/pkgs/core/cmake/3.5.2/20160612153830/include -I/hab/pkgs/core/gcc/5.2.0/20160612064854/include -I/hab/pkgs/core/make/4.1/20160612080650/include -I/hab/pkgs/core/python2/2.7.11/20160620182552/include -I/hab/pkgs/core/python2/2.7.11/20160620182552/Include -I/hab/pkgs/core/zlib/1.2.8/20160612064520/include
   llvm: Setting CPPFLAGS=-I/hab/pkgs/core/glibc/2.22/20160612063629/include -I/hab/pkgs/core/cmake/3.5.2/20160612153830/include -I/hab/pkgs/core/gcc/5.2.0/20160612064854/include -I/hab/pkgs/core/make/4.1/20160612080650/include -I/hab/pkgs/core/python2/2.7.11/20160620182552/include -I/hab/pkgs/core/python2/2.7.11/20160620182552/Include -I/hab/pkgs/core/zlib/1.2.8/20160612064520/include
...
```

I don't have any deps that are passing variables along from one build to the next, so all lines are equivalent.

What doesn't make 100% sense is that there is a `CFLAGS` and `CPPFLAGS` file in the $pkg_prefix. but no `CXXFLAGS` file in the resulting package.

Why would I have one and not the other?

**Comment by hexsel** [comment]
Mostly unrelated to this, but I was reading the header for the plan file and it mentions that a plan file is "like a cross of an rpm spec and a Dockerfile", but it's also missing the "docker compose"/docker-compose.yml aspect of it, it's actually what I found the deal maker...

**Comment by adamhjk** [comment]
@hexsel that feels pretty completely un-related :) Also, I'm not sure in what way a habitat plan maps to compose - typically, compose lets you put together a number of different containers, their links, etc. Habitat would make the services inside those containers easier to build and manage, but you would still want something like compose to put them all together. Yes?

**Comment by adamhjk** [comment]
@miketheman nice catch - there was a bug in the code that writes out the CXXFLAGS file. Should be fixed, and you should be gtg to r+ this when you're satisfied.

@thesentinels delegate=miketheman

**Comment by thesentinels** [comment]
:v: @miketheman can now approve this pull request

**Comment by stevendanna** [comment]
Just tested this locally for my case as well.  Looks good to me, thanks!

**Comment by adamhjk** [comment]
@thesentinels r+ 

Stealing @miketheman's potential thunder.

**Comment by thesentinels** [comment]
:pushpin: Commit 62faa09 has been approved by `adamhjk`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 62faa09 with merge 9081c0a...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139849014)

**Comment by fnichol** [comment]
Lovely addition, don't know why I didn't think of this for every plan that involved c++ code.

**Comment by miketheman** [comment]
My thunder has been stolen due to being busy with other things! 
Thanks for the fix @adamhjk - glad I could help debug.
t3icrlr

**Comment by hexsel** [comment]
@adamhjk I suppose you're the one that knows, but it does seem, to me, like there's some overlap. It manages the link between applications, manages the service discovery for you. Sounds like a lot of the functionality on docker-compose.

**Pull request merged**
