### PR TITLE
Emphasize GitHub App installation

### LINKED ISSUE #3664: [builder ui] Emphasize GitHub App installation
In order to connect a plan to the Build Service, you must first install the Habitat Builder GitHub App. Missing this step will result in error messages and likely confusion, so we'd like to better emphasize this required step in the on-screen instructions.

### To-dos

- [x] Update instructions copy and add button on first step of connecting a plan (mockups below)
- [x] Update the validation messages for both confirmed and errored states (below the text input)
- [x] Add a sidebar with additional help text

### Mockups
[Mockup of repo found](https://chef.invisionapp.com/share/27DQCRSFX#/249855432_create_Package)
[Mockup for invalid repo](https://chef.invisionapp.com/share/ATDV3G25G#/257397776_create_Package_Error)

### PR DESCRIPTION
**Pull request by cnunciato**
This updates some copy and makes the call to action clearer. Also adds a sidebar with instructions and handy links and includes a fix for handling plans without any packages (so no “Supported Platforms”) yet.

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

Fixes #3664.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
cc @ryankeairns

**Comment by ryankeairns** [comment]
adde9b7b-2198-4758-b7bb-9461045a5cc4

**Comment by reset** [comment]
tenor-102986835

**Comment by ryankeairns** [comment]
Fixes #3563

**Pull request merged**
