### PR TITLE
Homepage fixes

### PR DESCRIPTION
**Pull request by magwalk**
- fixes font rendering issues in Github banner
- moves CTA buttons up higher on the page

screen shot 2017-02-16 at 3 11 26 pm

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by eeyun** [comment]
looks great @maggiewalker . There was one other thing I think

source/index.html.slim has a small typo in it:
```
136 p.home--icon-code $ EDITOR plan.sh
```
Should actually be
```
136 p.home--icon-code $ $EDITOR plan.sh
```

**Comment by eeyun** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/202445242).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/202445242).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/202445242).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/202445242).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by apriofrost** [comment]
Thanks @magwalk so much for doing an amazing work! 
There are a few fixes I would suggest for the live site:

image
- When viewing the site on my Chrome, there is an extra white stripe under the logo boards. It seems to be the scrolling bar that is hidden - it splits into two parts when the browser width is reduced to a breakpoint.
- This is totally my neglect: the shadow under the tree icon on the right is missing. I'm going to send @magwalk the new asset files to fix it.
- The two shadow areas behinds the logos are also missing. I'm going to send that files to @magwalk as well.


image
- It will be good to add an extra line of space above the 'run', making it less clustered with the paragraphs above that are not directly related to 'run'.

image

- In the desktop view, it will look more visually balanced when the two boxes share the same height. Same to the consistent vertical distance between each chunk of small title + paragraph.

image

- In the footer, it will be good to remove the shadow under the button 'Try Habitat Now'. We've removed the bold button shadow from the former design in the rest of the page to keep an overall flat visual style, so it will be good to keep them consistent across the page.

image

- In the footer, the space below the '© 2017 Chef Software, Inc. All Rights Reserved. Patent Pending.' seems too high. It will be good to reduce it to close to the legal copy.

**Pull request merged**
