### PR TITLE
update copyright headers

### PR DESCRIPTION
**Pull request by metadave**

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @smith, @reset, @fnichol, @ryankeairns and @adamhjk to be potential reviewers

**Comment by fnichol** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 2aad51f has been approved by `fnichol`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 2aad51f with merge db0455d...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26781320)

**Pull request merged**
