### PR TITLE
Update to latest ZeroMQ crate

### PR DESCRIPTION
**Pull request by reset**
* Swap off of my personal fork to the canonical repository. We have been
  granted commit access and will collaborate there from now on
* Remove explicit ZeroMQ socket closes - these are now automatically
  handled by the Socket's drop trait
* Update Builder component plans to find libzmq at build time

### CODE REVIEW

**Comment by fnichol** [comment]
Hopefully a rebase against master should clear the CI failure. Otherwise, looks like a nice cleanup--merge when ready!

**Comment by reset** [comment]
@fnichol It didn't, but I'll re-run the job and see if it clears

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/165382281).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/165382281).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
