### PR TITLE
Revert "Fix travis deploy for PRs redux"

### PR DESCRIPTION
**Pull request by mwrock**
Reverts habitat-sh/habitat#2236

### CODE REVIEW

**Comment by mwrock** [comment]
see https://travis-ci.org/habitat-sh/habitat/jobs/230542984 I've been thinking of another route that does not change the travis yaml.

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/230548597).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/230548597).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by mwrock** [comment]
So sorry @georgemarshall for the hassle. I've noticed that its almost impossible to test the final 3% of the deployment run without doing an actual deployment.

**Pull request merged**
