### PR TITLE
Set PATH metadata file to only contain my bin dirs

### PR DESCRIPTION
**Pull request by elliott-davis**
Signed-off-by: Elliott Davis <elliott@excellent.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by elliott-davis** [comment]
This is mostly here as a place-holder. Feel free to close if this isn't even close @fnichol

**Comment by fnichol** [comment]
Okay, this appears to be a safe change in islolation, given that we current have logic that favors `RUNTIME_ENVIRONMENT` in places where that and `PATH` could exist. It further make newly built packages free themselves on binlinking issues so there is a way for folks to built themselves out of the issue they are seeing (if building is reasonable)

References habitat-sh/builder#240

**Comment by christophermaier** [comment]
tenor-154658709

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/351438943).

**Comment by fnichol** [comment]
Nice, thanks all!

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/351438943).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
