### PR TITLE
Unify `make bldr-run` Makefile target to work on native Linux & Mac.

### PR DESCRIPTION
**Pull request by fnichol**
This change brings the 2 Procfiles into one version that should work under most circumstances under Linux and Mac. The notable exception is for systems that already have a `redis-server` process running, such as a Homebrew-installed package on macOS or a system-installed package on Ubuntu for example.

The 2 remaining Makefile targets are:

* `bldr-run` - which launches the Builder services necessary for developing against. By default on the Mac this will run in a devshell using Docker and will be run natively on Linux without Docker.
* `bldr-shell` - which launches a devshell (i.e. a Docker container) with forwarded ports but doesn't run any of the services

As the `BUILDING.md` instructions describe how to work natively on Mac (i.e. not using Docker but targeting macOS directly), you can set `export IN_DOCKER=false` for `make bldr-run` to compile and run on the Mac.

The driving user feature for this change was to be able to run `make bldr-run` on a Linux host without needing to resort to the same bind mount/Docker overhead which slows down the development cycle.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

gif-keyboard-10465326414260578854

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/189311788).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/189311788).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
