### PR TITLE
Display active build messaging across package tabs

### LINKED ISSUE #3107: Display the active-build message across package tabs
Concerning this, which advises that a build is currently happening:

image

* [x] Pull its functionality into a proper component
* [x] Display it across all package tabs
* [x] Support dispatched, pending and processing statuses
* [x] Only show the Build button for packages with projects 
* [x] Disable the Build button in the sidebar while a build is running
* [x] Poll to detect when a build has completed, so the user can be notified in place

### PR DESCRIPTION
**Pull request by cnunciato**
This change extracts the message that indicates a running build into a new component and displays that component across all package views. It also:

* displays the build button for linked projects only,
* disables the button when a build is already underway, and
* fixes an icon rendering bug with a glorious monkeypatch.

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

Fixes #3107.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/273437987).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/273437987).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
