### PR TITLE
Exclude sandbox channels from recommendations when installing packages

### PR DESCRIPTION
**Pull request by raskchanky**
Right now, when you run `hab pkg install` and it doesn't find the package you specified in the channel you specified (or the `stable` channel if you didn't specify a channel), `hab` will pull a full list of channels for the origin in question and try to find the package you want in every one of those channels. The goal here is to provide the user with some helpful feedback.  The problem is that sandbox channels (beginning with `bldr-`) are included in that list by default, which is not what we want. The sandbox channels aren't useful or interesting to end users.

This change adds an option to exclude sandbox channels from the channel list for an origin and enables it by default.  If, for some reason, you need those sandbox channels in a channel list, you can still get them by passing `?sandbox=true` to the channel list API URL.  By default, though, they're hidden.

tenor-259237633

Closes https://github.com/habitat-sh/habitat/issues/3755
Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
Being in a different time zone is the best. I just wake up to a bunch of killer work that I can't wait to push to release/push to live 😄 

tenor-192091614

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/289798975).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/289798975).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
