### PR TITLE
Suitability

### LINKED ISSUE #1767: Elect 'healthiest' follower when leader goes down
When running clustered statefull services where follower nodes count on streaming replication to sync with a leader node we want to elect the follower that is 'furthest along' as the new leader.

Are there any thoughts as to how this can be achieved? Either as a work around or supported in the core. I'd be happy to brainstorm and hack on a solution.

### PR DESCRIPTION
**Pull request by bodymindarts**
Add support for `suitability` hook.
By printing a parsable u64 as the last line of stdout this hook allows services to report a priority by which they should be elected the new leader when an election is initiated.

Closes #1767 

Also all output from running hooks is streamed to 
```
{{pkg_svc_path}}/logs/<hook>.stdout.log
```
 and 
```
{{pkg_svc_path}}/logs/<hook>.stderr.log
```

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by bodymindarts** [comment]
Unfortunately I could not verify the working end-to-end due to https://github.com/habitat-sh/habitat/issues/1818.

The PR I had open before the hooks refactoring from @reset was working fine and the code is mostly ported so I have no reason to believe this is not working as expected.

**Comment by reset** [comment]
gif-keyboard-8898726304316569699

@bodymindarts perfect!

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/205078686).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/205078686).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
