### PR TITLE
Corrected spelling of Marc's name.

### PR DESCRIPTION
**Pull request by juliandunn**

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk and @ryankeairns to be potential reviewers

**Comment by ryankeairns** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit a215618 has been approved by `ryankeairns`

**Comment by juliandunn** [comment]
It's a dupe of #908 so we don't need this now.

**Pull request closed without merging**
