### PR TITLE
Add nginx-builder-api to configure an nginx service

### PR DESCRIPTION
**Pull request by jtimberman**
Signed-off-by: jtimberman <joshua@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @reset to be a potential reviewer

**Comment by reset** [comment]
@jtimberman I think that's basically all you gotta do since you've already got the plan in the source tree, good work!

**Comment by reset** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit a4d0884 has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit a4d0884 with merge 4be5bbb...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139038292)

**Pull request merged**
