### PR TITLE
don't allow duplicate invites

### PR DESCRIPTION
**Pull request by metadave**
damn, I wrote some TypeScript

Fixes https://github.com/habitat-sh/habitat/issues/835

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @smith and @reset to be potential reviewers

**Comment by reset** [comment]
@thesentinels r+

gif-keyboard-3983345365987851309

**Comment by thesentinels** [comment]
:pushpin: Commit 68371bd has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 68371bd with merge c4df0e4...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26893159)

**Pull request merged**
