### PR TITLE
Removing license boiler plate.

### PR DESCRIPTION
**Pull request by Themodestduckling**
Is this the right way to do it?
I am trying to help with issue #6286

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@Themodestduckling Yes, exactly! Thank you so much for this 🎉 

One other thing to be aware of: we do have a policy that requires that all contributions have a Developer Certificate of Origin (DCO). This boils down to having a line like the following in each commit message:

```
Signed-off-by: Joe Smith <joe.smith@email.com>
```
Further details on our DCO policy can be found [here](https://github.com/habitat-sh/habitat/blob/master/CONTRIBUTING.md#signing-your-commits).

**Comment by Themodestduckling** [comment]
Hey there! Sorry for not responding promptly, I will continue working on it
today.
Thank you

**Comment by Themodestduckling** [comment]
Hey I'm still working on this :) I will try to get it finished as soon as possible.

**Comment by Themodestduckling** [comment]
I think I am all finished removing licence boiler plates from the code :)

**Comment by baumanj** [comment]
@Themodestduckling: are you still interested in completing this PR? Let us know if you need any assistance getting this to a mergeable state.

**Comment by baumanj** [comment]
Hey @Themodestduckling, this PR is so close to being mergeable. Are you going to be able to complete it in the foreseeable future, do you think?

**Comment by christophermaier** [comment]
@Themodestduckling How are things going? Need any assistance?

**Comment by baumanj** [comment]
Since we haven't heard from @Themodestduckling in over 6 weeks, I'm inclined to call this abandoned. I'll create a separate PR (since I can't push to one based on a non-`habitat-sh` org) and try to retain as much of the work as I can.

**Comment by baumanj** [comment]
Superseded by https://github.com/habitat-sh/habitat/pull/6563 due to lack of author activity

**Pull request closed without merging**
