### PR TITLE
nsswitch.conf required for name resolution in studio

### LINKED ISSUE #2317: Contents of /etc/hosts does not resolve.
- hab 0.22.1/20170509234454
- CentOS 7 (Linux 3.10.0-514.16.1.el7.x86_64)

Observation:
After entering the habitat studio it is not possible to resolve hostnames contained within /etc/hosts. The same hostnames can be resolved outside the studio.

Expectation:
Entries in the host machine's /etc/hosts should be resolvable within the habitat studio.

Example:
https://asciinema.org/a/5200a4tvjkd0d5c2bdw3nrzyx

### PR DESCRIPTION
**Pull request by eeyun**
Resolves #2317 last bit of content we need to have name resolution work consistently in the studio

Signed-off-by: eeyun <ihenry@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
Great investigation work @eeyun

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/260376105).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/260376105).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
