### PR TITLE
New blog post: Packaging Drupal

### PR DESCRIPTION
**Pull request by therealpadams**
This PR provides a blog post about my experiences in producing Drupal packages for Habitat. It is a reposting of: http://baggerspion.net/2017/05/drupal-twice/

Signed-off-by: Paul Adams <paul@baggerspion.net>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by eeyun** [comment]
One note @therealpadams if you'd like your name and an author bio to show up beneath your blog post you'll need to add your info here: https://github.com/habitat-sh/habitat/blob/master/www/data/author_bios.yml

**Comment by therealpadams** [comment]
I wondered where those came from; not documented in the "Hello World" blog post!
Basic biography added now. I was unsure, but I assumed that the bio is looked-up by name... I simply followed the same structure as the other authors in the file.

**Comment by reset** [comment]
tenor-178931215

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/233455860).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/233455860).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
