### PR TITLE
setup builder-depot to run unit tests with fake data

### PR DESCRIPTION
**Pull request by mwrock**
This creates a `TestableBroker` that can allow database calls to be faked with canned responses and also records the requests so one can validate their properties if thats important.

Its not the intent of this PR to write tests for all existing handlers but it should now be easy to write tests moving forward. Here is one test example:

```
    #[test]
    fn list_public_keys() {
        let mut broker: TestableBroker = Default::default();

        let mut access_res = CheckOriginAccessResponse::new();
        access_res.set_has_access(true);
        broker.setup::<CheckOriginAccessRequest, CheckOriginAccessResponse>(&access_res);

        let mut origin_res = Origin::new();
        origin_res.set_id(5000);
        broker.setup::<OriginGet, Origin>(&origin_res);

        let mut key_res = OriginPublicKeyListResponse::new();
        let mut keys = protobuf::RepeatedField::new();

        let mut key = OriginPublicKey::new();
        key.set_name("my_name".to_string());
        key.set_revision("my_rev".to_string());
        keys.push(key);

        let mut key2 = OriginPublicKey::new();
        key2.set_name("my_name2".to_string());
        key2.set_revision("my_rev2".to_string());
        keys.push(key2);

        key_res.set_keys(keys);
        broker.setup::<OriginPublicKeyListRequest, OriginPublicKeyListResponse>(&key_res);

        let response = iron_request(method::Get,
                                    "http://localhost/origins/org/keys",
                                    "",
                                    Headers::new(),
                                    broker);
        let result_body = response::extract_body_to_string(response.unwrap());

        assert_eq!(result_body,
                   "[\
            {\
                \"origin\":\"my_name\",\
                \"revision\":\"my_rev\",\
                \"location\":\"/origins/my_name/keys/my_rev\"\
            },\
            {\
                \"origin\":\"my_name2\",\
                \"revision\":\"my_rev2\",\
                \"location\":\"/origins/my_name2/keys/my_rev2\"\
            }\
        ]");
    }
```

There were a few disappointments in writing this. I REALLY wanted the `TestablrBroker` and `BrokerConn`  to be polymorphic using a `trait object`. If that were possible, we could simply feed to the iron request `extensions` a `Broker` trait and at test time, use a `TestableBroker` instead of a `BrokerConn`. Unfortunately, trait objects cannot have generic types. I went down several other experiments but settled for using another struct alltogether and having a function in `server.rs` that calls `route` on the appropriate one.

Also, the `iron-test` crate does not allow one to inject extensions into the request so I cargo culted some of its code to be able to do that.

If we find ourselves using `TestableBroker` elsewhere, we should move it somewhere more centralized but its current location seems fine.

Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
A couple other things to note on this PR:

1. I had merge conflicts with the top level Cargo.lock and so I just regenerated it. Thats why there are several updates but feels like its the right thing to do unless it busts the build.
2. Calling `request.extensions.get_mut` means that all other immutable `get` calls to extensions needed to be in a different scope. Much of the churn in server.rs was around that.

**Comment by reset** [comment]
@mwrock this is seriously good work - everyone will appreciate being able to leverage this in our testing! We should expand this into the `builder-api` and `builder-admin` in the future and use this to do full integration tests ;)

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/215116949).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/215116949).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
