### PR TITLE
Add Hab API docs

### PR DESCRIPTION
**Pull request by IanMadd**
Signed-off-by: IanMadd <imaddaus@chef.io>

This will add Builder and Supervisor API docs

### CODE REVIEW

**Comment by kagarmoe** [comment]
This is not the change you're looking for:

Screen Shot 2020-10-30 at 4 32 37 PM

**Comment by IanMadd** [comment]
I've got merge a couple PRs in Automate and chef-web-docs before that's not an issue.

**Comment by kagarmoe** [comment]
Let me know when it is ready

**Comment by mjingle** [comment]
@IanMadd I also noticed that the browser tab for the API docs says "Chef Automate API Documentation."

**Comment by IanMadd** [comment]
Fixed the page title problem with chef/chef-web-docs#2738

**Review by mjingle — APPROVED** [review]
tenor-132382020

**Pull request merged**
