### PR TITLE
Allow sourcing of /src/.studiorc to set hab env vars

### PR DESCRIPTION
**Pull request by bdangit**
- modified profile to source `/src/.studiorc`
- added documentation on how to customize your studio

-----

This enables the following use cases:
- Set hab env vars that are only available inside studio. (ie. `HAB_AUTH_TOKEN` and `HAB_DEPOT_URL`)
- Be able to personalize the studio for own dev workflow

Signed-off-by: Ben Dang <me@bdang.it>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@bdangit I think this is a nice addition for interactively hacking on a plan and customizing the environment for that plan. I think we should make a few changes before merging in

* Promote this in the docs somewhere. This feature will become a hidden escape hatch for only the people who've read the codebase
* Use a lesser known name for the environment file which is more specific to Habitat - maybe `.studiorc` instead of `.bashrc`? This will at the very least hint to an end-user to search for what this file is for in the docs

**Comment by bdangit** [comment]
Ah great feedback. I like `.studiorc`.  I'll come up with another commit in regards to this.

**Comment by bdangit** [comment]
@reset updated the commit as suggested.

**Comment by reset** [comment]
@bdangit this looks great, thank you for making those changes!

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/171474739).

**Comment by smurawski** [comment]
Thanks @bdangit

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/171474739).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
