### PR TITLE
Added plan for logstash

### PR DESCRIPTION
**Pull request by elliott-davis**
Please note this depends on the jruby1 pull request (#992)

Signed-off-by: Elliott Davis <edavis@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by smith** [comment]
@thesentinels r+

looks great!

gif-keyboard-10524845481765897722

**Comment by thesentinels** [comment]
:pushpin: Commit d3826d4 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit d3826d4 with merge 1fd77c3...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/140867265)

**Comment by smith** [comment]
Built and uploaded to depot https://app.habitat.sh/#/pkgs/core/logstash/2.3.3/20160628175751

**Pull request merged**
