### PR TITLE
Redirect /docs/try to /tutorials/download

### LINKED ISSUE #3349: Add redirect
Currently a handout at conferences lists "download habitat" at habitat.sh/docs/try, which doesn't exist. We need to add a redirect to https://www.habitat.sh/tutorials/download/

We will update the cards on the next printing so this redirect doesn't have to live forever.

This is reasonably high priority since it's leading to a broken link on marketing materials handed out at all conferences.

### PR DESCRIPTION
**Pull request by cnunciato**
Signed-off-by: Christian Nunciato <cnunciato@chef.io>

Fixes #3349.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/280182013).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/280182013).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by cnunciato** [comment]
http://www.acceptance.habitat.sh/docs/try

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/280190951).

**Comment by tashimi** [comment]
tenor-185695550

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/280190951).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
