### PR TITLE
Add advanced plan writing guide

### PR DESCRIPTION
**Pull request by tashimi**
Signed-off-by: Tasha Drew <tasha.drew@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
tenor-198956901

**Comment by themightychris** [comment]
`The value of name should exactly match the name of the project it represents ` @tashimi could you elaborate on what, if any, are the exceptions to this? e.g. projects with explicit caps or spaces/hyphens in the same? A lot of xorg projects have weird but significant caps and i've seen people do a few different things with them

**Comment by tashimi** [comment]
@themightychris These are guide rails rather than absolutes, but I would say do what you need to do to clearly communicate the original source of the project and software so that a user can read your plan and be sure it represents what they're looking for, and that they don't need to go build a new one because it already exists

**Comment by themightychris** [comment]
@tashimi none of the core plans have caps though, could these docs say for sure one way or the other whether caps are intended to be ok? It will be valuable if there's ever an issue with caps being preserved to be able to say "that needs to be fixed" or "you never should have started using caps in your plan names"

See https://bldr.habitat.sh/#/pkgs/xorg

**Comment by reset** [comment]
@themightychris using capital letters is fine and we'll always preserve capitalization for a display name. Packages are stored in a case-insensitive way so `MYPACKAGE` and `mypackage` should be the same package. We haven't put in the work yet to ensure search is case-insensitive but I'm sure we'll take a pass at search in the future

**Pull request merged**
