### PR TITLE
Added missing word (bare) in home page hero copy

### PR DESCRIPTION
**Pull request by TrevorBramble**
:bear: :metal:

Signed-off-by: Trevor Bramble <tbramble@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @magwalk, @smith, @ryankeairns, @davidwrede and @cwebberOps to be potential reviewers

**Comment by smith** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 3139147 has been approved by `smith`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 3139147 with merge 2cb40e8...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139561069)

**Pull request merged**
