### PR TITLE
Add target support so Windows packages work

### PR DESCRIPTION
**Pull request by raskchanky**
This is the companion PR that's required to make https://github.com/habitat-sh/builder/pull/453 work.

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
I'm probably missing something super basic, but what scenario is currently broken?

**Comment by chefsalim** [comment]
Looks great!  Since you're in this code, it would be awesome to either fully plumb in the target for the install path as well (or do a fast follow to add that).

tenor-52312291

**Comment by raskchanky** [comment]
@chefsalim sure I can do that

**Comment by raskchanky** [comment]
@chefsalim Can you be a bit more specific about what you're looking for?  A cursory glance through the package install code doesn't show any obvious places to plumb the target into.

**Comment by chefsalim** [comment]
@raskchanky the install path is still passing in None for target.. so we still depend on the user agent formation in the Api Client to set the target for the back end.  If we start plumbing in the target explicitly, it lets us get out of the user agent dependency entirely at some point.  It's not a huge deal as things will still work with your code as is, but it might be nice to add that capability now.  If we wanted to be extra bold, we could add a target to the hab install command itself as well as an option. It could then give us the ability to force install a package for a different architecture - for example, if we wanted to just do a download, or there was a script only or non-binary package that we just wanted assets from, etc - there could be a bunch of future scenarios.

**Comment by raskchanky** [comment]
@chefsalim I feel like I'm missing something.  Unless we do your suggestion of adding `--target` or something similar to the `hab pkg install` command, where else would we get the target from, if not from the `ApiClient` user agent?  Technically we could call out to `uname` or similar, but that's all `ApiClient` does.

**Comment by chefsalim** [comment]
@raskchanky Yeah we'd do exactly one of those two things - pull uname up front, and/or add the --target.  If this is getting to be too much/complicated, we can table it for now..

**Comment by chefsalim** [comment]
Sorry didn't mean to close the PR!

**Comment by raskchanky** [comment]
I think I'll leave it for now, since adding `--target` to `hab pkg install` is a little out of scope for this PR, and there's no need for an explicit call to `uname`, since that's what `ApiClient` does to get the value for its `UserAgent` header that we're already using.  Thanks for the suggestions!

**Comment by chefsalim** [comment]
👍

**Pull request merged**
