### PR TITLE
tweak elb settings for gateways

### PR DESCRIPTION
**Pull request by reset**
Signed-off-by: Jamie Winsor <jamie@vialstudios.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @adamhjk to be a potential reviewer

**Comment by reset** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit f20ab90 has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit f20ab90 with merge 29b7584...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.com/habitat-sh/habitat/builds/26780229)

**Pull request merged**
