### PR TITLE
[blog] Add post detailing base plans refresh 2019-01-22

### PR DESCRIPTION
**Pull request by smacfarlane**
This adds a blog post about the upcoming base-plans refresh.  

Adding a T-DO-NOT-MERGE label until we commit to the date.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by smacfarlane** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
Hey, @smacfarlane - you don't have permission to issue `deploy` on this pull request.

Nope

**Comment by smacfarlane** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
Sorry; I had a problem deploying this change to acceptance. The error was:

```ruby
Expected process to exit with [0], but received '128'
---- Begin output of git reset --hard 367fda83b139f8246e9d7b55561b5b8faa653e26 ----
STDOUT: 
STDERR: fatal: Could not parse object '367fda83b139f8246e9d7b55561b5b8faa653e26'.
---- End output of git reset --hard 367fda83b139f8246e9d7b55561b5b8faa653e26 ----
Ran git reset --hard 367fda83b139f8246e9d7b55561b5b8faa653e26 returned 128
```

Oops

**Pull request closed without merging**
