### PR TITLE
Adds lefthand side nav to demos

### LINKED ISSUE #4682: Improve demo intro and navigation
During user testing, we noted a few consistent pieces of feedback with regards to the Learn page and demos:
- users were not sure which demo to start with, though the presumed the first/left most box which is good but not required. We want users to pick the most interesting demo/topic based upon their personal needs.
- the purpose of each demo is not clearly stated up front "Why am I doing this again?"
- once in a demo, several testers stated that they would prefer to see the navigation links on the left hand side to a) serve as waypoints and see what's coming up and b) to come back and use this as a reference. Currently, the navigation (topics) are not visible - we have the orange tabs up top that indicate link, but do not inform on content.

### PR DESCRIPTION
**Pull request by ryankeairns**
Fixes #4682 

Based upon feedback from several usability test sessions, this PR clarifies copy in several spots and, more noticeably, adds a left-hand side nav to the demo layout.

In some steps I have gone with a single column layout for the content, while those with shorter content have retained their 2-column layout in order to keep the steps feeling shorter.

Signed-off-by: Ryan Keairns <rkeairns@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/347008871).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/347008871).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by ryankeairns** [comment]
🤔 Perhaps all the pages should be single column... the screenshots get pretty small when in a two-column layout. Curious people's thoughts... See here --> https://www.acceptance.habitat.sh/demo/packaging-system/steps/1/

**Comment by cnunciato** [comment]
Interesting yeah. On the one hand, the larger images are nice (a couple of them are hard to read at 50% width), but they do make each step feel "bigger" somehow.

**Comment by apriofrost** [comment]
I think it’s good to merge. In the future, we may consider changing the two column text content into just one - making them all look like the last step. It would leave more space for the image and the CLI commands: https://www.acceptance.habitat.sh/demo/packaging-system/steps/6/

**Comment by apriofrost** [comment]
I have one small nitpick for the color - the paragraph text seems not having enough contrast with the background, which makes it a bit hard to read. Could we increase the color brightness a bit? @ryankeairns image

**Comment by ryankeairns** [comment]
@apriofrost I've updated the copy under the main title to start with 'Choose any topic...' which was the main point of the subtitle text in the Habitat 101 section that you referenced. In turn, I've removed the light colored paragraph under that Habitat 101 divider.

Simply making that text brighter results in a lot of competing text on the screen, which is I why I've opted to go this route. Also, simpler is better :)

screenshot 2018-02-28 08 33 17

**Comment by ryankeairns** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/347297157).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/347297157).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by cnunciato** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/347397997).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/347397997).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
