### PR TITLE
Don't use Helm's dependencies feature

### PR DESCRIPTION
**Pull request by zeenix**
Until [the Helm bug](https://github.com/kubernetes/helm/issues/3632) to handle dependencies properly is resolved, let's not use the dependencies feature and ask users to install habitat-operator chart themselves.

***Please note:*** Merging this PR means that users of Helm exporter (or rather users of the the carts produced by the Helm exporter) will have to manually install the Habitat operator. We will want to update the docs/blog posts accordingly soon after we release this change.

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by christophermaier** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/353811717).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/353811717).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
