### PR TITLE
Start services using specified hab_svc_user on windows

### PR DESCRIPTION
**Pull request by mwrock**
Currently we do not honor `hab_svc_user` on windows. We start windows based services under the same account that the supervisor is running as. This PR launches services using the logon token of `hab_svc_user` if specified.

Because we need to generate a logon token for the user, we need the logon credentials of that user and also need to persist those credentials so that the supervisor can use them if it needs to restart the service or start a newly loaded service. We use DPAPI to encrypt the user password and store it in the service spec on disk. Both `hab sup start` and `hab sup load` will take a `--password` parameter and store it in the spec. The password can only be decrypted by the hab binary as long as it is compiled with an additional byte array that provides added entropy to the encryption. If no byte array is provided at compile time, the passwords could feasibly be decrypted as long as the decryption is attempted on the same machine where the password was encrypted. We are storing a production byte array in base64 format in our password vault and passing to the appveyor build via a secure environment variable.

In order to start services using another user's logon token, the account  running the supervisor must have the `SE_INCREASE_QUOTA_NAME` and `SE_ASSIGNPRIMARYTOKEN_NAME` privileges assigned. The supervisor will validate these privileges are assigned and will return an error stating which is missing when attempting to start services with lacking privileges.

### CODE REVIEW

**Comment by mwrock** [comment]
Note that this is "mostly" working now. The following needs to occur before merge:

- [ ] Format and rebase with current master
- [ ] Cleanup all the new FFI (its a total mess) and move it out of `windows_child.
- [ ] Create a propper environment block for the environment variables. The current logic just inherits all vars from the supervisor user
- [ ] Implement the password encryption and decryption DPAPI calls
- [ ] Add a "secret" byte string to 1password and the appveyor secret vars. We'll use this to "add complexity" to the encryption so that ONLY hab can ever decrypt the passwords

**Comment by mwrock** [comment]
fixes #2125

**Comment by mwrock** [comment]
Just made a small but important change based on some more testing I did today: We now specify `LOGON32_LOGON_SERVICE` when generating the logon token for `hab_svc_user` this allows the service to run with full admin privileges (if the user is an administrator). Otherwise, the service could possibly encounter errors when performing admin operations.

This means that `hab_svc_user` must have this right assigned to it. If creating the process results in an error due to this right missing, we will return an error clearly stating what logon right needs to be granted to the user.

**Comment by reset** [comment]
@mwrock this looks great! Resolve the lockfile conflicts and merge it in!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/250588499).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/250588499).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
