### PR TITLE
A PR to preview what habitat.sh will look like with branding from community.chef.io

### PR DESCRIPTION
**Pull request by chefjiajia**
Main changes: 
- Changed the navbar to resemble that of community.chef.io
- Colors, e.g., links, footer

### CODE REVIEW

**Comment by kagarmoe** [comment]
@chefjiajia How do I build this? Thanks!

**Comment by chefjiajia** [comment]
@kagarmoe 
In the habitat/www dir, `bundle exec middle server `should do the trick. If you have issues with versions on local the README might be helpful - or ping me on Slack!

**Comment by kagarmoe** [comment]
I've been out for a bit, could you bring me up to speed/refresh my memory? Is this just a demo of the new site on Middleman, or is the new site actually on Middleman?

**Comment by kagarmoe** [comment]
We need to change the use of magenta in headers and on buttons. The accepted convention for the vivid red family in information is that it is reserved for critical warnings.
Screen Shot 2020-06-23 at 1 37 48 PM

A good example of "NotThis!" magenta vs "GoodThing" is: 

Screen Shot 2020-06-23 at 1 41 30 PM

**Comment by chefjiajia** [comment]
@kagarmoe This will be the actual site that's live! It'll be temporary -- once the Hab docs are fully migrated, we'll redirect the site completely. 

I've reverted the pink to the original Habitat teal. Will bring this up with Creative as well - we probably want to change the fuchsia if we'd like to consolidate with Docs branding in the future. Thanks for the reminder.

**Comment by kagarmoe** [comment]
The Chef Habitat link in the top-nav 404s. Should we send it to this GH repo? https://github.com/habitat-sh/habitat

**Comment by chefjiajia** [comment]
@kagarmoe The goal is to launch the new Habitat page right before so that link would work properly. Here's the page in staging:

https://5ef14a431766bb00072903a9--chef-dev.netlify.app/products/chef-habitat/

**Comment by chefjiajia** [comment]
@sdelano Updated the font issue on Safari - if the team has no other outstanding items, should be good to go for Monday's launch!

**Pull request merged**
