### PR TITLE
Fixes homepage scripts and in turn fixes css rendering

### PR DESCRIPTION
**Pull request by ryankeairns**
After deploying the blog, we noticed that the home page styles weren't rendering correctly and there was a javascript error.

After digging into it, the issue was related to an issue with how javascript files are dynamically included in middlemanapp via middlemanapp-sprockets. Researching indicated that if you point at a newer version of middleman-sprockets that the javascript require functionality would work again... and so it did.

The only side effect was that it no longer could handle the radial gradient backgrounds that we were using on the home page, so I had to make some very minor tweaks to those css rules (removing an unrecognizable parameter).

Signed-off-by: Ryan Keairns <rkeairns@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/232631818).

**Comment by reset** [comment]
tenor-36742729

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/232631818).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by ryankeairns** [comment]
Notes for a future-proof fix:

https://forum.middlemanapp.com/t/how-to-add-javascripts-in-middleman-4/2689

Sprockets was removed from *middleman core*, to fix this we could continue using sprockets by:

- set to the last version `gem 'middleman-sprockets', '~> 4.1.0'` and activate it manually it in our config.rb with `activate :sprockets`
or, better yet
- use an external js build tool like webpack

**Pull request merged**
