### PR TITLE
Promote events and blog posts

### PR DESCRIPTION
**Pull request by nathenharvey**
On the community page:

* List slack before forums
* Add link to upcoming Habitat events
  * https://events.chef.io/events/categories/habitat/
* Add link to Habitat-related blogs
  * https://blog.chef.io/category/habitat/

Signed-off-by: Nathen Harvey <nharvey@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by nathenharvey** [comment]
habitat_-_community

**Comment by apriofrost** [comment]
Hi Nathen,
This is Liz. I'm currently working on the redesign of the community page with Jason L from the marketing team. There are some conflicts between the requirements. Let's find some time to sync on slack, and I could show you the latest mockup I'm working on.

**Comment by apriofrost** [comment]
After the discussion with Jason and Nathen, we've decided to move forward with the above design as the next step for now.

**Comment by eeyun** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/201999495).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/201999495).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
