### PR TITLE
tar windows package artifacts from a temporary directory

### PR DESCRIPTION
**Pull request by mwrock**
For some reason the 7z tar archiving via `-spf` does not produce an expandable archive that is readable by `hab pkg install`. By replicating the packages directory structure in the temp directory and taring that entire tree, `hab pkg install` is able to successfully install the generated `hart` file.

Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@mwrock I think this is perfectly fine but we should add a comment in the code to explain *why* we're doing it this way. This PR message will eventually get lost and we might save somebody some time in a year when they try to refactor this out ;)

**Comment by mwrock** [comment]
Good call @reset! Comment added.

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/188940245).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/188940245).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
