### PR TITLE
Improve client & server error reporting

### PR DESCRIPTION
**Pull request by reset**
This change will attempt to convert non-200 HTTP responses from the
Depot and API servers into a NetError which now implements
std::error::Error and is bubbled up back to the `hab` crate. These
errors contain a code and a message to help identify what exactly
went wrong with the users remote request.

Additional changes around erorr handling have been made as well. We
will now continue to validate already cached sessions even if the
GitHub API is down and we also report errors from their API more
gracefully.

There was quite a bit of work here so I would recommend a reviewer
to read each commit if they'd like a full understanding of what all went in
to this PR!

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by metadave** [comment]
+1

**Comment by reset** [comment]
@habitat-sh/habitat-core-maintainers this one could use one more look over, I made some additional changes and commits over my 3 hour flight back home. This should wrap things up and get us to a good place!

**Comment by eeyun** [comment]
Am I wrong that this PR also solves this open issue https://github.com/habitat-sh/habitat/issues/1105 ?

I realized last week this was opened before the discussion we had around cleaning up error handling related to the `401 Unauthorized` messages from users having the incorrect GH User Token scoping.

**Comment by raskchanky** [comment]
gif-keyboard-12704431809050293618

**Comment by raskchanky** [comment]
@eeyun It _looks_ like it would, but I'll defer to @reset for the final word on that.

**Pull request merged**
