### PR TITLE
Check expiry before doing calculations with it to avoid panicking

### LINKED ISSUE #2386: [builder-jobsrv] occasionally panics when starting jobs
The builder-jobsrv can occasionally panic when starting jobs.  This results is a "net:route:3" error.

Backtrace (Not very useful) below:

May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O): thread 'worker-manager' panicked at 'other was less than the current instant', /checkout/src/libstd/sys/unix/time.rs
:276
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O): stack backtrace:
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    0: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    1: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    2: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    3: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    4: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    5: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    6: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    7: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    8: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    9: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):   10: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):   11: start_thread
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):              at /hab/cache/src/glibc-2.22/nptl/pthread_create.c:334
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):   12: clone
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):              at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

### PR DESCRIPTION
**Pull request by raskchanky**
tenor-227446435

Fixes #2386 

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/249814170).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/249814170).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
