### PR TITLE
Update bootstrap script to install hab 0.7.0

### PR DESCRIPTION
**Pull request by jtimberman**
Signed-off-by: jtimberman <joshua@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @fnichol, @reset and @smith to be potential reviewers

**Comment by reset** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 0379a59 has been approved by `reset`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 0379a59 with merge 59de510...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139932564)

**Pull request merged**
