### PR TITLE
A few fixes for the supervisor

### LINKED ISSUE #1818: Rendering config is failing
With current master
```
$ hab sup start core/postgresql --group reference
hab-sup(MR): Butterfly Member ID 882060ebb5c14e5e8d53cafe367226c4
hab-sup(SR): Adding core/postgresql/9.6.1/20170215221136
hab-sup(MR): Starting butterfly on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
postgresql.reference(SR): Failed to write service configuration: hab-sup(ER)[src/error.rs:379:8]: Failed to encode TOML: values must be emitted before tables
```

Could this be due to @fnichol recent upgrade to the serialization libs?

### PR DESCRIPTION
**Pull request by smurawski**
Fix the eachAlive helper (guard against the condition where the `alive` key is not present, like at supervisor startup).

Fix the toml serialization in `toml 0.3.0` (https://github.com/alexcrichton/toml-rs/issues/145) by pinning to a commit off master.  We can revert the Cargo.toml commit and cargo update when a new release of toml is out.

Fixes #1818

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
gif-keyboard-4689751144824651477

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/205123772).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/205123772).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/205123772).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
