### PR TITLE
Clarify how to pass configuration updates

### PR DESCRIPTION
**Pull request by bdangit**
- passing in a stringified version of TOML is not clear anywhere.
- also made it clear that you have to update the version of the config
   apply

Signed-off-by: bdangit <me@bdang.it>

### CODE REVIEW

**Comment by thesentinels** [comment]
@bdangit, thanks for your PR! By analyzing the annotation information on this pull request, we identified @davidwrede, @cwebberOps, @leonhartX, @mattray and @ryankeairns to be potential reviewers

**Comment by metadave** [comment]
Thanks @bdangit!

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit b94b158 has been approved by `metadave`

**Comment by thesentinels** [comment]
:hourglass: Testing commit b94b158 with merge ce08e6b...

**Pull request merged**
