### PR TITLE
Rename windows queue for launcher steps

### PR DESCRIPTION
**Pull request by smacfarlane**
This updates the windows queue names in the launcher pipeline steps to match the updated queue names provided by our build infrastructure.  

Signed-off-by: Scott Macfarlane <smacfarlane@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by smacfarlane** [comment]
@tduffield all uses of `default-windows-privileged` I found have been corrected

**Comment by tduffield** [comment]
@smacfarlane you're right. I was acting on old information.

**Pull request merged**
