### PR TITLE
[docs] Typo fix: original -> origin

### PR DESCRIPTION
**Pull request by stevendanna**
Signed-off-by: Steven Danna <steve@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @cwebberOps, @ryankeairns, @jhedev, @davidwrede and @juliandunn to be potential reviewers

**Comment by juliandunn** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 04a1dd5 has been approved by `juliandunn`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 04a1dd5 with merge 17b2295...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139757129)

**Pull request merged**
