### PR TITLE
Add Google Custom Search to Docs

### PR DESCRIPTION
**Pull request by magwalk**
In response to a request to add search from Issue #1098

Signed-off-by: Maggie Walker <magwalk@gmail.com>

screen shot 2016-07-28 at 8 55 53 am

### CODE REVIEW

**Comment by thesentinels** [comment]
@magwalk, thanks for your PR! By analyzing the annotation information on this pull request, we identified @cwebberOps, @ryankeairns and @TrevorBramble to be potential reviewers

**Comment by cwebberOps** [comment]
Closes #1098 

@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 5c39d34 has been approved by `cwebberOps`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 5c39d34 with merge d04abe7...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/148082904)

**Pull request merged**
