### PR TITLE
Fixed typo and updated continuous delivery doc

### PR DESCRIPTION
**Pull request by davidwrede**
- Fixed typo in "Why Habitat" topic
- Updated Continuous Deployment topic to reflect Chef Delivery -> Chef Automate changes

### CODE REVIEW

**Comment by davidwrede** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 0c87c77 has been approved by `davidwrede`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 0c87c77 with merge 0c87c77...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/144214839)

**Pull request merged**
