### PR TITLE
Update the dev docs

### PR DESCRIPTION
**Pull request by cnunciato**
* Minor cleanups and clarifications
* Add a simple Vagrantfile for help getting started
* Re-enable the `web` process for use with `make bldr-run`, and handle conflicts stemming from shared node_modules
* Round out the builder-web setup instructions

Signed-off-by: Christian Nunciato <cnunciato@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
Closes #2511.

**Comment by raskchanky** [comment]
You mention running `builder-web` inside the VM but I don't think this PR modifies the `Procfile` to make that happen.

**Comment by raskchanky** [comment]
Other than my one comment, this looks great.  I still disagree that making `builder-web` part of `make bldr-run` with the rest of the API services is a good idea, but it's not a hill I'm interested in dying on.  If this is a more frictionless way for people to get up and running, then that seems worth it.

**Comment by raskchanky** [comment]
tenor-146318167

**Comment by cnunciato** [comment]
Ah, nice catch @raskchanky -- thanks.

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/240009582).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/240009582).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
