### PR TITLE
Made Handlebars example easier to understand

### PR DESCRIPTION
**Pull request by davidwrede**
Per discussion in Habichat #documentation channel, Handlebars example for followers in a leader-follower topology is now more clear.

Signed-off-by: David Wrede <dwrede@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/230036745).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/230036745).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by reset** [comment]
@davidwrede I don't believe that this is more clear, this was part of the changes that I recently made to the templating language. The `with` helper inherits the context of the implicit block passed to it which gives you the ability to reference members of the leader without saying `leader.`. I think that we should favor `each` over `with` and not use `with` at all when we're talking about a single member

**Comment by reset** [comment]
Ah I missed the part where you made the block implicit in this example. These are actually equivalent:

```
{{#if svc.me.follower}}
  slaveof {{svc.leader.sys.ip}} {{svc.leader.cfg.port}}
{{/if}}
```

```
{{#if svc.me.follower}}
  {{#with svc.leader as |leader|}}
    slaveof {{leader.sys.ip}} {{leader.cfg.port}}
  {{/with}}
{{/if}}
```

**Pull request merged**
