### PR TITLE
adds nell shamrell to maintainers list

### PR DESCRIPTION
**Pull request by nellshamrell**
Hoping to contribute to and assist with all of these aspects of Habitat, so went ahead and added myself as a maintainer to them.

Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
gif-keyboard-14137869312430837166

**Comment by adamhjk** [comment]
gif-keyboard-13842575547272509034

**Comment by nellshamrell** [comment]
Happy Bunny

**Pull request merged**
