### PR TITLE
Fix Hook output and remove "output" from HealthCheck and Hook errors

### PR DESCRIPTION
**Pull request by reset**
This PR accomplishes two goals:

1. stdout and stderr from running hooks will one again correctly be
   piped to the supervisor's output and it's originating service
   group will be included in it's preamble
2. The "output" member on the HealthCheck and Hook errors has been
   removed. See the description below for details

Originally we were storing the stdout of a failed hook and, by proxy, a
health check as a member of the error struct. We can't do this because
we don't know exactly how large the contents of the output would be and
this could cause the supervisor to crash. The output from hooks are
piped to the supervisor's console and can be retrieved from there.

gif-keyboard-569115800137743555

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
LGTM but I believe you need to apply `to_string_lossy` to the `OsStr` building the powershell statement. I can add that commit since it is easier for me to iterate on that.

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/193115733).

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/193115733).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/193115733).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
