### PR TITLE
[plan-build] Set the ownership of `results/*` to the same as the Plan.

### PR DESCRIPTION
**Pull request by fnichol**
If you work on a Linux workstation, raise a cheer! Your results
directory, .hart, and last_build.env should get the same ownership as
your `plan.sh` which was built against. No more `sudo rm -rf results`
just to clear them out. Ah, I feel much better...

giphy-downsized

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
I just want to check this quickly on a Mac/Docker run first, then I'll drop the "do not merge tag"

**Comment by fnichol** [comment]
Yup, looks good!

**Comment by reset** [comment]
tenor-170703513

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/233864698).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/233864698).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
