### PR TITLE
removing restriction for builds in progress

### PR DESCRIPTION
**Pull request by mgamini**
Signed-off-by: Garrett Amini <garrett@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
@mgamini looks good! Do you mind squashing your commits to one before we merge?

**Comment by raskchanky** [comment]
@mgamini just missing a dank gif 😁

**Comment by reset** [comment]
tenor-148228471

**Pull request merged**
