### PR TITLE
Add an API to allow updating an origin

### PR DESCRIPTION
**Pull request by raskchanky**
tenor-179570939

Closes https://github.com/habitat-sh/habitat/issues/3096

Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by mwrock** [comment]
This all looks good to me. I was thinking about needing to have validation around the default_visibility string and started wondering if it might be better to have the default_visibility be a boolean (is_public) or an enum if we anticipate more states than public or private. I know this would mean changing more stuff but now is the time to do it before release.

**Comment by chefsalim** [comment]
It looks like the other half of this change is already merged so my comment may be moot. I was thinking we might not want to touch Origin at all, but have a separate OriginSettings table, that we can expand over time instead of putting user-configuration directly into Origin.

**Comment by raskchanky** [comment]
@mwrock I specifically avoided a boolean field, just in case something weird arose in the future like `protected` or who knows what.  I figured it was better to allow for more than two choices now than have to do a data migration later.  Changing it to an enum is a good idea though.  I'll do that.

**Comment by raskchanky** [comment]
@chefsalim I think an `OriginSettings` table is a great idea, so we can expand things over time if we need to.  My only concern is time at this point.  Do you think it's important to implement that now?  My gut says to punt on that at this point and make an issue to implement that down the road.

**Comment by chefsalim** [comment]
I'll leave it up to you - if you want to go with this now, we can refactor later as needed. If you want to do the origin settings now, and take some extra time now instead of refactor time later, I'd definitely support you on that as well.

**Comment by raskchanky** [comment]
@chefsalim I'm going to merge this as is and write up an issue to do the `OriginSettings` refactor at some point in the future.

**Comment by raskchanky** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/273096383).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/273096383).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
