### PR TITLE
move user and group validation outside of service struct constructor so failed services can have persisted state

### LINKED ISSUE #2273: Inconsistency between sup load and status
Ubuntu 16.04.2 docker container, Habitat 0.22.0

The setup:

```
docker pull ubuntu:xenial
docker run -it ubuntu:xenial

apt-get update
apt-get install -y curl
curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | bash
hab sup run &
```

We now have Ubuntu 16.04, and hab and hab-sup 0.22.0. Try to load `core/nginx`:

```
root# hab sup load core/nginx
<installs nginx>
Waiting for the core/nginx service to enter the up state......hab-sup(MR): Starting core/nginx
hab-sup(MR): Unable to start core/nginx, hab-sup(UR)[src/util/users.rs:42:27]: Package requires group hab to exist, but it doesn't
.........
hab-sup(MN): The core/nginx service was not succesfully loaded: hab-sup(MR)[src/manager/mod.rs:228:12]: Service core/nginx not loaded
```

As expected, this fails because we haven't yet created the `hab` user required by the service. Let's add the user and then load the service:
```
root# useradd hab
root# hab sup status core/nginx
hab-sup(MN): The core/nginx service is not currently loaded.
root# hab sup load core/nginx
hab-sup(MN)[src/main.rs:247:23]: Service already loaded, unload 'core/nginx' and try again
```

The `status` command is checking whether the status persisted in the services.dat file is present. The `load` command is checking whether there is a spec file present.

```
root# curl http://localhost:9631/services
[]
root# cat /hab/sup/default/data/services.dat
[]
root# cat /hab/sup/default/specs/nginx.spec
ident = "core/nginx"
group = "default"
depot_url = "https://willem.habitat.sh/v1/depot"
topology = "standalone"
update_strategy = "none"
binds = []
desired_state = "up"
start_style = "persistent"
```

Removing the spec file, or running `unload` on the service will allow the `load` command to work properly.

### PR DESCRIPTION
**Pull request by mwrock**
This fixes #2273. Currently creating a `Service` struct checks the `svc_user` and `svc_group` to ensure they are valid. If this fails, The service fails upon loading. Strictly speaking the spec is saved so any subsequent attempt to load the service fails stating that it is already loaded. Further, because the `Service` cannot be constructed, it also cannot be persisted and therefore the `status` command will not include it and will state that it is not loaded when the service is explicitly queried.

This PR moves the user/group validation out of the Service creation and into a separate `assert_pkg_user_and_group` that the `Service` calls berfore creating the service directories. `Service::load` no longer creates the svc directories. It simply loads the service. The supervisor manager now calls the service to create those directories when adding active services.

Signed-off-by: Matt Wrock <matt@mattwrock.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by reset** [comment]
This is good enough to get us over the finish line! In a future refactor I might suggest avoiding cloning the current state of services into a HashMap owned by the manager struct itself. Aside from the additional allocations (which really aren't much) this creates a potential caching problem which could result in some bugs

@thesentinels approve

tenor-93850701

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/230503764).

**Pull request merged**
