### PR TITLE
Update my role in MAINTAINERS

### PR DESCRIPTION
**Pull request by reset**
gif-keyboard-9202568500358984097

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by adamhjk** [comment]
@reset you're the LT for core, but I'm still the project lead. :) 

gif-keyboard-14034402818708454166

**Comment by adamhjk** [comment]
gif-keyboard-17602520099296275432

**Comment by reset** [comment]
Fixed it

gif-keyboard-3194714377961668336

**Comment by adamhjk** [comment]
@thesentinels approve

gif-keyboard-14537891374303162381

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/204339569).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/204339569).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
