### PR TITLE
Link key cache into Docker export root filesystem

### PR DESCRIPTION
**Pull request by christophermaier**
When exporting a Docker container, we now link in the Habitat key
cache. This is mainly to support initial experiences where users are
trying Habitat out, but have not uploaded keys to Builder (for
whatever reason). If the keys are not present in the cache, Habitat
will attempt to retrieve the public key from Builder. This will fail
if the key is not in Builder (obviously!), which can be confusing to
new users.

As coded, there is a change in behavior here; previously, an exported
Docker image would contain all the public keys downloaded in the
course of generating the image. Since we now are symlinking the key
directory in (and unlinking after we've downloaded the packages), the
keys will no longer be present in the image. In practice, this shouldn't
cause any issues. If you are running a Habitat Docker container with
an update strategy of "none", there's no need for keys anyway, because
nothing is going to be downloaded from Builder. If you're running with
an update strategy, you're going to be downloading new versions of
your software from Builder, which inherently means keys will be
available and downloaded as needed.

(One last bit is needed for this to completely work as desired: public keys
need to be pulled into the studio as well as the private keys we currently 
pull in. @fnichol is working on that now in parallel with this work. With that 
in place, #3495 will be fixed.)

Signed-off-by: Christopher Maier <cmaier@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by fnichol** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/283518587).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/283518587).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
