### PR TITLE
Swiftype config tweaks

### LINKED ISSUE #4543: Improve Swiftype indexing
We're currently using a Swiftype meta tag (name="body" in the <head> of our pages that is incorrectly telling Swiftype to ignore the real <body> content. Instead, we're setting it to be equal to the page description. This behavior was confirmed via Swiftype Support.

Re-naming that meta tag to something other than 'body' will instruct the Swiftype crawler to read the full content of the page body.

Additionally, Swiftype docs recommend not indexing repeated, global navigational elements, so those should be set for exclusion.

### PR DESCRIPTION
**Pull request by ryankeairns**
Fixes #4543 

Swiftype changes to improve search results.

Note: I contacted Swiftype support with regards to the meta tag we were using with a name="body" and learned that this would override the actual content in the <body> tag. In our case, we were assigning the value of this meta tag to the page description (from the page's front matter)... which means we likely weren't indexing the full page content.

Also, based on tutorials and docs on the Swiftype site, I've set the global top/side/footer nav sections to not be indexed.

Signed-off-by: Ryan Keairns <rkeairns@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by ryankeairns** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/336227164).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/336227164).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by ryankeairns** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by ryankeairns** [comment]
@thesentinels acceptance

**Comment by thesentinels** [comment]
:metal: I am sending your branch against master to our acceptance environment.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started the deployment of acceptance](https://travis-ci.org/habitat-sh/habitat/builds/336568352).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports acceptance has been deployed](https://travis-ci.org/habitat-sh/habitat/builds/336568352).

I love new and shiny websites!

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Comment by mgamini** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/338664420).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/338664420).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
