### PR TITLE
Add Etsy testimonial to www homepage

### PR DESCRIPTION
**Pull request by Padgett**
Signed-off-by: Joshua Padgett <jpadgett@chef.io>

screen shot 2016-06-22 at 17 11 35

### CODE REVIEW

**Comment by thesentinels** [comment]
By analyzing the blame information on this pull request, we identified @magwalk, @ryankeairns, @davidwrede, @smith and @cwebberOps to be potential reviewers

**Comment by TrevorBramble** [comment]
@thesentinels r+

**Comment by thesentinels** [comment]
:pushpin: Commit 8e5536c has been approved by `TrevorBramble`

**Comment by thesentinels** [comment]
:hourglass: Testing commit 8e5536c with merge 59eafab...

**Comment by thesentinels** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/habitat-sh/habitat/builds/139642260)

**Pull request merged**
