### PR TITLE
Tokyo is the next stop on the tour

### PR DESCRIPTION
**Pull request by nathenharvey**
Link home page to
https://pages.chef.io/HandsOnWithHabitat_Tokyo_RSVP.html

Signed-off-by: Nathen Harvey <nharvey@chef.io>

### CODE REVIEW

**Comment by mwrock** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/habitat/builds/225235368).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/habitat/builds/225235368).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
